### ISSUE TITLE
无法创建包括中文路径的时间序列[Bug] 

### ISSUE THREAD

**Issue by ccliushou** [apache/iotdb#10043]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

1.1.0

### Describe the bug and provide the minimal reproduce step

cli中执行：CREATE TIMESERIES root.pos.ps20230101.京A12345.status WITH DATATYPE=BOOLEAN, ENCODING=PLAIN

Query Fail:305: [INTERNAL_SERVER_ERROR(305)] Exception occurred: "CREATE TIMESERIES root.pos.ps20230101.京A12345.status WITH DATATYPE=BOOLEAN, ENCODING=PLAIN". executeStatement failed. null

### What did you expect to see?

期望创建成功。

### What did you see instead?

Query Fail:305: [INTERNAL_SERVER_ERROR(305)] Exception occurred: "CREATE TIMESERIES root.pos.ps20230101.京A12345.status WITH DATATYPE=BOOLEAN, ENCODING=PLAIN". executeStatement failed. null

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xingtanzjr** [comment]
Hi @ccliushou , thanks for reaching out. We have received your feedback and will investigate this issue

**Comment by xingtanzjr** [comment]
Hi @ccliushou , we have fixed the bug in branch rel/1.1, you can pull the latest code and have a try
