### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Shmming-86** [apache/iotdb#10328]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

V1.1.0

### Describe the bug and provide the minimal reproduce step

查询结果与预期不符

进行时间段范围查询时 使用 `WHERE (time >= xxxx AND time <= xxxx) ORDER BY time DESC LIMIT 10 OFFSET 0`查询时，查询结果错误，有部分最新的符合条件的结果未显示。

经过测试，发现通过缩小时间范围或者修改LIMIT条件可以查询出正确的结果

- 出现异常的查询语句

``` shell
---------------------
Starting IoTDB Cli
---------------------
 _____       _________  ______   ______    
|_   _|     |  _   _  ||_   _ `.|_   _ \   
  | |   .--.|_/ | | \_|  | | `. \ | |_) |  
  | | / .'`\ \  | |      | |  | | |  __'.  
 _| |_| \__. | _| |_    _| |_.' /_| |__) | 
|_____|'.__.' |_____|  |______.'|_______/  version 1.1.0 (Build: 807ec8b-dev)

IoTDB> SELECT aa.bb.cc_tag1 FROM root WHERE time >= 2023-06-26T00:00:00.000+08:00 AND time <= 2023-06-26T19:30:00.000+08:00 ORDER BY time DESC LIMIT 10 OFFSET 0
+-----------------------------+------------------+
|                         Time|root.aa.bb.cc_tag1|
+-----------------------------+------------------+
|2023-06-26T19:27:35.000+08:00|               2.0|
|2023-06-26T19:27:24.809+08:00|              16.0|
|2023-06-26T19:26:24.282+08:00|              22.0|
|2023-06-26T19:26:20.462+08:00|              13.0|
|2023-06-26T19:25:20.070+08:00|              13.0|
|2023-06-26T19:24:19.766+08:00|              16.0|
|2023-06-26T19:24:19.629+08:00|              19.0|
|2023-06-26T19:23:19.146+08:00|              19.0|
|2023-06-26T19:22:18.636+08:00|              17.0|
|2023-06-26T19:21:18.226+08:00|              19.0|
+-----------------------------+------------------+
Total line number = 10
It costs 0.005s
``` 

- 修改LIMIT条件后正确的查询结果
``` shell
IoTDB> SELECT aa.bb.cc_tag1 FROM root WHERE time >= 2023-06-26T00:00:00.000+08:00 AND time <= 2023-06-26T19:30:00.000+08:00 ORDER BY time DESC LIMIT 20 OFFSET 0
+-----------------------------+------------------+
|                         Time|root.aa.bb.cc_tag1|
+-----------------------------+------------------+
|2023-06-26T19:29:26.484+08:00|               3.0|     《----------------        缺失的结果
|2023-06-26T19:27:35.000+08:00|               2.0|
|2023-06-26T19:27:24.809+08:00|              16.0|
|2023-06-26T19:26:24.282+08:00|              22.0|
|2023-06-26T19:26:20.462+08:00|              13.0|
|2023-06-26T19:25:20.070+08:00|              13.0|
|2023-06-26T19:24:19.766+08:00|              16.0|
|2023-06-26T19:24:19.629+08:00|              19.0|
|2023-06-26T19:23:19.146+08:00|              19.0|
|2023-06-26T19:22:18.636+08:00|              17.0|
|2023-06-26T19:21:18.226+08:00|              19.0|
|2023-06-26T16:26:59.236+08:00|               0.0|
|2023-06-26T16:26:58.232+08:00|              13.0|
|2023-06-26T16:26:57.229+08:00|               0.0|
|2023-06-26T16:26:56.225+08:00|               5.0|
|2023-06-26T16:26:55.221+08:00|               3.0|
|2023-06-26T16:26:54.220+08:00|              18.0|
|2023-06-26T16:26:53.216+08:00|              15.0|
|2023-06-26T16:25:52.202+08:00|              15.0|
|2023-06-26T16:18:45.207+08:00|              15.0|
+-----------------------------+------------------+
Total line number = 20
```

- 修改时间范围后正确的查询结果
``` shell
IoTDB> SELECT aa.bb.cc_tag1 FROM root WHERE time >= 2023-06-26T19:23:00.000+08:00 AND time <= 2023-06-26T19:30:00.000+08:00 ORDER BY time DESC LIMIT 10 OFFSET 0
+-----------------------------+------------------+
|                         Time|root.aa.bb.cc_tag1|
+-----------------------------+------------------+
|2023-06-26T19:29:26.484+08:00|               3.0|    <=============  错误结果中缺失的数据
|2023-06-26T19:27:35.000+08:00|               2.0|
|2023-06-26T19:27:24.809+08:00|              16.0|
|2023-06-26T19:26:24.282+08:00|              22.0|
|2023-06-26T19:26:20.462+08:00|              13.0|
|2023-06-26T19:25:20.070+08:00|              13.0|
|2023-06-26T19:24:19.766+08:00|              16.0|
|2023-06-26T19:24:19.629+08:00|              19.0|
|2023-06-26T19:23:19.146+08:00|              19.0|
+-----------------------------+------------------+
Total line number = 9
It costs 0.007s
```

### What did you expect to see?

IoTDB> SELECT aa.bb.cc_tag1 FROM root WHERE time >= 2023-06-26T00:00:00.000+08:00 AND time <= 2023-06-26T19:30:00.000+08:00 ORDER BY time DESC LIMIT 10 OFFSET 0
+-----------------------------+------------------+
|                         Time|root.aa.bb.cc_tag1|
+-----------------------------+------------------+
|2023-06-26T19:29:26.484+08:00|               3.0| 
|2023-06-26T19:27:35.000+08:00|               2.0|
|2023-06-26T19:27:24.809+08:00|              16.0|
|2023-06-26T19:26:24.282+08:00|              22.0|
|2023-06-26T19:26:20.462+08:00|              13.0|
|2023-06-26T19:25:20.070+08:00|              13.0|
|2023-06-26T19:24:19.766+08:00|              16.0|
|2023-06-26T19:24:19.629+08:00|              19.0|
|2023-06-26T19:23:19.146+08:00|              19.0|
|2023-06-26T19:22:18.636+08:00|              17.0|
+-----------------------------+------------------+

### What did you see instead?

IoTDB> SELECT aa.bb.cc_tag1 FROM root WHERE time >= 2023-06-26T00:00:00.000+08:00 AND time <= 2023-06-26T19:30:00.000+08:00 ORDER BY time DESC LIMIT 10 OFFSET 0
+-----------------------------+------------------+
|                         Time|root.aa.bb.cc_tag1|
+-----------------------------+------------------+
|2023-06-26T19:27:35.000+08:00|               2.0|
|2023-06-26T19:27:24.809+08:00|              16.0|
|2023-06-26T19:26:24.282+08:00|              22.0|
|2023-06-26T19:26:20.462+08:00|              13.0|
|2023-06-26T19:25:20.070+08:00|              13.0|
|2023-06-26T19:24:19.766+08:00|              16.0|
|2023-06-26T19:24:19.629+08:00|              19.0|
|2023-06-26T19:23:19.146+08:00|              19.0|
|2023-06-26T19:22:18.636+08:00|              17.0|
|2023-06-26T19:21:18.226+08:00|              19.0|
+-----------------------------+------------------+

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by HTHou** [comment]
@JackieTien97 PTAL

**Comment by HTHou** [comment]
Hi, this bug has been fixed in latest version.
