### ISSUE TITLE
如何使用python接口获得存储的浮点数的字符串？

### ISSUE THREAD

**Issue by zlhliu** [apache/iotdb#10454]
python接口只能直接拿到浮点数，而不能获得存储的浮点数的字符串。获得的二进制值field.set_binary_value(value_bytes)也不知道如何unpack到字符串。

**Comment by HTHou** [comment]
field.get_string_value

**Comment by zlhliu** [comment]
cli中显示的float没有精度问题，但field.get_string_value读到的float仍然有精度问题。请问有直接读取内部存储的字符串的方法么。
我需要保留6位有效数字，比如cli中的79.06，使用get_string_value只能读到79.05999755859375。
![cf78feb9edd875d20eddeb7be726f26](https://github.com/apache/iotdb/assets/79457868/e8988247-59e5-4de8-afdb-f479fd75cd3e)
![c1118af30c18301e46c943fffceb726](https://github.com/apache/iotdb/assets/79457868/df32f193-2fc5-40f8-89f9-675bfe2b8a28)

**Comment by HTHou** [comment]
python语言的特性是浮点数默认都是double类型，这里的 float 强转 double 就会有精度损失。只有 IoTDB 里也使用 Double 类型才能避免这个问题。

**Comment by zlhliu** [comment]
谢谢，问题解决了
