### ISSUE TITLE
元数据按需加载到内存

### ISSUE THREAD

**Issue by lichanging** [apache/iotdb#10466]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Motivation

当前所有元数据在程序启动时会将所有的元数据都写入到内存里面，这样在元数据不断增加的场景中很容易导致内存不够用

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jixuan1989** [comment]
latest version has support it.

**Comment by lichanging** [comment]
> latest version has support it.

What is the specific version number that supports it?

**Comment by lichanging** [comment]
> latest version has support it.

What is the specific version number that supports it?

**Comment by qiaojialin** [comment]
@lichanging Hi, will support PBTree schema storage in 1.2.1 (at 8.30), schema_engine_mode=PBTree

Another feather to lower the memory occupation of schema is the schema(device) template(already in 1.1).
