### ISSUE TITLE
[Bug] Rest API query isn't closed, kill query doesn't work

### ISSUE THREAD

**Issue by atb2215** [apache/iotdb#10465]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

```
+-------+-----------+
|Version|  BuildInfo|
+-------+-----------+
|  1.1.1|d123b8e-dev|
+-------+-----------+
```

### Describe the bug and provide the minimal reproduce step

curl -H "Content-Type:application/json" -H "Authorization:Basic cm9vdDpyb290" -X POST --data '{"sql":"show databases"}' http://0.0.0.0:18080/rest/v2/nonQuery

Returns the correct result, however, when running "show query processlist" the query is still shown:
```
|                    Time|                QueryId|DataNodeId|ElapsedTime|                                               Statement|
|2023-07-06T05:51:40.167Z|20230706_055140_69968_1|         1|   1525.655|  show databases|
|2023-07-06T06:17:05.819Z|20230706_061705_85654_1|         1|      0.003|  show query processlist|

```
Running "kill all queries" or killing the specific query doesn't remove the query.

Running 'show databases' in the CLI or python returns the expected result and the query is does not appear in the "show query processlist"

### What did you expect to see?

The query removed from the processlist upon returning a result.  The query removed from the processlist when "kill all queries" is run.

### What did you see instead?

Queries from restv2 remain in the processlist.

### Anything else?

This impacts queries run by grafana.  Over time the memory maxes out.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by CloudWise-Lukemiao** [comment]
hi，
    I am using iotdb version 1.1.1 (https://dlcdn.apache.org/iotdb/1.1.1/apache-iotdb-1.1.1-all-bin.zip), and the problem has not been reproduced. The normal rest nonQuery interface cannot execute queries. The only difference is that it is executing show version. Your BuildInfo shows d123b8e-dev and mine shows d123b8e. I want to know more about information such as the download address of iotdb or Cluster information, etc.
<img width="714" alt="image" src="https://github.com/apache/iotdb/assets/76942485/077f8e66-e11b-405f-90f6-ed1bce700dfc">
<img width="565" alt="image" src="https://github.com/apache/iotdb/assets/76942485/f82a6bfa-7a81-443f-8293-798147db4396">
<img width="618" alt="image" src="https://github.com/apache/iotdb/assets/76942485/a92ec67f-2f2b-41ea-8e85-5a49145b3106">

**Comment by atb2215** [comment]
Interesting... I'm using the docker image built using the following:
```
docker run -d --name iotdb-service \
              --hostname iotdb-service \
              --sysctl net.core.somaxconn=65535\
              -p 6667:6667 \
              -p 18080:18080 \
              -e cn_internal_address=iotdb-service \
              -e cn_target_config_node_list=iotdb-service:10710 \
              -e cn_internal_port=10710 \
              -e cn_consensus_port=10720 \
              -e dn_rpc_address=iotdb-service \
              -e dn_internal_address=iotdb-service \
              -e dn_target_config_node_list=iotdb-service:10710 \
              -e dn_mpp_data_exchange_port=10740 \
              -e dn_schema_region_consensus_port=10750 \
              -e dn_data_region_consensus_port=10760 \
              -e dn_rpc_port=6667 \
              apache/iotdb:latest
```

**Comment by atb2215** [comment]
![image](https://github.com/apache/iotdb/assets/136280310/19de573a-3442-4949-8aa6-24b4edb310bd)
