### ISSUE TITLE
[Bug] 1.1.1版本时间对齐序列查最新值，偶发报错、少数据

### ISSUE THREAD

**Issue by zhouzhiy** [apache/iotdb#10753]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

1.1.1

### Describe the bug and provide the minimal reproduce step

对齐时间的时间序列查询最新值，sql报错，或者结果集错误（少数据）

### What did you expect to see?

正确结果

### What did you see instead?

偶现301错误，或者少数据

下图为少数据的，应该查出48条数据，结果查出了9条
![image](https://github.com/apache/iotdb/assets/52025735/73249ac9-aed3-4dc5-9015-f7bea94e3abe)
下图为报错的日志
![image](https://github.com/apache/iotdb/assets/52025735/825ac825-5b98-437b-9942-5282e9ae02d6)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JackieTien97** [comment]
你可以试一下1.1.2，已经修复过相关的问题了
