### ISSUE TITLE
[Bug] 文件compact完成导致reader缓存文件流未close的问题

### ISSUE THREAD

**Issue by IceMimosa** [apache/iotdb#10809]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

1.3.0-SNAPSHOT

### Describe the bug and provide the minimal reproduce step

文件在compact完成之后，FileReaderManager中的文件流没有被释放，导致已经deleted的文件会越来越多。
![image](https://github.com/apache/iotdb/assets/9958300/50a28b79-42a4-466d-a600-94417b23b9e6)

### What did you expect to see?

读缓存文件需要被正确释放

### What did you see instead?

无

### Anything else?

FileReaderManager还需要进一步优化，比如缓存大小控制、已删除文件需要close等。

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by HTHou** [comment]
https://github.com/apache/iotdb/pull/10688 fixed this issue.
