### ISSUE TITLE
[Bug] SessionPool for Python3.8 failed to compile with syntax errors

### ISSUE THREAD

**Issue by pyh1998** [apache/iotdb#10842]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

IotDB: 1.1.2
Python: 3.8

### Describe the bug and provide the minimal reproduce step

When I upgraded to version 1.1.2 and try to use the session pool, the SessionPool.py file fails to compile with a syntax error.

**Error message:**
```
File "D:\Anaconda\lib\site-packages\iotdb\SessionPool.py", line 65, in SessionPool
    def __poll_session(self) -> Session | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
![image](https://github.com/apache/iotdb/assets/71625437/a8d56f34-c3f7-4b6e-b182-d97c7e8fe1fc)

### What did you expect to see?

Programmes can be compiled and run properly

### What did you see instead?

The programme failed to compile

### Anything else?

Please fix this problem ASAP and support python 3.8

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JackieTien97** [comment]
@ycycse take a look

**Comment by ycycse** [comment]
Hi,  thank you for bringing up the issue and providing feedback about the bug on IoTDB! Writing union types as X | Y is the feature of python 3.10, actually we should avoiding using it to ensure the compatibility.

You can also use it now by the folllowing methods:

- update your python to 3.10

or

- remove "-> Session|None" to avoid use this feature in codes and recompile py-client in iotdb

**Comment by pyh1998** [comment]
@ycycse thanks for your answer!
Will this bug be fixed in the next version? and when will the next version be released?

**Comment by ycycse** [comment]
> @ycycse thanks for your answer! Will this bug be fixed in the next version? and when will the next version be released?

It will. But next version may be released after accumulating a certain amount of features, it may be not very fast. This is a relatively minor compatibility issue so I advice you to directly fix it in your repo.

**Comment by ycycse** [comment]
> @ycycse thanks for your reply! Will this bug be fixed in the next version? and when will the next version be released?

If you only use the session in iotdb package of python. You can try to upgrade 1.2.1 which won't have the problem of compatibility.

**Comment by pyh1998** [comment]
@ycycse I am little confused with 'py-client', how to upgrade it?

**Comment by ycycse** [comment]
> @ycycse I am little confused with 'py-client', how to upgrade it?

How do you use sessionPool and upgraded to version 1.1.2, did you use 'pip install'?

**Comment by ycycse** [comment]
1. We will relase 1.2.1 this week, you can wait and upgrade by 'pip install apache-iotdb==1.2.1'
2. Download the source code of iotdb to your local machine. Fix the code in iotdb-client/client-py/iotdb/SessionPool.py, then run `python3 setup.py sdist bdist_wheel` in 'iotdb-client/client-py/' to build your own package, then pip install the .whl file in 'iotdb-client/client-py/dist'

**Comment by pyh1998** [comment]
@ycycse Hi, are you ready to release version 1.2.1?
I'm still waiting for a new version that will enable python 3.8 to use SessionPoll.

**Comment by ycycse** [comment]
> @ycycse Hi, are you ready to release version 1.2.1? I'm still waiting for a new version that will enable python 3.8 to use SessionPoll.

I'm afraid our release has encountered some delays... I will inform you as soon as the release is successful.

**Comment by ycycse** [comment]
> @ycycse Hi, are you ready to release version 1.2.1? I'm still waiting for a new version that will enable python 3.8 to use SessionPoll.

Hi, 1.2.1 has already been released https://github.com/apache/iotdb/releases/tag/v1.2.1.
