### ISSUE TITLE
[Bug] Too many open files

### ISSUE THREAD

**Issue by suyx1999** [apache/iotdb#10961]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

IoTDB version: 1.1.2 release

### Describe the bug and provide the minimal reproduce step

I try to load a set of tsfiles into iotdb. The number of the tsfiles is nearly 170 and the disk occupancy of the tsfiles is 6GB. However, the data node log reports an error "Too many open files". 
I have set the max open files, but it does not work.
![91693050449_ pic](https://github.com/apache/iotdb/assets/51471745/e04844c2-adf4-4e14-9d1c-b7f29d7213e9)

### What did you expect to see?

Successful loading

### What did you see instead?

![81693050440_ pic](https://github.com/apache/iotdb/assets/51471745/30bce52e-f4ca-41c7-8324-d0ecd33aacfa)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by HTHou** [comment]
@SteveYurongSu

**Comment by HTHou** [comment]
Hi, you may need to check whether the timestamp precision of the sources file matches the configuration of IoTDB.

**Comment by suyx1999** [comment]
Thanks, I change the parameter timestamp_precision in `iotdb-common.properties` and it works
