### ISSUE TITLE
[Feature request] Add placeholder support in down-sampled time series

### ISSUE THREAD

**Issue by qubic** [apache/iotdb#11173]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Motivation

Is it possible to add placeholder support in down-sampled time series ?

Like this: 

```
CREATE CONTINUOUS QUERY cq1
BEGIN
  SELECT max_value(value)
  INTO root.sg_bk.::(value_max)
  FROM root.sg.*.*
  GROUP BY(10s)
END;

```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JackieTien97** [comment]
Actually, after downsample query, the DataSet headers are like `max_value(root.XX.XX.XX)`, so we cannot take it as a raw path, so we cannot extract path from `max_value(root.XX.XX.XX)`, and if we use group by level clause the case will be more complex.

**Comment by JackieTien97** [comment]
BTW, you can use align by device clause to use placeholder, like the following:

<img width="1062" alt="image" src="https://github.com/apache/iotdb/assets/16079446/106626ef-fd80-4173-a3e7-d40c45674a74">
