### ISSUE TITLE
[Bug] IoTDB 查询性能非常差

### ISSUE THREAD

**Issue by ufoe** [apache/iotdb#11317]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

1.2.1

### Describe the bug and provide the minimal reproduce step

<img width="641" alt="image" src="https://github.com/apache/iotdb/assets/1306250/a7511d83-c0f1-4220-8fc8-5f0cd864ac99">

默认按周时间分区的

查询一个指定设备的一个信号，查询1天内的数据就很慢，一般都要超过5秒，偶发要20秒、30秒

### What did you expect to see?

响应在秒级、1秒内

### What did you see instead?

超过5秒，偶发30秒或者更长

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JackieTien97** [comment]
这个sql正常的时候大概耗时多久？去掉order by time asc 执行的话，大概多少秒啊？

**Comment by lancelly** [comment]
请问可以提供数据和具体版本commit吗，如果不能的话，可以用Jprofiler抽样看一下查询时候的耗时分布吗？
