### ISSUE TITLE
[Bug] Skip downsampling in sample function if proportion > 0.5

### ISSUE THREAD

**Issue by fuwei3140** [apache/iotdb#11334]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

1.1.x 1.2.x

### Describe the bug and provide the minimal reproduce step

![image](https://github.com/apache/iotdb/assets/88534321/1aa70206-f20e-43d2-abf9-36ce6293ba08)
Full data returned instead of downsampled data when proportion > 0.5 in all sample functions including equal_size_bucket_agg_sample. However, the interface documentation allows the use of values between (0,1].

### What did you expect to see?

If proportion is 0.8, I expect to receive 80% of the downsampled data.

### What did you see instead?

Full dataset returned.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JackieTien97** [comment]
Actually, it seems that you misunderstand the meaning of proportion parameter. Now, proportion is used to decide how many sample buckets we will have, `bucketSize = (int) (1 / proportion);`, so if proportion is 0.5, we will get a bucket whose size is 2, which means we will sample one point for each two data points. if proportion is larger than 0.5, like 0.8, the bucket size is always 1, which means we will sample one point for each one data point(yes, that's doing nothing). However, if proportion is 0.1, the bucket size is 10, which means we will sample one point for each 10 data points.

It's not a bug, proportion is just defined like that in `EqualSizeBucketSample` method.

**Comment by JackieTien97** [comment]
Actually, it seems that you misunderstand the meaning of proportion parameter. Now, proportion is used to decide how many sample buckets we will have, bucketSize = (int) (1 / proportion);, so if proportion is 0.5, we will get a bucket whose size is 2, which means we will sample one point for each two data points. if proportion is larger than 0.5, like 0.8, the bucket size is always 1, which means we will sample one point for each one data point(yes, that's doing nothing). However, if proportion is 0.1, the bucket size is 10, which means we will sample one point for each 10 data points.

It's not a bug, proportion is just defined like that in EqualSizeBucketSample method.
