### ISSUE TITLE
SessionDataSet 结构体转为 df 数据结构的时候 binary 为什么要 decode

### ISSUE THREAD

**Issue by Nancyskier** [apache/iotdb#11356]
https://github.com/apache/iotdb/blob/960952e0a7d1eaf8d589fcc394bbc997ce0f12ba/iotdb-client/client-py/iotdb/utils/IoTDBRpcDataSet.py#L312C15-L312C15

execute_query_statement()  return 的 SessionDataSet 结构体转为 df 数据结构的时候 binary 为什么要 decode，decode 的时候报错了

**Comment by HTHou** [comment]
目前的应用是想直接存储二进制类型的数据吗？

**Comment by Nancyskier** [comment]
> 目前的应用是想直接存储二进制类型的数据吗？

目前还不存储，目前使用到的场景是查询结果转为dataframe来使用。

**Comment by HTHou** [comment]
IoTDB 现在没有单独的binary 数据类型，只有TEXT。这里转df的时候默认这里的binary是一个可以decode 的TEXT类型值了。

**Comment by Nancyskier** [comment]
好的，那先手动处理了。close 掉了
