### ISSUE TITLE
[Bug] WAL目录清理线程异常，目录持续变大，最终导致数据无法写入

### ISSUE THREAD

**Issue by IceMimosa** [apache/iotdb#11480]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

rc/1.2.2

### Describe the bug and provide the minimal reproduce step

WAL清理线程工作异常，疑似死循环，导致WAL目录持续飙升，最终导致系统不可用。重启后恢复正常，暂无恢复步骤

### What did you expect to see?

希望WAL目录正常清理

### What did you see instead?

![image](https://github.com/apache/iotdb/assets/9958300/5e26be9a-6d37-4c1a-9353-67694d38efa9)
![c49077aa-34a1-4c44-8c3d-5e91d6fb0b9e](https://github.com/apache/iotdb/assets/9958300/6f07c298-84b1-4aa6-9feb-2395ea17e49b)
![7eb5a4c9-a945-4117-a6f9-0ca2d909c221](https://github.com/apache/iotdb/assets/9958300/9ad26688-785c-40be-acdc-be3088761f86)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by wanghui42** [comment]
hello，是否有使用 pipe 呢

**Comment by caozj1011** [comment]
You can upgrade to the latest code of master to verify that the issue has been fixed, look this PR: 
 [https://github.com/apache/iotdb/pull/11017](url)

**Comment by caozj1011** [comment]
In the meantime, you can look at the specific commitId from the CLI command line, let me check this version of the code. Please reply me when you have specific commitId, and take a screenshot of commitId.

**Comment by IceMimosa** [comment]
@caozj1011 rc/1.2.2 应该包含了这个commit了，我怀疑可能是follower有问题，导致wal膨胀。重启后没保留现场，我这边再观察一段时间，感谢回复。
