### ISSUE TITLE
1.2.2版本flink-sql-cdc bug

### ISSUE THREAD

**Issue by bigdata-spec** [apache/iotdb#11537]
1.测出cdc.port为8080，代码只能运行一次有数据，且数据重复且往iotdb写数据不再继续打印数据，第二次再跑一条数据都没。

![image](https://github.com/apache/iotdb/assets/23710717/7b6b0055-1fc1-4e4f-9b6b-d3b5da87ba55)

2.集群重启后8080端口自动起来了
![image](https://github.com/apache/iotdb/assets/23710717/07e4200e-d3af-45dc-bf84-4dc11c836c76)

**Comment by SteveYurongSu** [comment]
@bigdata-spec 感谢反馈！这个问题在 master 上已经修复，可以重新尝试。如果继续有问题，可继续留言。

**Comment by TheDawnXu** [comment]
这个8080端口是什么服务的端口啊 只有集群的时候有？本地测试单机的时候不启动？

**Comment by TheDawnXu** [comment]
> @bigdata-spec 感谢反馈！这个问题在 master 上已经修复，可以重新尝试。如果还有问题，可继续留言。

我使用了1.3.0的版本，感觉问题还在
