### ISSUE TITLE
[Bug] Running compaction task failed

### ISSUE THREAD

**Issue by zhaozhihua2008** [apache/iotdb#11600]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

0.13.2

### Describe the bug and provide the minimal reproduce step

程序不停的报错：
2023-11-23 07:44:20,541 [pool-7-IoTDB-Compaction-5] ERROR o.a.i.d.e.c.t.AbstractCompactionTask:72 - Running compaction task failed
java.lang.InterruptedException: [Compaction] compaction for target file [file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699280358127-1-0-1.cross, status: UNCLOSED

实际上/opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699280358127-1-0-1.cross 这个文件并不存在？而且现在iotdb查询经常报慢日志，跟上面的报错有关系吗？

### What did you expect to see?

程序处理正常，不在报错。

### What did you see instead?

2023-11-23 07:44:20,541 [pool-7-IoTDB-Compaction-5] ERROR o.a.i.d.e.c.t.AbstractCompactionTask:72 - Running compaction task failed
java.lang.InterruptedException: [Compaction] compaction for target file [file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699280358127-1-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699316349952-3-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699327159202-5-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699328442503-6-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699329729911-7-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699331259191-8-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699332750213-10-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699334359729-11-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699352273930-13-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699353685391-14-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699354887393-15-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699356760396-16-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699358348346-18-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699360214476-19-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699361607438-21-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699363055505-22-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699364305598-23-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699365786440-25-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699367020597-26-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699368466462-27-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699369783495-29-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699370972741-30-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699372593036-31-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699374039658-33-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699508520887-42-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699519576602-44-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699520753636-45-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699521978854-46-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699523197960-47-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699524428737-49-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699525659687-50-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699526889323-51-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699528119616-52-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699529352486-54-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699530623668-55-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699531854868-56-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699533079856-58-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699534306239-59-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699535531732-60-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699536757815-61-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699537980118-63-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699539205992-64-0-1.cross, status: UNCLOSED, file is /opt/iotdb/apache-iotdb-0.13.2-all-bin/sbin/../../data/data/sequence/root.tb/0/0/1699540431659-65-0-1.cross, status: UNCLOSED

### Anything else?

而且现在iotdb查询经常报慢日志，跟上面的报错有关系吗？
2023-11-23 00:05:15,986 [pool-19-IoTDB-Query-5] INFO  o.a.i.d.s.t.i.TSServiceImpl$QueryTask:246 - Cost: 6902 ms, sql is select avg(ele_a_value) as ele_a_value, avg(ele_b_value) as ele_b_value, avg(ele_c_vlaue) as ele_c_vlaue, avg(l_ec_value) as l_ec_value from root.tb.ec_meter.* group by ([2023-11-22 23:42:00,2023-11-22 23:45:00),1m) align by device

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by shuwenwei** [comment]
.cross 文件是合并过程中产生的临时文件，如果合并任务正常执行完成会重命名并替换掉对应的源文件，如果像上面这样失败了就会被删除。可以尝试升级新版本，大概率已经修复了。可以在 log_datanode_all.log 中搜索一下 CompactionExceptionHandler 看看更详细的日志

**Comment by zhaozhihua2008** [comment]
谢谢。手动执行运维命令，flush，merge。之后无此问题了。 主要我们的路径中有数字，升级到1.0 报错，暂时无法升级。
