### ISSUE TITLE
Connection reset by peer:socket write error

### ISSUE THREAD

**Issue by shexianguanfang** [apache/iotdb#1164]
定时写入数据的时候偶尔会出现这个问题,出现这个错误,执行下次定时写入程序就写不进去了
客户端,服务端版本0.9.2
[logs.zip](https://github.com/apache/incubator-iotdb/files/4590510/logs.zip)
![测试程序1](https://user-images.githubusercontent.com/63700415/81250976-d72e2680-9054-11ea-9d5c-6ea962aa25e6.png)
![测试程序2](https://user-images.githubusercontent.com/63700415/81250982-d8f7ea00-9054-11ea-8d22-20aacfe4609b.png)

**Comment by jixuan1989** [comment]
Hi many thanks.

@qiaojialin ,

> Parsing error, statement [CREATE TIMESERIES root.hn.gd.na.1q.status WITH DATATYPE=BOOLEAN, ENCODING=PLAIN] failed when parsing AST tree to generate logical operator. Detailed information: [line 1:33 mismatched input 'q' expecting WITH near '1'. Please refer to SQL document and check if there is any keyword conflict.]

0.9.2版本应该支持以数字开头的path吧？（1q）。请排查下。

> org.apache.iotdb.db.exception.query.IllegalASTFormatException: Parsing error, statement [CREATE TIMESERIES root.hn.gd.na.phase1.device WITH DATATYPE=TEXT, ENCODING=PLAIN] failed when parsing AST tree to generate logical operator. Detailed information: [line 1:39 mismatched input 'device' expecting set null]

以及这句SQL。

**Comment by jixuan1989** [comment]
@shexianguanfang 0.10起才支持数字开头的path。例如咱们`root.hn.gd.na.1q.status` 中这个`1q`在0.9是不支持的。

另外0.9里`device`是关键词，所以path中不能有device，@qiaojialin 看看这个怎么改。

**Comment by qiaojialin** [comment]
device 关键字避免用吧，客户端做个转化

**Comment by qiaojialin** [comment]
reset 这个错误可以在 session 和 jdbc 里加个重连重试机制来屏蔽掉

**Comment by shexianguanfang** [comment]
好的,谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jialin Qiao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月12日(星期二) 中午1:42
收件人:&nbsp;"apache/incubator-iotdb"<incubator-iotdb@noreply.github.com&gt;;
抄送:&nbsp;"1171085170"<1171085170@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-iotdb] Connection reset by peer:socket write error (#1164)





 
reset 这个错误可以在 session 和 jdbc 里加个重连重试机制来屏蔽掉

**Comment by shexianguanfang** [comment]
之前刚开始用,不太了解,以后注意,谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jialin Qiao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月12日(星期二) 中午1:41
收件人:&nbsp;"apache/incubator-iotdb"<incubator-iotdb@noreply.github.com&gt;;
抄送:&nbsp;"1171085170"<1171085170@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-iotdb] Connection reset by peer:socket write error (#1164)





 
device 关键字避免用吧，客户端做个转化

**Comment by shexianguanfang** [comment]
好的,谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiangdong Huang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 下午5:47
收件人:&nbsp;"apache/incubator-iotdb"<incubator-iotdb@noreply.github.com&gt;;
抄送:&nbsp;"1171085170"<1171085170@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-iotdb] Connection reset by peer:socket write error (#1164)





 
@shexianguanfang 0.10起才支持数字开头的path。例如咱们root.hn.gd.na.1q.status 中这个1q在0.9是不支持的。
 
另外0.9里device是关键词，所以path中不能有device，@qiaojialin 看看这个怎么改。

**Comment by qiaojialin** [comment]
Session 加了重连机制，可以拉一下master代码测试一下 0.10.0-SNAPSHOT 版本
