### ISSUE TITLE
How does apache IOTDB query the time of the last change of data value?

### ISSUE THREAD

**Issue by t59688** [apache/iotdb#11791]
In IoTDB, there are time series under root.device_id, where xxxx represents multiple series. I would like to query for the last changed value and the time of change under root.device_id. How should I write the query statement?

such as :1,2,2,3,3,3,3,3,3，i need find  when data change  from 2 to 3

**Comment by wanghui42** [comment]
@JackieTien97

**Comment by Beyyes** [comment]
Hi, you can see the answer in this links: https://stackoverflow.com/questions/77719939/how-does-apache-iotdb-query-the-time-of-the-last-change-of-data
