### ISSUE TITLE
tsfile output error

### ISSUE THREAD

**Issue by myysophia** [apache/iotdb#11967]
1. iotdb version: 1.2.2   , 1C1D
2. command
`
export-tsfile.sh -h 127.0.0.1-p 6667 -u root -pw root -f root.tt-td /tmp/root.emsplus -q "select * from root.tt.**"
`
3. error
`
Starting IoTDB Client Export Script
Cannot dump result because: 301: There is not enough memory to execute current fragment instance, current remaining free memory is 86762854, estimated memory usage for current fragment instance is 270139392
`

4. databnode data size
`
root@iotdb-0:/iotdb# du -sh *
112K    conf
8.3M    data
40K     ext
85M     lib
16K     LICENSE
68K     licenses
45M     logs

`

**Comment by Beyyes** [comment]
datanode_memory_proportion参数控制分给查询的内存，chunk_timeseriesmeta_free_memory_proportion控制查询执行可用的内存。
默认情况下分给查询的内存为堆内存*30%，查询执行可用的内存为查询内存的20%。
报错显示当前剩余查询执行可用内存为86762854B=82.74MB，该查询预估使用执行内存270139392B=257.6MB。

在不改变默认参数的前提下，调大IoTDB的堆内存(通过datanode-env.sh调整)，配置4.2G（4.2*1024MB=4300MB），4300*30%*20%=258M>257.6M，可以满足要求。
或者更改datanode_memory_proportion、chunk_timeseriesmeta_free_memory_proportion参数，使查询执行可用内存>257.6MB。

**Comment by myysophia** [comment]
3q
