### ISSUE TITLE
How to compile client-cpp in Windows?

### ISSUE THREAD

**Issue by 8188** [apache/iotdb#11981]
AT root path, run command: 
`mvn package -P compile-cpp -pl client-cpp,server,example/client-cpp-example -am ...` 
and report: 
`[ERROR] [ERROR] Could not find the selected project in the reactor: client-cpp @`
Who can provide help or give me a compiled package?

**Comment by HTHou** [comment]
Hi, you can find it here.

https://github.com/thulab/iotdb-daily-build/releases/tag/2024-01-25-java8-apache-iotdb

**Comment by 8188** [comment]
Thank you! @HTHou
