### ISSUE TITLE
iotdb-env.sh 配置java_home如果直接指定Java路径报错找不到Java (Java not found if I set the JAVA_HOME variable in iotdb-env.sh)

### ISSUE THREAD

**Issue by juice411** [apache/iotdb#1220]
![图片](https://user-images.githubusercontent.com/10968514/82197901-1baba300-992e-11ea-8d82-4ea7646e5d5d.png)

图片上的Java路径是确实存在的，但启动时会报错：
Unable to find java executable. Check JAVA_HOME and PATH environment variables.

**Comment by samperson1997** [comment]
Hi, @SilverNarcissus could you solve this issue?
