### ISSUE TITLE
OpenSSL version for IoTDB-Client CPP Example build faliure

### ISSUE THREAD

**Issue by Thomas-Niu** [apache/iotdb#12260]
当我尝试编译C++客户端时，我经过一番努力，1.0.0版本的客户端确实可以编译出来。但是当我尝试编译IoTDB-Client CPP Example时，出现了error Link2019：无法解析的外部符号_SSL_*,我确信这些和openssl的有关，请问对于1.0.0的版本来讲，openssl有确定能够编译通过的版本吗？编译错误如下所示
![屏幕截图 2024-03-30 120040](https://github.com/apache/iotdb/assets/58394033/767e5294-26af-43a2-a004-2d7ec8807484)

**Comment by HTHou** [comment]
可以参考这个 https://github.com/thulab/iotdb-daily-build/actions/runs/8490630117/job/23261910255

**Comment by Thomas-Niu** [comment]
> 可以参考这个 https://github.com/thulab/iotdb-daily-build/actions/runs/8490630117/job/23261910255

谢谢你的建议，我使用的是vs2015进行boost，openssl以及iotdb的编译。目前来看，openssl的版本不对，尝试过3.**和1.1.1stable版本，但是仍然无法解决这个问题

**Comment by Thomas-Niu** [comment]
IoTDB 1.0.0 发布版64bit编译成功
1) openssl: Win64OpenSSL-3_2_1
2) boost: 1.72
使用maven将compile _tools编译成功后，再用vs打开client-cpp-example后，链接对应的lib和include路径即可一把过。
