### ISSUE TITLE
[Bug] NPE when deleting timeseries via Java API

### ISSUE THREAD

**Issue by bossenti** [apache/iotdb#12473]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

1.3.0 (Java API)

### Describe the bug and provide the minimal reproduce step

Deleting a time series via the Java API yields to a NullPointerExecption.

```Java
sessionPool.executeQueryStatement(DELETE timeseries root.*)
```
leads to:

```text
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "columnNameList" is null
at org.apache.iotdb.rpc.IoTDBRpcDataSet.<init>(IoTDBRpcDataSet.java:104)
at org.apache.iotdb.isession.SessionDataSet.<init>(SessionDataSet.java:121)
at org.apache.iotdb.session.SessionConnection.executeQueryStatement(SessionConnection.java:399)
at org.apache.iotdb.session.Session.executeStatementMayRedirect(Session.java:791)
at org.apache.iotdb.session.Session.executeQueryStatement(Session.java:763)
```

Nevertheless, the time series is deleted so the query is executed successfully but there seems to be an issue when creating the response object.

### What did you expect to see?

Executing the query without an exception

### What did you see instead?

The stack trace as shown above.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by HTHou** [comment]
Hi @bossenti , `executeQueryStatement` is for query statement only. You should use `executeNonQueryStatement` for delete statement.

**Comment by bossenti** [comment]
My bad 🙈 Please apologize, thank you for your help!
