### ISSUE TITLE
分组查询时,时间跨度过大会导致服务器崩溃

### ISSUE THREAD

**Issue by 18816837260** [apache/iotdb#12499]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

1.2.2

### Describe the bug and provide the minimal reproduce step

分组SQL查询
group by ([2024-04-13 09:00:00, 20242024-04-19T16:00:00), 1m, 1m) ;
我把结束时间2024-04-19T16:00:00写成了20242024-04-19T16:00:00
然后程序一直执行到服务器崩溃。

### What did you expect to see?

希望可以配置单个任务最大的内存消耗。

### What did you see instead?

SQL是18:00执行,直到18:15分左右服务器告警。我们重启服务后才回复正常
![1715308242103](https://github.com/apache/iotdb/assets/114205220/203116b2-96df-4f07-b075-44d28ac3b39e)

### Anything else?

无

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ycycse** [comment]
Hi, for each time period, a corresponding TTimePartitionSlot object is generated. When too many objects occupy memory, there will be an issue of insufficient JVM memory. I can add a memory check at the planning stage to avoid this problem.
![image](https://github.com/apache/iotdb/assets/51467236/fc984716-5e80-49d9-b983-f0febfa2e9b5)

**Comment by JackieTien97** [comment]
fixed in https://github.com/apache/iotdb/pull/12725
