### ISSUE TITLE
[Feature request] Byte array data type

### ISSUE THREAD

**Issue by HXCK3D** [apache/iotdb#12588]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Motivation

There is currently no data type for a byte array in IotDB.

### Solution

Add a new data type for byte array. For example, it can be called BYTES.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by HTHou** [comment]
We are introducing new data types. https://github.com/apache/iotdb/pull/12576

**Comment by HTHou** [comment]
For current version, you can use TEXT to store byte array data. Here is an example.
![image](https://github.com/apache/iotdb/assets/25913899/7018a768-aeb5-4926-8bb7-019ba7239ea7)
