### ISSUE TITLE
[Feature request] Allow Pandas >= 2

### ISSUE THREAD

**Issue by rmpinchback** [apache/iotdb#12591]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Motivation

I ran into a situation where I was trying to install several libraries via pip that had pandas dependencies, and one of them required >= 2 on the pandas version.  While the requirements.txt in source control for the iotdb Python client doesn't indicate a restriction for not using pandas 2+, the metadata in the setup.py file restricts to less than v2.

### Solution

If there isn't a functional reason for the limitation then I'd suggest removing the "<1.99.99" restriction.  Also the minimum required version should probably be updated to agree with what is in the requirements.txt file, which it currently doesn't.

### Alternatives

No real alternative comes to mind.  Pandas v2 has been out for quite awhile now.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by HTHou** [comment]
Hi, I don't think we have such "<1.99.99" restriction for pandas. 
https://github.com/apache/iotdb/blob/baf37c3711d907ed15cc7a99f8d9b16e7c7eceea/iotdb-client/client-py/requirements.txt#L20

Moreover, the python CI is using the latest pandas v2.2.2, and it works well.
https://github.com/apache/iotdb/actions/runs/9262251482/job/25478871454

**Comment by HTHou** [comment]
Oh..okay, I know where the problem is...
https://github.com/apache/iotdb/blob/baf37c3711d907ed15cc7a99f8d9b16e7c7eceea/iotdb-client/client-py/resources/setup.py#L44

**Comment by rmpinchback** [comment]
Awesome, ty!  I should have mentioned setup.py, apologies for that.  I had to hunt around a bit for it myself.   I was seeing the effect of the constraint from Jenkins build logs, but it took a little poking around before I could see the root problem.

**Comment by HTHou** [comment]
Any problem of this PR? https://github.com/apache/iotdb/pull/12601 You can give an approval if there is no problem and then I'll merge it.

**Comment by rmpinchback** [comment]
Commented on the PR, thumbs up.  I think you can close this now.
