### ISSUE TITLE
可以有导入导出元数据的功能吗(Could IoTDB export the schema and import into another IoTDB?)

### ISSUE THREAD

**Issue by juice411** [apache/iotdb#1263]
![图片](https://user-images.githubusercontent.com/10968514/82851451-70ed4300-9f32-11ea-92d3-7272b7f135b7.png)
比如这个元数据表，我想导出该路径下的所有元数据为CSV文件，然后在别的服务器上重新导入该批数据，而不是在别的服务器上重新调用注册

**Comment by jixuan1989** [comment]
目前版本，元数据可以方便地拷贝和加载。 将data/system/schema/mlog.txt （可以先压缩下节省空间）拷贝出来放到一个新iotdb实例的对应目录下，重启即可。

**Comment by qiaojialin** [comment]
Hi, metadata can be easily copied and load. Just copying the data/system/schema/mlog.txt into this folder in another IoTDB and restarting is ok.

**Comment by juice411** [comment]
拷贝是所有吧，只需指定存储组的元数据呢？

**Comment by juice411** [comment]
拷贝过去在删除？

**Comment by qiaojialin** [comment]
对，拷过去再删除其他存储组。。 之后可以加一个导入导出元数据的语句
