### ISSUE TITLE
TsFile文件只能读和写吗？能追加和修改吗？(Does TsFile only support Read and Write a New One? Can I append data to the file or modify the data in the File?)

### ISSUE THREAD

**Issue by scyqf** [apache/iotdb#1274]
TsFile文件只能读和写吗？能基于已有的TsFile文件实现追加和修改吗？

**Comment by jixuan1989** [comment]
> Can I append data to the file ?

可以，可以使用`RestorableTsFileIOWriter` 实现追加写；
Yes, you can use `RestorableTsFileIOWriter` to append data to an existed TsFile.

> Can I modify data in a  TsFile?

不行， TsFile不能做数据修改，这种情况下要么使用IoTDB，要么自己组织多个TsFile并用后者替代前者的数据。
No, you can not modify data in a TsFile. If you need to modify data, use IoTDB interface, or you can manage several TsFiles and use the latter version to cover the previous versions.

**Comment by qiaojialin** [comment]
You can try this:

ForceAppendTsFileWriter tsFileIOWriter = new ForceAppendTsFileWriter(f);
TsFileWriter tsFileWriter = new TsFileWriter(tsFileIOWriter);

No need to register schema again, then you can append data into it and close. (only append data in time ascending order)

TsFile does not support modify.

**Comment by jixuan1989** [comment]
`ForceAppendTsFileWriter` also works if your TsFile is complete.

**Comment by qiaojialin** [comment]
Here is an example to append data to a TsFile.

https://github.com/apache/incubator-iotdb/blob/master/example/tsfile/src/main/java/org/apache/iotdb/tsfile/TsFileForceAppendWrite.java
