### ISSUE TITLE
你好,请问现在iotdb的时间是精确到毫秒级吗 (What is the time precision unit of IoTDB? Can it be changed?)

### ISSUE THREAD

**Issue by liwh1111** [apache/iotdb#1276]
![image](https://user-images.githubusercontent.com/63097736/83000903-91ee8a80-a03d-11ea-9717-42fd57d225de.png)

你好, 我在测试时发现, 循环插入10000条数据, 时间用now(), 会丢很多数据, 查询数据库发现time在每毫秒都有数据,  一毫秒之内的其他数据好像都被覆盖了, 还能再往下精确吗? 如果可以, 该怎样操作呢.

**Comment by jixuan1989** [comment]
IoTDB默认使用毫秒， 但是其实IoTDB内部是用的long进行存储的，因此可以通过配置来支持微秒和纳秒。
在IoTDB配置文件(iotdb-engine.properties)中的如下配置:
```
# Use this value to set timestamp precision as "ms", "us" or "ns".
# Once the precision is been set, it can not be changed.
timestamp_precision=ms
```
这样的话，你传入一个long时间戳，就会将其按照微秒或者纳秒解读了。
不过目前的版本中 `now()`返回的是毫秒值， 所以如果将`timestamp_precision`设置为`us`或者`ns`，那么时间将来解析成人类可读的时间(yyyy-mm-dd HH:MM:ss)就会不太对。 这个会马上加PR修复。

By default, IoTDB considers a long timestamp as millisecond time unit, but you can change it in iotdb-engine.properties: `timestamp_precision=us` or `timestamp_precision=ns`.

But currently, `now()` function only returns `ms`.

**Comment by jixuan1989** [comment]
#1290 会解决这个问题，并在0.10中发布。

**Comment by yinlenc** [comment]
目前在0.11.2版本的配置文件中，timestamp_precision任然只能设置成ms，设置成us就无法启动。 我目前在做技术研制，参数的采样周期是1KHz以上，请问，如何解决？

**Comment by OrdinarySK** [comment]
请问这个问题解决了嘛，我在v0.12版本中更改配置为ns，但是启动服务会报错 提示改成ms

**Comment by jixuan1989** [comment]
是在全新系统中吗？
iotdb不允许在启动之后再重设时间戳精度。

OrdinarySK ***@***.***> 于2021年7月10日周六 下午2:18写道：
