### ISSUE TITLE
1.3.1版本能否提供一个arm64架构的docker镜像版本？

### ISSUE THREAD

**Issue by FlickerMi** [apache/iotdb#12769]
目前docker hub只有amd64版本

**Comment by FlickerMi** [comment]
这里提供了构建arm64 docker镜像版本方法：https://notemi.cn/docker-build---x86_64-architecture-how-to-build-an-image-of-arm64-architecture.html

**Comment by HTHou** [comment]
1.3.2 已发布到dockerhub，这次同时发布了arm版本
