### ISSUE TITLE
不存在时间序列的情况下，直接插入数据，为什么插入的整数类型会默认加上小数点

### ISSUE THREAD

**Issue by lxb9764** [apache/iotdb#13117]
![0452832897fd27138cccf9c720224401](https://github.com/user-attachments/assets/398e406d-178f-42d2-8703-18ed0a3354dc)
版本1.3.1或1.3.2

**Comment by lxb9764** [comment]
如何修改默认行为？让本是整数类型的用int32/64

**Comment by HTHou** [comment]
https://iotdb.apache.org/zh/UserGuide/latest/Reference/Common-Config-Manual.html#%E7%B3%BB%E7%BB%9F%E9%85%8D%E7%BD%AE%E9%A1%B9

integer_string_infer_type

**Comment by lxb9764** [comment]
可行
