### ISSUE TITLE
iotdb里面的time无法取别名

### ISSUE THREAD

**Issue by lxb9764** [apache/iotdb#13133]
![image](https://github.com/user-attachments/assets/ad188fd8-12a4-480b-b275-faaafddad9bc)
insert into root.iot_log.d2.d3(timestamp, s1, s2) values(1723098324072,3,3)
![image](https://github.com/user-attachments/assets/280e3e13-b10e-41bd-b623-b337e94b3b63)

**Comment by Beyyes** [comment]
在当前版本中Time会默认显示，不支持对time列取别名。

即将发布的下一个版本中对Time/属性等工作做了积极的探索，欢迎到时体验新版本。
