### ISSUE TITLE
mqtt开启

### ISSUE THREAD

**Issue by LikemeXY** [apache/iotdb#13159]
在使用docker部署的集群版本中，confignNode和dataNode中的iotdb-common配置都存在mqtt配置，此时需要开启哪个节点的mqtt配置,还是说只需要开一个dataNode的mqtt即可，目前是2C2D的，iotdb的版本是1.3.2，目前只开启了一个configNode的mqtt配置
![image](https://github.com/user-attachments/assets/44055126-889b-47d6-9c06-bbf89ab4ef6a)
![image](https://github.com/user-attachments/assets/6614c303-fb3e-4b8f-b660-4945531724dd)

**Comment by HTHou** [comment]
开启datanode上的配置就行，confignode上的配置项不生效。

**Comment by LikemeXY** [comment]
> 打开datanode上的配置项就行，confignode上的该配置项不生效。

集群中的所有datanode都需要开启吗

**Comment by HTHou** [comment]
如果只链接一个datanode，可以只开启一个datanode的
