### ISSUE TITLE
C#集群的连接问题

### ISSUE THREAD

**Issue by LikemeXY** [apache/iotdb#13198]
SessionPool在C#中是否支持集群连接？怎么连接？

**Comment by HTHou** [comment]
@lausannel @CritasWang

**Comment by CritasWang** [comment]
参考 https://github.com/apache/iotdb-client-csharp/pull/8/files

**Comment by LikemeXY** [comment]
> 参考 https://github.com/apache/iotdb-client-csharp/pull/8/files SessionPool 中更新了 构造函数，支持传递 nodeUrls public SessionPool(List nodeUrls, string username, string password, int fetchSize)

好的
