### ISSUE TITLE
分页和模糊查询是否支持 (whether supporting paging and fuzzy query ("like" keyword))

### ISSUE THREAD

**Issue by dongbin86** [apache/iotdb#1372]
问几个问题哈：
1、支持分页吗？
看sql文档似乎支持offset和limit，应该是可以支持分页吧

2、字符串的正则匹配或者模糊查询
看文档好像没有like这种语句，支持的话能给个例子吗

3、有没有读写benchmark的报告，想了解下具体的性能表现

**Comment by jixuan1989** [comment]
1. Support paging. 
you can define the fetch_size for query (avoid to use offset.. it is not efficient)
支持分页，在查询时设置fetch_size就行。

另外，offset虽然能用于从第n行返回，但是性能并不是没有损耗的。

2. Not support "like" query for string values now.
目前不支持对字符串值做模糊匹配。

3. Please read this doc before the doc is published on the website: https://github.com/apache/incubator-iotdb/pull/1189 
这个文档中包含了性能对比，在合并到官网前，可以看这个PR.

**Comment by dongbin86** [comment]
@jixuan1989 感谢回复，like这种语义是否有支持计划？

**Comment by jixuan1989** [comment]
Currently we have no plan to support "like" query for string, as there is no high-efficient way to implement that.. 
If we do not want to scan data point by point, we have to use index.  
We are developing an index framework to let users implement their desired index themselves.

暂时没有计划支持模糊查询。。。 （主要是不建立索引，只能暴力检索，性能并不好。如果要建立索引的话，我们近期会提供出索引框架，希望用户能自己去扩展自己需要的索引）。

**Comment by HTHou** [comment]
Like is supported.
