### ISSUE TITLE
client-py存在问题 (Client-py example error and compile iotdb-server failed)

### ISSUE THREAD

**Issue by ppyu** [apache/iotdb#1386]
利用python连接iotdb存在问题，利用 `pip install apache-iotdb`下载下来的与你们给出的demo版本不一致，缺失很多类。 
通过手动编译最新代码并加入项目测试也存在如下图所示的问题。
![image](https://user-images.githubusercontent.com/32732750/85000060-7ed66280-b184-11ea-9005-c9ff4121dae3.png)

**Comment by jixuan1989** [comment]
Hi, current `pip install apche-iotdb` only support 0.9.x, so you can not use it to connect to iotdb 0.10.x and the master branch.

By the way, the python client example codes in current master branch has a bug, and I will fix it quickly. 

Many thanks for reporting that.

**Comment by jixuan1989** [comment]
Now v0.10 is published, you can use `pip3 install apache-iotdb` to get the new one. and the corresponding example version is at https://github.com/apache/incubator-iotdb/blob/rel/0.10/client-py/src/client_example.py

**Comment by ppyu** [comment]
您好，已下载最新发布的，但我在centos7上运行 mvn clean package -pl server -am -Dmaven.test.skip=true 编译时出错。
如下两图








顺便问一下，现在只编译server其它的也要一起被编译了吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiangdong Huang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月1日(星期三) 下午4:17
收件人:&nbsp;"apache/incubator-iotdb"<incubator-iotdb@noreply.github.com&gt;;
抄送:&nbsp;"可以扣篮但没必要"<971106266@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-iotdb] client-py存在问题 (#1386)





 
Now v0.10 is published, you can use pip3 install apache-iotdb to get the new one. and the corresponding example version is at https://github.com/apache/incubator-iotdb/blob/rel/0.10/client-py/src/client_example.py

**Comment by jixuan1989** [comment]
图没有上传。。。 
`mvn clean package -pl server -am -DskipTests` 试试？避免使用`-Dmaven.test.skip=true`

**Comment by ppyu** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiangdong Huang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月1日(星期三) 晚上9:04
收件人:&nbsp;"apache/incubator-iotdb"<incubator-iotdb@noreply.github.com&gt;;
抄送:&nbsp;"可以扣篮但没必要"<971106266@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-iotdb] client-py存在问题 (#1386)





 
图没有上传。。。
 mvn clean package -pl server -am -DskipTests 试试？避免使用-Dmaven.test.skip=true

**Comment by jixuan1989** [comment]
the following issue is resolved in #1449 

> 您好，已下载最新发布的，但我在centos7上运行 mvn clean package -pl server -am -Dmaven.test.skip=true 编译时出错。 如下两图 顺便问一下，现在只编译server其它的也要一起被编译了吗？

**Comment by cjf411** [comment]
目前安装python版本处于不可用状态，自己安装pip install apache-iotdb，运行SessionExample.py会提示IOTDB_SERVICE_PROTOCOL_V3找不到。如果自己编译的话，运行SessionExample.py，会卡在session.open(False)卡死。

**Comment by umaker** [comment]
> 目前安装python版本处于不可用状态，自己安装pip install apache-iotdb，运行SessionExample.py会提示IOTDB_SERVICE_PROTOCOL_V3找不到。如果自己编译的话，运行SessionExample.py，会卡在session.open(False)卡死。

python的apache-iotdb采用最新的0.11.1，数据库也用0.11.1，目前可以跑通
