### ISSUE TITLE
[Feature request] [Python] Allow for sqlalchemy versions greater tha 2.0

### ISSUE THREAD

**Issue by MarcBresson** [apache/iotdb#13991]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Motivation

New major version of sqlalchemy did not introduce any major breaking change and the python code here is probably already compatible. As a matter of fact, we are using sqlalchemy 2.0.27 with an older version of apache-iotdb that did not set such a hard condition on the requirements.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by CritasWang** [comment]
Welcome submit a PR

**Comment by CritasWang** [comment]
CI failed and is incompatible in some scenarios

**Comment by MarcBresson** [comment]
Hello @CritasWang my bad, tests were outdated compared to the examples given in the readme. Now tests should run just fine

**Comment by CritasWang** [comment]
> Hello @CritasWang my bad, tests were outdated compared to the examples given in the readme. Now tests should run just fine

https://github.com/apache/iotdb/actions/runs/11910341559/job/33262355435?pr=14083
https://github.com/apache/iotdb/actions/runs/11910341559/job/33262354350?pr=14083

There are still some issues that require further modifications
