### ISSUE TITLE
[Bug] Dependency redundancy occurs

### ISSUE THREAD

**Issue by nanoori** [apache/iotdb#14122]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

iotdb-session: 1.3.2 
java: 21
os: mac 14.1.1

### Describe the bug and provide the minimal reproduce step

I'm testing the java native api by referring to the example below, but the build itself fails. If there's anything I'm doing wrong, please give me a tip or guide

https://github.com/apache/iotdb/blob/master/example/session/src/main/java/org/apache/iotdb/SyntaxConventionRelatedExample.java

- pom.xml

```
        <dependency>
            <groupId>org.apache.iotdb</groupId>
            <artifactId>iotdb-session</artifactId>
            <version>1.3.2</version>
        </dependency>

        <dependency>
            <groupId>org.apache.iotdb</groupId>
            <artifactId>node-commons</artifactId>
            <version>1.3.2</version>
        </dependency>
```
- module-info.class
```	
requires iotdb.session;
requires isession;
requires service.rpc;
requires tsfile;
requires common.api;
```
- session config

```
@Configuration
public class IoTDBConfig {

	@Value("${iotdb.host}")
	private String host;

	@Value("${iotdb.port}")
	private int port;

	@Value("${iotdb.username}")
	private String username;

	@Value("${iotdb.password}")
	private String password;

	@Bean
	public Session session() {
		Session session = new Session(host, port, username, password);
		try {
			session.open();
		} catch (Exception e) {
			throw new IllegalStateException("Failed to open IoTDB session", e);
		}
		return session;
	}
}
```

- using session and print

```
paths.forEach(path -> {
			String sql = String.format("SELECT last_value(*) FROM %s", path);
			log.info("Executing query: {}", sql);

			try {
				SessionDataSet dataSet = session.executeQueryStatement(sql);
				while (dataSet.hasNext()) {
					log.info("data = {}", dataSet.next());

				}
			} catch (StatementExecutionException e) {
				throw new RuntimeException(e);
			} catch (IoTDBConnectionException e) {
				throw new RuntimeException(e);
			}
		});
```

- build fail message
```
java: module com.zaxxer.hikari reads package org.apache.iotdb.tsfile.utils from both common.api and tsfile
java: module com.zaxxer.hikari reads package org.apache.iotdb.tsfile.read.common.block from both common.api and tsfile
java: module com.zaxxer.hikari reads package org.apache.iotdb.tsfile.read.common.block.column from both common.api and tsfile
java: module com.zaxxer.hikari reads package org.apache.iotdb.tsfile.file.metadata.enums from both common.api and tsfile
java: module com.zaxxer.hikari reads package org.apache.iotdb.tsfile.exception.write from both common.api and tsfile
java: the unnamed module reads package org.apache.iotdb.tsfile.utils from both common.api and tsfile

... 
```

### What did you expect to see?

build and run success 

### What did you see instead?

java: module com.zaxxer.hikari reads package org.apache.iotdb.tsfile.utils from both common.api and tsfile
java: module com.zaxxer.hikari reads package org.apache.iotdb.tsfile.read.common.block from both common.api and tsfile
java: module com.zaxxer.hikari reads package org.apache.iotdb.tsfile.read.common.block.column from both common.api and tsfile
java: module com.zaxxer.hikari reads package org.apache.iotdb.tsfile.file.metadata.enums from both common.api and tsfile
java: module com.zaxxer.hikari reads package org.apache.iotdb.tsfile.exception.write from both common.api and tsfile
java: the unnamed module reads package org.apache.iotdb.tsfile.utils from both common.api and tsfile

.... 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by CritasWang** [comment]
Can you provide the complete code package

**Comment by nanoori** [comment]
Sorry, i can't provide my code package.

**Comment by CritasWang** [comment]
Try changing the `module-info`

**Comment by nanoori** [comment]
i change my code and fix this error. thanks
