### ISSUE TITLE
datanode为只读状态，怎么解决呢

### ISSUE THREAD

**Issue by YWzzq** [apache/iotdb#14286]
占用的磁盘是98%，但是我还剩下56g，整个磁盘是1.8t。![image](https://github.com/user-attachments/assets/ecc3210b-ecf3-4fb0-9ed0-da77dd3feb36)

**Comment by CritasWang** [comment]
阈值为 5%

# Disk remaining threshold at which DataNode is set to ReadOnly status
# effectiveMode: restart
# Datatype: double(percentage)
disk_space_warning_threshold=0.05
