### ISSUE TITLE
LIMIT子句与GROUP BY子句组合 0.10.0版本中无效 (can not use "limit" and "group by" together)

### ISSUE THREAD

**Issue by zhangJiangKai** [apache/iotdb#1505]
**Describe the bug**
0.10.0版本中 样例数据测试 
select count(status), max_value(temperature) from root.ln.wf01.wt01 group by ([2017-11-01T00:00:00, 2017-11-07T23:00:00),1d) limit 5 offset 3
和
select count(status), max_value(temperature) from root.ln.wf01.wt01 group by ([2017-11-01T00:00:00, 2017-11-07T23:00:00),1d) 
结果一致

**Expected behavior**
文档结果为
![image](https://user-images.githubusercontent.com/33944793/87640740-bfbc9980-c779-11ea-8c94-51cb63ebb3f4.png)

**Screenshots**
实际结果

![image](https://user-images.githubusercontent.com/33944793/87640817-df53c200-c779-11ea-8e1f-1d7906c5b66a.png)

**Desktop (please complete the following information):**
 - Linux 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 -  /iotdb/sbin/start-cli.sh
 - Version 0.10.0

**Additional context**

**Comment by qiaojialin** [comment]
Thanks for your feedback! This if fixed in rel/0.10 and master branch, please have a check
