### ISSUE TITLE
执行删除组delete storage group root.xxx出错

### ISSUE THREAD

**Issue by beyondyinjl2** [apache/iotdb#1521]
**Describe the bug**
执行删除组命令delete storage group root.xxx出错,执行后,start-cli.sh会断开连接,再连接上去后,分组还存在,查询这个分组数据时,start-cli.sh又会断开,重启IOTDB服务后,再执行一次删除组命令delete storage group root.xxx,才删除成功
版本:0.9.3和0.10.0,数据量50条左右

**Comment by HTHou** [comment]
您好，能否提供一下执行了哪些sql语句和server端的相关错误日志？
Hi, can you please provide more information about this issue? Such as the sql statements you used and error logs on sever.

**Comment by qiaojialin** [comment]
cannot reproduction
