### ISSUE TITLE
导入外部TSFILE 问题 (bug when loading a manually generated TsFile into IoTDB instance)

### ISSUE THREAD

**Issue by xuanqisong** [apache/iotdb#1551]
通过example建立的tsfile文件
在导入的时候提示 411 
如下

IoTDB> load "D:\iotDb\testTsFile\1595501732489-1-0.tsfile"
Msg: 411: Cannot load file D:\iotDb\testTsFile\1595501732489-1-0.tsfile because null

但是查询此组，还可以能查询到数据

生成tsfile的Example里面不知道是不是有bug
19:00:38.302 [main] ERROR com.zichan360.local.TestTsFile - meet error in TsFileWrite with tablet
org.apache.iotdb.tsfile.exception.write.NoMeasurementException: input measurement is invalid: sensor_1
	at org.apache.iotdb.tsfile.write.TsFileWriter.checkIsTimeSeriesExist(TsFileWriter.java:232) ~[tsfile-0.10.0.jar:0.10.0]
	at org.apache.iotdb.tsfile.write.TsFileWriter.write(TsFileWriter.java:263) ~[tsfile-0.10.0.jar:0.10.0]
	at com.zichan360.local.TestTsFile.main(TestTsFile.java:72) [classes/:?]

原版代码如下
      List<MeasurementSchema> measurementSchemas = new ArrayList<>();
      // add measurements into file schema (all with INT64 data type)
      for (int i = 0; i < sensorNum; i++) {
        measurementSchemas.add(
            new MeasurementSchema("sensor_" + (i + 1), TSDataType.INT64, TSEncoding.TS_2DIFF));
      }

      // add measurements into TSFileWriter
      try (TsFileWriter tsFileWriter = new TsFileWriter(f, schema)) {

        // construct the tablet
        Tablet tablet = new Tablet("device_1", measurementSchemas);

我修改成
            List<MeasurementSchema> measurementSchemas = new ArrayList<>();
            // add measurements into file schema (all with INT64 data type)
            for (int i = 0; i < sensorNum; i++) {
                MeasurementSchema measurementSchema = new MeasurementSchema("sensor_" + (i + 1), TSDataType.INT64, TSEncoding.TS_2DIFF);
                measurementSchemas.add(measurementSchema);
                schema.registerTimeseries(new Path("root.device_1", measurementSchema.getMeasurementId()), measurementSchema);
            }

            // add measurements into TSFileWriter
            try (TsFileWriter tsFileWriter = new TsFileWriter(f, schema)) {

                // construct the tablet
                Tablet tablet = new Tablet("root.device_1", measurementSchemas);
可以执行了
而且example生成的tsfile不能直接导入到IOTDB里面，需要将
device_1 替换成 root.device_1才可以

**Comment by qiaojialin** [comment]
感谢反馈，这个example 是有bug，使用 load tsfile 功能时候，TsFile 的 device 命名需要符合 IoTDB 的 命名，root 开头

**Comment by xuanqisong** [comment]
> 感谢反馈，这个example 是有bug，使用 load tsfile 功能时候，TsFile 的 device 命名需要符合 IoTDB 的 命名，root 开头

是使用的root开头的，现在提示的是because null 但是我在查询的时候是能看到存储组里面有数据
我看日志操作是做了一次系统的mv操作，而且在show storage group能看到tsfile里面的存储组名称的

**Comment by qiaojialin** [comment]
哦，发现了，导入的时候最后有一个属性没初始化，抛了个空指针，这之前数据已经导入成功了，这个属性对单机没影响，我修一下

**Comment by xuanqisong** [comment]
> 哦，发现了，导入的时候最后有一个属性没初始化，抛了个空指针，这之前数据已经导入成功了，这个属性对单机没影响，我修一下

嗯我也刚看到这....
但是我有几次导入没有抛异常....很神奇，现在复现不出来了，我也再追一下源码调试一下

**Comment by qiaojialin** [comment]
solved
