### ISSUE TITLE
IoTDB是否支持集群

### ISSUE THREAD

**Issue by ATM006** [apache/iotdb#1568]
我如何配置iotdb使其支持集群部署和jdbc连接

**Comment by neuyilan** [comment]
cluster_new分支目前支持集群，org.apache.iotdb.cluster.ClientMain 类里面有一些使用的例子，你可以尝试下。

**Comment by zfqhd43** [comment]
请问集群模式现在稳定吗？ 有实际的项目场景在使用吗？

**Comment by HTHou** [comment]
目前已经有线上系统在使用了
