### ISSUE TITLE
使用 tsfile API 写tsfile文件时，修改TSFileConfig对象无效。

### ISSUE THREAD

**Issue by ppyu** [apache/iotdb#1574]
使用 tsfile API 写tsfile文件时，修改TSFileConfig对象无效。
日志中出现下列警告：
WARN org.apache.iotdb.tsfile.common.conf.TSFileDescriptor - Failed to find config file iotdb-engine.properties at classpath, use default configuration
似乎程序启动时就按默认配置运行了，配置类修改无效。

**Comment by jixuan1989** [comment]
确保iotdb-engine.properties 在classpath里 应该是可以的吧？

**Comment by ppyu** [comment]
我对Java不是很熟，意思是缺少iotdb-engine.properties文件吗？您能说详细点吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-iotdb"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月28日(星期二) 晚上7:47
收件人:&nbsp;"apache/incubator-iotdb"<incubator-iotdb@noreply.github.com&gt;;
抄送:&nbsp;"可以扣篮但没必要"<971106266@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-iotdb] 使用 tsfile API 写tsfile文件时，修改TSFileConfig对象无效。 (#1574)





 
确保iotdb-engine.properties 在classpath里 应该是可以的吧？

**Comment by qiaojialin** [comment]
在刚开始就通过 TsFileConfig 设置好，然后创建 writer 就可以了吧

![image](https://user-images.githubusercontent.com/7240743/89178186-a613b280-d5bf-11ea-8352-5094b38c02ee.png)
