### ISSUE TITLE
DataIterator中迭代器如何获取一条记录的所有时序名称

### ISSUE THREAD

**Issue by ATM006** [apache/iotdb#1593]
我遇到的问题：如何获取iterator.getLong(index)中index的最大值。因为我想用来遍历所有的时间序列名称。
![image](https://user-images.githubusercontent.com/24607498/89168792-f551e700-d5af-11ea-806c-3343a832243c.png)

**Comment by ATM006** [comment]
查看IoTDBRpcDataSet.java中columnSize属性是一个私有属性。

**Comment by qiaojialin** [comment]
SessionDataSet dataSet = session.executeQueryStatement("select * from root.sg1.d1");
System.out.println(dataSet.getColumnNames());

这个 getColumnNames 的 size 就是结果的表头
