### ISSUE TITLE
编码方式无法支持数据类型时,持久化失败 (If the encoding doesn't fit the data type, the data persistence will fail thus losing data)

### ISSUE THREAD

**Issue by zhangJiangKai** [apache/iotdb#1599]
**Describe the bug**
.
例如
GORILLA doesn't support data type: INT32

**To Reproduce**
1. 设置INT32编码方式为GORILLA
2. 插入多条数据
3. 重启服务
4. 数据丢失

**Comment by zhangJiangKai** [comment]
@qiaojialin

**Comment by qiaojialin** [comment]
感谢！0.9、0.10.0 版本，如果用 Session 的 createTimeseries 接口手动创建时间序列，需要保证数据类型和编码配套，不然数据持久化会失败。会在 0.10.1 版本修复。

数据类型和编码的匹配关系：

BOOLEAN : PLAIN, RLE(推荐)
INT32/INT64: PLAIN, RLE(推荐), TS2_DIFF
FLOAT/DOUBLE: PLAIN, GORILLA(推荐), RLE(有损, lossy)
TEXT: PLAIN

**Comment by jixuan1989** [comment]
fixed by PR #1600 and #1602
