### ISSUE TITLE
监控功能无法使用

### ISSUE THREAD

**Issue by wtk91** [apache/iotdb#1603]
使用版本：0.10.0release版本
操作步骤：在iotdb-engine.properties中将enable_stat_monitor设定成true后重启iotdb
想根据官方文档的方法查看相关数据统计监控值
但是使用类似如下语句没有得到结果
select TOTAL_POINTS from root.stats.write.global
看了下root.stats存储组底下只有file_size.WAL和file_size.SYS
如何才能让数据统计监控值的语句正常执行出结果？请指教

**Comment by qiaojialin** [comment]
我们已经安排人修复了，预计在 0.11 版本修好

**Comment by HTHou** [comment]
您好，监控功能0.11版本没有加上去，但是已经有PR https://github.com/apache/iotdb/pull/1725 修复监控而且合并进master分支了。0.12版本会支持。
