### ISSUE TITLE
iotdb0.10.0报错如何解决 (How to deal with OOM)

### ISSUE THREAD

**Issue by ATM006** [apache/iotdb#1718]
![image](https://user-images.githubusercontent.com/24607498/92677737-0cc28380-f357-11ea-9683-9c2765826cec.png)

**Comment by qiaojialin** [comment]
默认  enable_parameter_adapter 参数为 true，应该不会爆内存。如果这个设置为  false 了，需要根据负载调整其他参数。
The default value of enable_parameter_adapter is true, this could avoid OOM. If set this to false, you need to change other parameters accordingly.

https://www.slidestalk.com/IoTDB/IoTDBOps

![image](https://user-images.githubusercontent.com/7240743/92695623-4e652580-f37b-11ea-8a24-98c566982953.png)

如果调整之后还爆内存可以联系我，微信 qiaojialin1993
