### ISSUE TITLE
iotdb connectors  support c# 

### ISSUE THREAD

**Issue by geffzhang** [apache/iotdb#1742]
Microsoft releases Open source cross-platform .net core https://github.com/dotnet, Upcoming Release 5.0. As a popular language, c# has an advantage in cloud-native application development, Is there someone started to implement the c# connectors?

**Comment by jixuan1989** [comment]
Hi, as we are using Thrift as the RPC framework, I think it is possible.

**Comment by geffzhang** [comment]
I found the project https://github.com/core-bim/Apache.IotDB.NetCore

**Comment by HTHou** [comment]
Another project if anyone like to try.
https://github.com/eedalong/Apache-IoTDB-Client-CSharp
