### ISSUE TITLE
docker镜像iotdb：0.10.0运行占用cpu、内存异常

### ISSUE THREAD

**Issue by ATM006** [apache/iotdb#1744]
![image](https://user-images.githubusercontent.com/24607498/93716627-6fabea00-fba3-11ea-9578-f57a10d9c01e.png)

[root@hdp57 ~]# ps auxw|head -1;ps auxw|sort -rn -k3|head -10
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      3089  183 27.4 12605160 6741924 ?    Ssl  Sep20 1054:15 /usr/local/openjdk-11/bin/java -Dlogback.configurationFile=/iotdb/sbin/../conf/logback.xml -DIOTDB_HOME=/iotdb/sbin/.. -DTSFILE_HOME=/iotdb/sbin/.. -DIOTDB_CONF=/iotdb/sbin/../conf -DTSFILE_CONF=/iotdb/sbin/../conf -Dname=iotdb\.IoTDB -Xms1200M -Xmx5986M -Dlogback.configurationFile=/iotdb/sbin/../conf/logback.xml -DIOTDB_HOME=/iotdb/sbin/.. -DTSFILE_HOME=/iotdb/sbin/.. -DIOTDB_CONF=/iotdb/sbin/../conf -DTSFILE_CONF=/iotdb/sbin/../conf -Dname=iotdb\.IoTDB -cp :/iotdb/sbin/../lib/FastInfoset-1.2.16.jar:/iotdb/sbin/../lib/HikariCP-2.4.7.jar:/iotdb/sbin/../lib/accessors-smart-1.2.jar:/iotdb/sbin/../lib/airline-0.8.jar:/iotdb/sbin/../lib/antlr4-runtime-4.8-1.jar:/iotdb/sbin/../lib/asm-5.0.4.jar:/iotdb/sbin/../lib/bugsnag-3.6.1.jar:/iotdb/sbin/../lib/commons-cli-1.3.1.jar:/iotdb/sbin/../lib/commons-codec-1.13.jar:/iotdb/sbin/../lib/commons-collections4-4.0.jar:/iotdb/sbin/../lib/commons-io-2.5.jar:/iotdb/sbin/../lib/commons-lang-2.6.jar:/iotdb/sbin/../lib/commons-lang3-3.8.1.jar:/iotdb/sbin/../lib/content-type-2.0.jar:/iotdb/sbin/../lib/fastjson-1.2.70.jar:/iotdb/sbin/../lib/fastutil-7.0.6.jar:/iotdb/sbin/../lib/guava-21.0.jar:/iotdb/sbin/../lib/h2-mvstore-1.4.199.jar:/iotdb/sbin/../lib/iotdb-cli-0.10.0.jar:/iotdb/sbin/../lib/iotdb-jdbc-0.10.0.jar:/iotdb/sbin/../lib/iotdb-server-0.10.0.jar:/iotdb/sbin/../lib/istack-commons-runtime-3.0.8.jar:/iotdb/sbin/../lib/jackson-annotations-2.10.0.jar:/iotdb/sbin/../lib/jackson-core-2.10.0.jar:/iotdb/sbin/../lib/jackson-databind-2.10.0.jar:/iotdb/sbin/../lib/javax.activation-api-1.2.0.jar:/iotdb/sbin/../lib/javax.annotation-api-1.3.2.jar:/iotdb/sbin/../lib/javax.inject-1.jar:/iotdb/sbin/../lib/javax.servlet-api-3.1.0.jar:/iotdb/sbin/../lib/jaxb-api-2.4.0-b180725.0427.jar:/iotdb/sbin/../lib/jaxb-runtime-2.4.0-b180725.0644.jar:/iotdb/sbin/../lib/jcip-annotations-1.0-1.jar:/iotdb/sbin/../lib/jcl-over-slf4j-1.7.25.jar:/iotdb/sbin/../lib/jetty-http-9.4.24.v20191120.jar:/iotdb/sbin/../lib/jetty-io-9.4.24.v20191120.jar:/iotdb/sbin/../lib/jetty-security-9.4.24.v20191120.jar:/iotdb/sbin/../lib/jetty-server-9.4.24.v20191120.jar:/iotdb/sbin/../lib/jetty-servlet-9.4.24.v20191120.jar:/iotdb/sbin/../lib/jetty-util-9.4.24.v20191120.jar:/iotdb/sbin/../lib/jetty-webapp-9.4.24.v20191120.jar:/iotdb/sbin/../lib/jetty-xml-9.4.24.v20191120.jar:/iotdb/sbin/../lib/jfreechart-1.5.0.jar:/iotdb/sbin/../lib/jjwt-api-0.10.7.jar:/iotdb/sbin/../lib/jjwt-impl-0.10.7.jar:/iotdb/sbin/../lib/jjwt-jackson-0.10.7.jar:/iotdb/sbin/../lib/jline-2.14.5.jar:/iotdb/sbin/../lib/jline-3.10.0.jar:/iotdb/sbin/../lib/json-smart-2.3.jar:/iotdb/sbin/../lib/jsr305-3.0.2.jar:/iotdb/sbin/../lib/lang-tag-1.4.4.jar:/iotdb/sbin/../lib/librato-java-2.1.0.jar:/iotdb/sbin/../lib/libthrift-0.13.0.jar:/iotdb/sbin/../lib/log4j-1.2.17.jar:/iotdb/sbin/../lib/logback-classic-1.1.11.jar:/iotdb/sbin/../lib/logback-core-1.1.11.jar:/iotdb/sbin/../lib/metrics-core-3.2.6.jar:/iotdb/sbin/../lib/metrics-json-3.2.6.jar:/iotdb/sbin/../lib/metrics-jvm-3.2.6.jar:/iotdb/sbin/../lib/metrics-librato-5.1.0.jar:/iotdb/sbin/../lib/moquette-broker-0.13.jar:/iotdb/sbin/../lib/netty-buffer-4.1.22.Final.jar:/iotdb/sbin/../lib/netty-codec-4.1.22.Final.jar:/iotdb/sbin/../lib/netty-codec-http-4.1.22.Final.jar:/iotdb/sbin/../lib/netty-codec-mqtt-4.1.22.Final.jar:/iotdb/sbin/../lib/netty-common-4.1.22.Final.jar:/iotdb/sbin/../lib/netty-handler-4.1.22.Final.jar:/iotdb/sbin/../lib/netty-resolver-4.1.22.Final.jar:/iotdb/sbin/../lib/netty-transport-4.1.22.Final.jar:/iotdb/sbin/../lib/netty-transport-native-epoll-4.1.22.Final-linux-x86_64.jar:/iotdb/sbin/../lib/netty-transport-native-unix-common-4.1.22.Final.jar:/iotdb/sbin/../lib/nimbus-jose-jwt-8.14.1.jar:/iotdb/sbin/../lib/oauth2-oidc-sdk-8.3.jar:/iotdb/sbin/../lib/org.osgi.core-6.0.0.jar:/iotdb/sbin/../lib/osgi.cmpn-6.0.0.jar:/iotdb/sbin/../lib/pax-jdbc-common-1.4.5.jar:/iotdb/sbin/../lib/progressbar-0.7.3.jar:/iotdb/sbin/../lib/service-rpc-0.10.0.jar:/iotdb/sbin/../lib/slf4j-api-1.7.25.jar:/iotdb/sbin/../lib/slf4j-log4j12-1.7.25.jar:/iotdb/sbin/../lib/snappy-java-1.1.7.2.jar:/iotdb/sbin/../lib/stax-ex-1.8.jar:/iotdb/sbin/../lib/stream-2.9.5.jar:/iotdb/sbin/../lib/tsfile-0.10.0.jar:/iotdb/sbin/../lib/txw2-2.4.0-b180725.0644.jar org.apache.iotdb.db.service.IoTDB

**Comment by ATM006** [comment]
![image](https://user-images.githubusercontent.com/24607498/93716680-c44f6500-fba3-11ea-8df8-0d0f7c8627ce.png)

**Comment by jixuan1989** [comment]
can you explain more about why you think of it in abnormal status?
可以详细描述希望是什么样的？

**Comment by qiaojialin** [comment]
您好，cpu 占用高是有一些问题，会在0.11 修掉

**Comment by qiaojialin** [comment]
cpu占用高已经在 master 分支修复了，0.11.0-SNAPSHOT，内存可以在 iotdb-env.sh 里手动配置，默认是机器1/4内存
