### ISSUE TITLE
Time or Timestamp should not be required as the first column in insert SQL statement

### ISSUE THREAD

**Issue by jiazhili-dawnlight** [apache/iotdb#1759]
support
```
insert into root.test2.wf01.wt0 (time,json ,`status` ) values (111,"abcddf" ,true  )
```
but not support
```
insert into root.test2.wf01.wt01 (json ,`status`,time ) values ("abcddf" ,true,111  )
```
get error msg

Msg: 401: line 1:34 mismatched input 'json' expecting {'.', '('}

**Comment by jixuan1989** [comment]
hi, yes, we require the first column as `time` in an `insert` SQL...
Any strong requirements for changing the position?

**Comment by jiazhili-dawnlight** [comment]
I am developing an [ORM tool ](https://gitee.com/xiandafu/beetlsql/blob/3.0/README3.md). If the `time` must be in the first column, many popular ORM tools (hiberante,jpa,Spring Data)will not be able to integrate iotdb.

**Comment by jixuan1989** [comment]
yes, I think we can modify our Antlr parser to support that. 
By the way, are you familiar with antlr4? I believe it is not a big modification.

**Comment by jiazhili-dawnlight** [comment]
i familiar with antlr4 ....

**Comment by rhmangmang** [comment]
> hi, yes, we require the first column as `time` in an `insert` SQL...
> Any strong requirements for changing the position?

this situation occurs again in release 0.11.0, should we write this description in the UserGuide?

**Comment by HTHou** [comment]
Fixed by this PR.
- https://github.com/apache/iotdb/pull/3614

**Comment by gofow** [comment]
Hi, I'd like to do this by modifying the 'insertColumnsSpec' in 'IoTDBSqlParser'. Would you mind assign the issue to me? @qiaojialin @HTHou @jixuan1989

**Comment by HTHou** [comment]
Fixed by https://github.com/apache/iotdb/pull/12074
