### ISSUE TITLE
JDBC ResultSet .wasNull

### ISSUE THREAD

**Issue by jiazhili-dawnlight** [apache/iotdb#1760]
wasNull  was called By Java ORM Framework ，but not support  version `0.10.0`  .

Just call IoTDBRpcDataSet.isNull  in method ResultSet.WasNull ?

**Comment by jixuan1989** [comment]
we have created an issue for this method. Will update  the progress when finished.
https://issues.apache.org/jira/browse/IOTDB-912

**Comment by HTHou** [comment]
This issue has be fixed by PR  https://github.com/apache/iotdb/pull/1791, please check it. The next release version will support the method.
