### ISSUE TITLE
select count(*)

### ISSUE THREAD

**Issue by jiazhili-dawnlight** [apache/iotdb#1761]
for the mysql , return one  column, but iotdb return multiple column, like this

select count(*) from root.test2.wf01.wt01;
```
+----------------------------------+--------------------------------+
|count(root.test2.wf01.wt01.status)|count(root.test2.wf01.wt01.json)|
+----------------------------------+--------------------------------+
|                                 3|                               3|
+----------------------------------+--------------------------------+
```

**Comment by jixuan1989** [comment]
Hi, see `Count points group by level`.

http://iotdb.apache.org/UserGuide/Master/Operation%20Manual/DML%20Data%20Manipulation%20Language.html#count-points-by-level

But it only supports `count()` function now.
