### ISSUE TITLE
Small recommendation in IoTDBConnection

### ISSUE THREAD

**Issue by tieredblocks** [apache/iotdb#1804]
_Its not a bug but a suggestion._ 

In **[IoTDBConnection](https://github.com/apache/iotdb/blob/master/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java)** java file, can we make following changes to the code:

- Replace **throw new SQLException("Not support .......")** to **throw new SQLException("Does not support .......")** or **throw new SQLException("No support for .......")** in the applicable methods

**Comment by qiaojialin** [comment]
Hi, thank you, it is fine. Would you like to fix this?

**Comment by tieredblocks** [comment]
Sure, will do this and upload the forked code

**Comment by jixuan1989** [comment]
PR https://github.com/apache/iotdb/pull/2278 

The PR needs to be maintained.
