### ISSUE TITLE
在调用DataIterator的getInt（columnName）方法时出现了数组下标越界的错误

### ISSUE THREAD

**Issue by try-anything** [apache/iotdb#1839]
**Describe the bug**
java.lang.ArrayIndexOutOfBoundsException: 3
 at org.apache.iotdb.tsfile.utils.BytesUtils.bytesToInt(BytesUtils.java:138) ~[tsfile-0.10.1.jar:0.10.1]
 at org.apache.iotdb.rpc.IoTDBRpcDataSet.getInt(IoTDBRpcDataSet.java:328) ~[service-rpc-0.10.1.jar:0.10.1]
 at org.apache.iotdb.session.SessionDataSet$DataIterator.getInt(SessionDataSet.java:197) ~[iotdb-session-0.10.1.jar:0.10.1]

**To Reproduce**
在调用DataIterator的getInt（columnName）方法时出现了数组下标越界的错误，换成getString可以获取正确的string类型结果

**Comment by EJTTianYu** [comment]
You may need to provide a reproducing solution or related codes. This case I can not understand of reproduce the problem

**Comment by try-anything** [comment]
1.create a timeseries datatype INT32 
2.use sessionpool connnect iotdbserver
3.codes like bottom
SessionDataSetWrapper wrapper = SessionPool.executeQueryStatement();
DataIterator dataIterator = wrapper.iterator();
int sum = 0;
while (dataIterator.next()) {
int sum+= dataIterator.getInt(ColumnName);
}
ps: when i use getString(ColumnName) can get a String value ,but using getInt will get exception

**Comment by JackieTien97** [comment]
> 1.create a timeseries datatype INT32
> 2.use sessionpool connnect iotdbserver
> 3.codes like bottom
> SessionDataSetWrapper wrapper = SessionPool.executeQueryStatement();
> DataIterator dataIterator = wrapper.iterator();
> int sum = 0;
> while (dataIterator.next()) {
> int sum+= dataIterator.getInt(ColumnName);
> }
> ps: when i use getString(ColumnName) can get a String value ,but using getInt will get exception

value列的类型应该就是string，因为如果select last包含多个时间序列，这多个时间序列的类型都不一样，但是他们的值都需要放在value这一列，所以value列的类型只能是string了。
