### ISSUE TITLE
降频聚合分析select count('iotDB关键字') align by device后结果集出现问题

### ISSUE THREAD

**Issue by try-anything** [apache/iotdb#1843]
当我使用降频聚合分析时，由于测点采用的level是iotDB的关键字，我将level用单引号括入进行查询。当使用align by device后出现了问题。下面的截图可以看到align by device查询的问题结果集
![image](https://user-images.githubusercontent.com/70941797/96815371-a64d7c80-144f-11eb-95fc-a459739be2ef.png)
![image](https://user-images.githubusercontent.com/70941797/96815489-aea5b780-144f-11eb-8084-dd0b39cdfdac.png)

**Comment by Alima777** [comment]
Hi,

由于**非 Align by device 查询**不支持在结果集中显示常量列，所以用单引号包裹查询没有问题。但是 Align by device 为了支持更加类似关系表结构的输出方式，是支持常量列的，即**将单引号包裹的字符串作为常量而非测点进行输出**，所以您给出的查询结果是符合预期的。

![image](https://user-images.githubusercontent.com/34242296/97148152-9a422180-17a5-11eb-8510-cfc4eb832d9e.png)

我这边直接使用 level 查询是没问题的，您可以尝试把单引号去掉查询。
