### ISSUE TITLE
SQL Arithmetic Operators

### ISSUE THREAD

**Issue by thart-hnrg** [apache/iotdb#1855]
SQL queries should support SQL arithmetic operators.

Currently 
If I run a query such as "select m1+m2 from XYZ.myseries" I get no results.

If I run a query such as "select m3 from XYZ.myseries where mt+ma > 10" I get an exception;
org.apache.iotdb.jdbc.IoTDBSQLException: 401: Filter has some time series don't correspond to any known time series

If I put the arithmetic in bvrckets I get this exception;
org.apache.iotdb.jdbc.IoTDBSQLException: 401: meet error while parsing SQL to physical plan: {}line 3:12 no viable alternative at input 'ma+mt)'

The query should process arithmetic operators.

I am using measurements to send alarms when thresholds are exceeded. Some threshholds are percentages but measurements are stored as true values so I need to calculate a percentage (this is just one example).

**Comment by qiaojialin** [comment]
Hi, thanks for your advise 👍   I have created an issue in the jira. We will support this in the future.

**Comment by SteveYurongSu** [comment]
> SQL queries should support SQL arithmetic operators.
> 
> Currently
> If I run a query such as "select m1+m2 from XYZ.myseries" I get no results.
> 
> If I run a query such as "select m3 from XYZ.myseries where mt+ma > 10" I get an exception;
> org.apache.iotdb.jdbc.IoTDBSQLException: 401: Filter has some time series don't correspond to any known time series
> 
> If I put the arithmetic in bvrckets I get this exception;
> org.apache.iotdb.jdbc.IoTDBSQLException: 401: meet error while parsing SQL to physical plan: {}line 3:12 no viable alternative at input 'ma+mt)'
> 
> The query should process arithmetic operators.
> 
> I am using measurements to send alarms when thresholds are exceeded. Some threshholds are percentages but measurements are stored as true values so I need to calculate a percentage (this is just one example).

Hi, I wrote a requirement doc for arithmetic operations in SELECT clauses, you can find the doc [here](https://cwiki.apache.org/confluence/display/IOTDB/Arithmetic+Operations+In+SELECT+Clauses). Please leave your opinion here if you have further ideas :)

**Comment by ope-nz** [comment]
Thanks @SteveYurongSu those requirements look great, I dont have any additional requirements beyond what you have documented in the doc. 

BTW I am the user who created the original issue, I didnt realise I was logged in with a different account at the time.

**Comment by HTHou** [comment]
This feature is added in v0.13 version, which will be released soon. 
https://iotdb.apache.org/UserGuide/Master/IoTDB-SQL-Language/DML-Data-Manipulation-Language.html#arithmetic-query
