### ISSUE TITLE
使用mybatis整合iotDB使用，抛出java.sql.SQLException: Method not supported异常，无法正常使用

### ISSUE THREAD

**Issue by lch0771** [apache/iotdb#1878]
使用mybatis来整合iotDB使用，抛出java.sql.SQLException: Method not supported异常，无法正常使用

**Comment by HTHou** [comment]
您好，请问这里调用了哪个jdbc方法？我们目前的jdbc是按照最小可用集来实现的，有些方法可能暂时未实现，常用的方法应该是都支持的。
