### ISSUE TITLE
是否有方法可以按月（每个月实际天数非30天）聚合数据？

### ISSUE THREAD

**Issue by try-anything** [apache/iotdb#1903]
以一年为时间范围想要按月聚合每个月的数据，类似group by([2020-01-01T00:00:00, 2021-01-01T00:00:00),1mo,1mo)。但是每个月的天数不同用1mo=30day会多出一段统计剩余5（365%30）天的结果，想问下有没有方法可以做到按月聚合每个月（不同月不同天数）的数据。

**Comment by qiaojialin** [comment]
感谢反馈，这个功能我们之后加一下，按照自然月聚合

**Comment by HTHou** [comment]
这个功能已经有PR了，0.12版本会支持。
https://github.com/apache/iotdb/pull/2029
