### ISSUE TITLE
请问现在有什么可视化客户端直接操作iotdb里的数据么，查询或者插入

### ISSUE THREAD

**Issue by Level1Accelerator** [apache/iotdb#2125]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HTHou** [comment]
支持Grafana
https://iotdb.apache.org/zh/UserGuide/Master/Ecosystem%20Integration/Grafana.html
目前的功能比较有限，新的grafana插件正在开发中

**Comment by qiaojialin** [comment]
https://github.com/apache/iotdb/pull/2096

有一个和 Zeppelin 集成的 PR，可以试用一下。

This PR integrates IoTDB with Zeppelin, you could try it~

**Comment by qiaojialin** [comment]
Zeppelin 已经合并到 0.12 版本了
http://iotdb.apache.org/zh/UserGuide/Master/Ecosystem%20Integration/Zeppelin-IoTDB.html
