### ISSUE TITLE
Precision loss and incompatible precisions between select and select last.

### ISSUE THREAD

**Issue by 140378476** [apache/iotdb#2131]
**Describe the bug**
1. I can not get precise result of float values using  `select` query.
2. When executing `select` and `select last`, I got float values in different precisions.

**To Reproduce**
1. Create timeseries: ` CREATE TIMESERIES root.t.d WITH DATATYPE=FLOAT, ENCODING=RLE`
2. Insert data: `INSERT INTO root.t(timestamp,d) VALUES(1,1.23456789)`
3. Select data: `SELECT * FROM root.t`, the returned value is `1.23`.
4. Select data using last: ` SELECT LAST * FROM root.t`, the returned value is `1.2345679`.

**Expected behavior**
It should return at least the precise float value instead of an approximate one. 
The result is expected to at least be the same as the returned value using select last.

**Screenshots**

![图片](https://user-images.githubusercontent.com/21256331/100367025-958aba80-303c-11eb-8bd6-2c2aa1527670.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version iotdb 0.10.1

**Additional context**
No

**Comment by HTHou** [comment]
Hi, I think `RLE` is not a good choice for high precision. If you looking for high precision, better to use `GORILLA` instead.  

Please see this doc on website for more information of the encoding precision.
https://iotdb.apache.org/UserGuide/Master/Concept/Encoding.html

The reason why `select last` doesn't loss precision is the result is cached when the data insert. :)
