### ISSUE TITLE
Incorrect result returned by `getFloat` in JDBC.

### ISSUE THREAD

**Issue by 140378476** [apache/iotdb#2132]
**Describe the bug**
I got clearly incorrect results when retrieving data using method `getFloat`.

**To Reproduce**
1. Create timeseries: ` CREATE TIMESERIES root.t.d WITH DATATYPE=FLOAT, ENCODING=GORILLA`
2. Insert data: `INSERT INTO root.t(timestamp,d) VALUES(1,1.2345678)`
3. Retrieve data using JDBC: (mostly copied from the user guide and converted to Kotlin)
```
    fun getConnection(): Connection? {
        // JDBC driver name and database URL
        val driver = "org.apache.iotdb.jdbc.IoTDBDriver"
        val url = "jdbc:iotdb://127.0.0.1:6667/"

        // Database credentials
        val username = "root"
        val password = "root"
        var connection: Connection? = null
        try {
            Class.forName(driver)
            connection = DriverManager.getConnection(url, username, password)
        } catch (e: ClassNotFoundException) {
            e.printStackTrace()
        } catch (e: SQLException) {
            e.printStackTrace()
        }
        return connection
    }

    fun select(){
        val connection = getConnection()
        if (connection == null) {
            println("get connection defeat")
            return
        }
        val statement: Statement = connection.createStatement()
        statement.execute("SELECT d from root.test")
        val rs = statement.resultSet
        rs.next()
        println("String:")
        println(rs.getString(2))
        println("Float:")
        println(rs.getFloat(2))
    }
```

4. The output is:
```
String:
1.2345678
Float:
1.0673209E9
```
I got incorrect result from `getFloat()`.

**Expected behavior**
I should get a correct result from `getFloat()`. 

**Desktop (please complete the following information):**
 - Version 0.10.1

**Additional context**
The inplementation in `IoTDBRpcDataSet.java` shows that it just converts 
the bytes to float in the method, while the bytes are actually in the format of String.

A further dig into the source code shows that all data are in the format of String except the timestamp.
I presume that the raw data transferred from the database is in the format of String.
This may cause performance issue(extra parsing and formatting, more transfer cost).

**Comment by HTHou** [comment]
Hi, same reason of your last question. Try to use encoding type `GORILLA `?

**Comment by 140378476** [comment]
Using encoding type `GORILLA` did fix the precision loss issue, but the method `getFloat` still return
incorrect values. 

I will try to make a simple fix for the latter problem.

**Comment by qiaojialin** [comment]
Hi, thanks for your detailed description, and welcome to contribute 👍

**Comment by Alima777** [comment]
Hi, I checked the code and found it's a typo mistake: It's in 326 line of `AbstractIoTDBJDBCResultSet`. 

Thanks for your detailed description!! If you don't mind, welcome to pull a PR to fix it :D

**Comment by HTHou** [comment]
The bug is fixed. I'll close this issue.
