### ISSUE TITLE
希望降频聚合查询补空值支持avg函数

### ISSUE THREAD

**Issue by flyingsand008** [apache/iotdb#2135]
降频聚合查询补空值，现在只支持 last_value 聚合函数。avg函数会报错。
Msg: 411: Meet error in query process: Group By Fill only support last_value function
希望能支持avg函数。

**Comment by qiaojialin** [comment]
感谢反馈，争取在 0.12 支持~

**Comment by HTHou** [comment]
0.13 版本支持了

- https://github.com/apache/iotdb/pull/4303
- https://github.com/apache/iotdb/pull/4375
