### ISSUE TITLE
持续写入时，一些老数据会查不到，但是重启后又能够被正确查询(When writing continuously, some old data can not be queried, but it can be queried correctly after restart)

### ISSUE THREAD

**Issue by zhanglingzhe0820** [apache/iotdb#2147]
持续写入时，能被查询到的数据总量维持在一定的阈值内，但是重启后又能够查询到之前写入的所有数据(When writing continuously, the total amount of data that can be queried remains within a certain threshold, but all of the data can be queried correctly after restart)

**Comment by zhanglingzhe0820** [comment]
fix this bug in [pr](https://github.com/apache/iotdb/pull/2141)

**Comment by qiaojialin** [comment]
fixed in master and rel/0.11
