### ISSUE TITLE
File Not Found when some TsFileResources serializing

### ISSUE THREAD

**Issue by HTHou** [apache/iotdb#2162]
In `0.11.0`, delete data in files and merge will serialize tsfile resource concurrently. Some error logs may show as below.

<img width="1016" alt="Screen Shot 2020-12-02 at 2 15 54 PM" src="https://user-images.githubusercontent.com/25913899/100852660-c4cc7c00-34c1-11eb-9bd8-c6acf28e697c.png">

A PR is fixing it. https://github.com/apache/iotdb/pull/2161

**Comment by qiaojialin** [comment]
has cherry-picked to rel/0.11
