### ISSUE TITLE
getObject should not return String for all data types

### ISSUE THREAD

**Issue by Alima777** [apache/iotdb#2169]
![image](https://user-images.githubusercontent.com/34242296/100957361-40c3d400-3555-11eb-9d2a-d1c5ecce1927.png)
![image](https://user-images.githubusercontent.com/34242296/100957385-4a4d3c00-3555-11eb-8047-8b47da9a838c.png)

**Comment by qiaojialin** [comment]
fixed in rel/0.11 (0.11.2-SNAPSHOT) and master (0.12.0-SNAPSHOT)
