### ISSUE TITLE
5s? 

### ISSUE THREAD

**Issue by cuibo01** [apache/iotdb#2185]
https://github.com/apache/iotdb/blob/19d57cff1b503155d0e70df50b4e13a37e4213b7/cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java#L1014

i think it is 60s and add a new conf

**Comment by jt2594838** [comment]
5s is for one round, which is enough as the request is very small and  not time-consuming. The total time is controlled by START_UP_TIME_THRESHOLD_MS, which is 60s.
