### ISSUE TITLE
例子能不用1970-1-1号吗？

### ISSUE THREAD

**Issue by pan2za** [apache/iotdb#2199]
**Describe the bug**
+-----------------------+------------------------+
|                   Time|root.ln.wf01.wt01.status|
+-----------------------+------------------------+
|1970-01-01T08:00:00.100|                    true|
|1970-01-01T08:00:00.200|                   false|
+-----------------------+------------------------+
Total line number = 2
这个时间太。。。了。
能自动生成时间吗？
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by pan2za** [comment]
1607224431 秒
单位是毫秒
INSERT INTO root.ln.wf01.wt01(timestamp,status,temperature) values(1607217224432,false,13)

**Comment by qiaojialin** [comment]
例子里的时间戳是 0，默认对应 1970年1月1号。
可以调整时间戳的值啊，如果是long，可以用 System.currentTimeMillis()，如果是 sql 里，可以用 now() 表示现在时间。

**Comment by pan2za** [comment]
哎哎，其实我只是想让你们提供一个自动生成时间戳的接口而已，或者提供一个不带时间戳的接口。你们这么难用，怎么期望用？
