### ISSUE TITLE
用time进行order by排序，order by time 和order by time desc查询出来的数据不一样。desc数据少。

### ISSUE THREAD

**Issue by suikailing** [apache/iotdb#2202]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by HTHou** [comment]
您好，这个bug在最新的代码已经修复完成 #2186，可以试试最新的master分支代码。

**Comment by qiaojialin** [comment]
solved in 0.11.1 and master branch
