### ISSUE TITLE
sync delete all records

### ISSUE THREAD

**Issue by flyingsand008** [apache/iotdb#2251]
**Describe the bug**
sync sender,delete some record,then sync receiver will delete all records of the timeseries.

**To Reproduce**
1. in sync sender
insert into root.ln.wf01.wt01(timestamp,temperature) values(2020-11-01 00:00:00.000,21.113817)
insert into root.ln.wf01.wt01(timestamp,temperature) values(2020-11-02 00:00:00.000,20.653296)
insert into root.ln.wf01.wt01(timestamp,temperature) values(2020-11-04 00:00:00.000,24.588139)
IoTDB> select * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+
|                         Time|root.ln.wf01.wt01.temperature|
+-----------------------------+-----------------------------+
|2020-11-01T00:00:00.000+08:00|                    21.113817|
|2020-11-02T00:00:00.000+08:00|                    20.653296|
|2020-11-04T00:00:00.000+08:00|                    24.588139|
+-----------------------------+-----------------------------+
flush
2. after sync 
in sync receiver 
IoTDB> select * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+
|                         Time|root.ln.wf01.wt01.temperature|
+-----------------------------+-----------------------------+
|2020-11-01T00:00:00.000+08:00|                    21.113817|
|2020-11-02T00:00:00.000+08:00|                    20.653296|
|2020-11-04T00:00:00.000+08:00|                    24.588139|
+-----------------------------+-----------------------------+
3. in sync sender
IoTDB> delete from root.ln.wf01.wt01 where time<2020-11-03T00:00:00.000+08:00
Msg: The statement is executed successfully.
IoTDB> select * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+
|                         Time|root.ln.wf01.wt01.temperature|
+-----------------------------+-----------------------------+
|2020-11-04T00:00:00.000+08:00|                    24.588139|
+-----------------------------+-----------------------------+
flush
4. after sync 
in sync receiver
IoTDB> select * from root.ln.wf01.wt01
+----+-----------------------------+
|Time|root.ln.wf01.wt01.temperature|
+----+-----------------------------+
+----+-----------------------------+
Empty set.

**Expected behavior**
in sync receiver
IoTDB> select * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+
|                         Time|root.ln.wf01.wt01.temperature|
+-----------------------------+-----------------------------+
|2020-11-04T00:00:00.000+08:00|                    24.588139|
+-----------------------------+-----------------------------+

**Desktop (please complete the following information):**
 - Version 0.11.0

**Comment by fanhualta** [comment]
Hi, thanks for your report. I have reproduced your case. In fact, according to the implementation of update and delete operations in the current synchronization module, the case is correct. That is, the deletion and update operation is not timely but delayed, the case will happen in the intermediate state. However, the current implementation is not user-friendly for users to use sync module, so further design is needed.
