### ISSUE TITLE
sync last point query not right

### ISSUE THREAD

**Issue by flyingsand008** [apache/iotdb#2256]
**To Reproduce**
1. in sync sender
insert into root.ln.wf01.wt01(timestamp,temperature) values(2020-11-01 00:00:00.000,21.113817)
insert into root.ln.wf01.wt01(timestamp,temperature) values(2020-11-02 00:00:00.000,20.653296)
flush
2. after sync
 in sync sender
insert into root.ln.wf01.wt01(timestamp,temperature) values(2020-11-04 00:00:00.000,24.588139)
flush
IoTDB> select * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+
|                         Time|root.ln.wf01.wt01.temperature|
+-----------------------------+-----------------------------+
|2020-11-01T00:00:00.000+08:00|                    21.113817|
|2020-11-02T00:00:00.000+08:00|                    20.653296|
|2020-11-04T00:00:00.000+08:00|                    24.588139|
+-----------------------------+-----------------------------+
IoTDB> select last * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+---------+
|                         Time|                   timeseries|    value|
+-----------------------------+-----------------------------+---------+
|2020-11-04T00:00:00.000+08:00|root.ln.wf01.wt01.temperature|24.588139|
+-----------------------------+-----------------------------+---------+
3. after sync
in sync receiver
IoTDB> select * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+
|                         Time|root.ln.wf01.wt01.temperature|
+-----------------------------+-----------------------------+
|2020-11-01T00:00:00.000+08:00|                    21.113817|
|2020-11-02T00:00:00.000+08:00|                    20.653296|
|2020-11-04T00:00:00.000+08:00|                    24.588139|
+-----------------------------+-----------------------------+
IoTDB> select last * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+---------+
|                         Time|                   timeseries|    value|
+-----------------------------+-----------------------------+---------+
|2020-11-02T00:00:00.000+08:00|root.ln.wf01.wt01.temperature|20.653296|
+-----------------------------+-----------------------------+---------+

**Expected behavior**
in sync receiver
IoTDB> select last * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+---------+
|                         Time|                   timeseries|    value|
+-----------------------------+-----------------------------+---------+
|2020-11-04T00:00:00.000+08:00|root.ln.wf01.wt01.temperature|24.588139|
+-----------------------------+-----------------------------+---------+

**Desktop (please complete the following information):**
 - Version 0.11.0

**Comment by fanhualta** [comment]
Hi, I try to reproduce your case, but I  just get the expected behavior.

**Comment by flyingsand008** [comment]
Hi,I'm sorry.Some steps are missing,please try again:

1. in sync sender

> IoTDB> insert into root.ln.wf01.wt01(timestamp,temperature) values(2020-11-01 00:00:00.000,21.113817)
Msg: The statement is executed successfully.
IoTDB> insert into root.ln.wf01.wt01(timestamp,temperature) values(2020-11-02 00:00:00.000,20.653296)
Msg: The statement is executed successfully.
IoTDB> flush
Msg: The statement is executed successfully.
IoTDB> select * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+
|                         Time|root.ln.wf01.wt01.temperature|
+-----------------------------+-----------------------------+
|2020-11-01T00:00:00.000+08:00|                    21.113817|
|2020-11-02T00:00:00.000+08:00|                    20.653296|
+-----------------------------+-----------------------------+
Total line number = 2
It costs 0.196s
IoTDB> select last * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+---------+
|                         Time|                   timeseries|    value|
+-----------------------------+-----------------------------+---------+
|2020-11-02T00:00:00.000+08:00|root.ln.wf01.wt01.temperature|20.653296|
+-----------------------------+-----------------------------+---------+
Total line number = 1
It costs 0.040s

2. after sync
in sync receiver

> IoTDB>  select * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+
|                         Time|root.ln.wf01.wt01.temperature|
+-----------------------------+-----------------------------+
|2020-11-01T00:00:00.000+08:00|                    21.113817|
|2020-11-02T00:00:00.000+08:00|                    20.653296|
+-----------------------------+-----------------------------+
Total line number = 2
It costs 1.645s
IoTDB>  select last * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+---------+
|                         Time|                   timeseries|    value|
+-----------------------------+-----------------------------+---------+
|2020-11-02T00:00:00.000+08:00|root.ln.wf01.wt01.temperature|20.653296|
+-----------------------------+-----------------------------+---------+
Total line number = 1
It costs 0.087s

3. in sync sender

> IoTDB> insert into root.ln.wf01.wt01(timestamp,temperature) values(2020-11-04 00:00:00.000,24.588139)
Msg: The statement is executed successfully.
IoTDB> flush
Msg: The statement is executed successfully.
IoTDB> select * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+
|                         Time|root.ln.wf01.wt01.temperature|
+-----------------------------+-----------------------------+
|2020-11-01T00:00:00.000+08:00|                    21.113817|
|2020-11-02T00:00:00.000+08:00|                    20.653296|
|2020-11-04T00:00:00.000+08:00|                    24.588139|
+-----------------------------+-----------------------------+
Total line number = 3
It costs 0.020s
IoTDB> select last * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+---------+
|                         Time|                   timeseries|    value|
+-----------------------------+-----------------------------+---------+
|2020-11-04T00:00:00.000+08:00|root.ln.wf01.wt01.temperature|24.588139|
+-----------------------------+-----------------------------+---------+
Total line number = 1
It costs 0.009s

4. after sync
in sync receiver

> IoTDB> select * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+
|                         Time|root.ln.wf01.wt01.temperature|
+-----------------------------+-----------------------------+
|2020-11-01T00:00:00.000+08:00|                    21.113817|
|2020-11-02T00:00:00.000+08:00|                    20.653296|
|2020-11-04T00:00:00.000+08:00|                    24.588139|
+-----------------------------+-----------------------------+
Total line number = 3
It costs 0.039s
IoTDB> select last * from root.ln.wf01.wt01
+-----------------------------+-----------------------------+---------+
|                         Time|                   timeseries|    value|
+-----------------------------+-----------------------------+---------+
|2020-11-02T00:00:00.000+08:00|root.ln.wf01.wt01.temperature|20.653296|
+-----------------------------+-----------------------------+---------+
Total line number = 1
It costs 0.019s


the second last query is the same as the first

**Comment by jixuan1989** [comment]
@fanhualta  any update?
