### ISSUE TITLE
分布式版本是不是不收费

### ISSUE THREAD

**Issue by chinausers** [apache/iotdb#2301]
分布式版本只有在商用才会使用。后边会不会考率收费问题。

**Comment by chinausers** [comment]
我还是建议收费的。毕竟商用维护，肯定是要花钱的。

**Comment by jixuan1989** [comment]
代码会保持开源，并遵从Apache License 2.0。
The project will be open-sourced, and obey the Apache License 2.0.

至于商用维护或者定制的需求，可以联系开发团队~。
