### ISSUE TITLE
Data error when using CHINESE CHARACTAR in path

### ISSUE THREAD

**Issue by Alima777** [apache/iotdb#2312]
Reappearance:

![image](https://user-images.githubusercontent.com/34242296/102969666-0d131300-4531-11eb-98ec-12fbec3e5513.png)

**Comment by Alima777** [comment]
The operating system is Windows. I tried Mac and it was good.

**Comment by HTHou** [comment]
Don't forget to cherry-pick the PR #2338 to master branch...
