### ISSUE TITLE
doc中图片无法浏览

### ISSUE THREAD

**Issue by eleleme** [apache/iotdb#2347]
githup和官网上的文档图片都是无法浏览的,如
https://user-images.githubusercontent.com/19167280/95296983-492cc500-08ac-11eb-9f66-c9c78401c61d.png

**Comment by HTHou** [comment]
您好，这个是国内网络环境导致的，使用代理后就可以了。

**Comment by flyingsand008** [comment]
# GitHub Start
140.82.114.4 github.com
185.199.108.153 assets-cdn.github.com
199.232.69.194 github.global.ssl.fastly.net
140.82.114.3 gist.github.com
199.232.96.133 user-images.githubusercontent.com
199.232.96.133 raw.githubusercontent.com
199.232.96.133 gist.githubusercontent.com
199.232.96.133 cloud.githubusercontent.com
199.232.96.133 camo.githubusercontent.com
199.232.96.133 avatars0.githubusercontent.com
199.232.96.133 avatars1.githubusercontent.com
199.232.96.133 avatars2.githubusercontent.com
199.232.96.133 avatars3.githubusercontent.com
199.232.96.133 avatars4.githubusercontent.com
199.232.96.133 avatars5.githubusercontent.com
199.232.96.133 avatars6.githubusercontent.com
199.232.96.133 avatars7.githubusercontent.com
199.232.96.133 avatars8.githubusercontent.com
# GitHub End
