### ISSUE TITLE
org.apache.iotdb.db.utils.TypeInferenceUtils#isNumber returns true when the input is "NaN"

### ISSUE THREAD

**Issue by weizihan0110** [apache/iotdb#2476]
The reason is Double.parseDouble("NaN") returns true:
![image](https://user-images.githubusercontent.com/15262869/104301220-56d49500-5502-11eb-941d-096a6bac5012.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jixuan1989** [comment]
Cool. Could you fix this?
