### ISSUE TITLE
8181可视化页面空指针问题

### ISSUE THREAD

**Issue by HappyDragon1994** [apache/iotdb#2518]
版本：v0.11.x
刚进入页面是正常的，然后用客户端执行几句语句后，页面报空指针
![QQ图片20210119112805](https://user-images.githubusercontent.com/60464328/104984424-9e4eaa00-5a49-11eb-80dc-ff298360d19a.jpg)

**Comment by wangchao316** [comment]
this issue has solved in master branch. 
https://github.com/apache/iotdb/pull/2459
