### ISSUE TITLE
NPE thrown when executing group by fill query without given `last_value` in select clause

### ISSUE THREAD

**Issue by SteveYurongSu** [apache/iotdb#2563]
**Describe the bug**
NPE thrown when executing group by fill query without given `last_value` in select clause.

**To Reproduce**
```sql
select ZT11709 from root.group_69.1701 GROUP BY([2020-06-09T23:51:35.267+08:00, 2020-06-17T23:17:14.887+08:00), 5m) FILL (double[PREVIOUS, 1m])
```

**Expected behavior**
The error message should contain "Group By Fill only supports last_value function"

**Comment by HTHou** [comment]
Fixed
