### ISSUE TITLE
OOM（内存溢出问题）

### ISSUE THREAD

**Issue by xlgo** [apache/iotdb#2595]
我们公司在生产上使用iotdb，数据量不算小。 
现在有个问题就是，每隔一个月左右，内存就会承包，到达29G 。然后就会内存溢出。
是做了一个docker镜像在跑。

**Comment by HTHou** [comment]
您好，想请问一下现在在使用哪个版本，大概有多少个存储组和序列，分配了多少内存？

**Comment by xlgo** [comment]
### 基础信息
- 版本：V0.10.0
- 存储组：50个
- 序列：929872个

### 设备路径： root.p1.p2.p3.p4
p1=50
p3= 51
p3=152
p4=120785

每个设备下数据有十几万的，有几万的,也有几十的
```sh
IoTDB> select count(accStatus) from root.*.*.p.014146520068
+-----------------------------------------------+
|count(root.g_11.bsjkj.p.014146520068.accStatus)|
+-----------------------------------------------+
|                                         111096|
+-----------------------------------------------+
IoTDB> select count(accStatus) from root.*.bsjkj.p.014146973405
+-----------------------------------------------+
|count(root.g_35.bsjkj.p.014146973405.accStatus)|
+-----------------------------------------------+
|                                          84770|
+-----------------------------------------------+
Total line number = 1
It costs 0.044s
IoTDB> select count(accStatus) from root.*.bsjkj.p.014146510015
+-----------------------------------------------+
|count(root.g_46.bsjkj.p.014146510015.accStatus)|
+-----------------------------------------------+
|                                           6240|
+-----------------------------------------------+
Total line number = 1
It costs 0.045s
IoTDB> select count(accStatus) from root.*.bsjkj.p.014146510016
+-----------------------------------------------+
|count(root.g_16.bsjkj.p.014146510016.accStatus)|
+-----------------------------------------------+
|                                            114|
+-----------------------------------------------+

```


### 并且经常出现下面信息
```log
2021-01-28 21:02:43,367 [pool-5-IoTDB-RPC-Client-thread-47] INFO  org.apache.iotdb.db.service.TSServiceImpl:507 - meet error while parsing SQL to physical plan: Filter has some time series don't correspond to any known time series
```



### 改动配置
`iotdb-env.sh`
```sh
if [ "$quarter_system_memory_in_mb" -gt "8192" ]
    then
    quarter_system_memory_in_mb="32768"
fi
```
`iotdb-engine`
```properties
tsfile_size_threshold=1073741824
enable_parameter_adapter=false
```
### 代表性日志
[log-all-2021-01-25.0.log](https://github.com/apache/iotdb/files/5891022/log-all-2021-01-25.0.log)
[log-error-2021-01-25.0.log](https://github.com/apache/iotdb/files/5891024/log-error-2021-01-25.0.log)


### 出现过的问题
- 链接超时
- 内存溢出（基本一个月就挂一次，从0.10.0发布后开始）
- 能够连接，但是插入数据报错

**Comment by qiaojialin** [comment]
memtble_size_threshold 是多大？

加个微信说吧  qiaojialin1993

**Comment by qiaojialin** [comment]
If OOM, two ways:
(1) config manually if you use 0.10 or earlier version:

 conf/iotdb-engine.properties:
 enable_parameter_adapter=false
 tsfile_size_threshold=100000000
 memtable_size_threshold=JVM memory/2/storage group number/4

(2) upgrade to version 0.11.2 or a later version
Generally, in 0.11 version, you do not need to config manually. If still OOM, you could still try to config

 conf/iotdb-engine.properties:
 enable_mem_control=false
 tsfile_size_threshold=100000000
 memtable_size_threshold=JVM memory/2/storage group number/4

 If still OOM, lower the memtable_size_threshold!

(3) check whether you have millions of devices, the penultimate nodes in the path. Try to modify your model to less than one million devices.

**Comment by xlgo** [comment]
`memtable_size_threshold`  我们这边看了一下默认是 1G。
