### ISSUE TITLE
Filter has some time series don't correspond to any known time series

### ISSUE THREAD

**Issue by qiaojialin** [apache/iotdb#2598]
This is due to the where clause contains some non-exist time series.

For example:

create timeseries root.turbine1.d1.s2 with datatype=DOUBLE, encoding=GORILLA, compression=SNAPPY
select * from root.turbine1.d1 where  s1=1

You will get this error message.

It's better to log which time series does not exist.

**Comment by Alima777** [comment]
Hi, don't forget to cherry-pick to 0.11.
