### ISSUE TITLE
Clean the tracing log

### ISSUE THREAD

**Issue by qiaojialin** [apache/iotdb#2679]
Currently, the tracing log looks like this:

![image](https://user-images.githubusercontent.com/7240743/107851979-afbc8380-6e48-11eb-9077-e0ca99e17e0e.png)

The information of tsfile resource is too much. It's better to remove the time range of each device.

**Comment by liu-hai** [comment]
This feature "Clean the Tracing Log" I will develop

**Comment by Alima777** [comment]
Fixed.
