### ISSUE TITLE
Too many paths in one query! Currently allowed max deduplicated path number is 28, this query contains 29 deduplicated path.

### ISSUE THREAD

**Issue by qiaojialin** [apache/iotdb#2747]
Since 0.11.0:

This is due to that currently allocated memory for the query is occupied by other query instances, the left memory could only support a query with 28 series.

You could enlarge the memory allocated for read in write_read_schema_free_memory_proportion=4:3:1:2
Or decrease the fetch_size in each query, the default is 10000.

We calculate the memory usage for a query by : number of series in this query * fetch_size

**Comment by qiaojialin** [comment]
fetch_size controls how many rows are return from the server each time.

For example:

If your SQL is: SELECT S11,S14 FROM root.6.438,root.3.435 WHERE time = 1601895100000 fill (TEXT[PREVIOUS])

You could set fetch_size to 1.

**Comment by JackieTien97** [comment]
If you use the session pool, you can't set the fetchSize alone for each query. So you can change the default fetchSize 10000 to 1000 while constructing the session pool.
