### ISSUE TITLE
org.apache.iotdb.db.exception.metadata.IllegalPathException: Illegal path: root.XXX.YYY is not a legal path

### ISSUE THREAD

**Issue by ope-nz** [apache/iotdb#2767]
**Describe the bug**
I noticed today in my logs that the error below is noted. What is interesting is that the storage group root.Test no longer exists but I am still seeing this message. 

Is this a bug?

How do I clear this message?

2021-03-02 18:48:24,578 [main] ERROR org.apache.iotdb.db.metadata.MManager:269 - Can not operate cmd 0,root.Test."C:\\".status,0,2,1,,,
org.apache.iotdb.db.exception.metadata.IllegalPathException: Illegal path: root.Test."C:\\".status is not a legal path
at org.apache.iotdb.db.metadata.MetaUtils.splitPathToDetachedPath(MetaUtils.java:70)
at org.apache.iotdb.db.metadata.PartialPath.(PartialPath.java:51)
at org.apache.iotdb.db.metadata.MManager.operation(MManager.java:353)
at org.apache.iotdb.db.metadata.MManager.initFromLog(MManager.java:266)
at org.apache.iotdb.db.metadata.MManager.init(MManager.java:218)
at org.apache.iotdb.db.service.IoTDB.initMManager(IoTDB.java:156)
at org.apache.iotdb.db.service.IoTDB.setUp(IoTDB.java:100)
at org.apache.iotdb.db.service.IoTDB.active(IoTDB.java:84)
at org.apache.iotdb.db.service.IoTDB.main(IoTDB.java:66)

**To Reproduce**
1. Create a timeseries root.Test.C:\\.status
2. Delete storage group root.Test
3. Stop/Start server
4. After restart see error in logs

**Expected behavior**

**Comment by Alima777** [comment]
I'm sorry, but it's not a bug. The problem is cause by, in "C:\" a backslash `\` is in front of the second double quotes, then this double quotes will be thought as the part of the whole string and there is no ending double quotes.

**Comment by ope-nz** [comment]
@Alima777 the problem is not the backslash.

The problem is once the timeseries and storage group are deleted this error still appears in the logs. Even after a server restart.

So there is no timeseries or storage group after the delete but the exception is still shown on start up.

I have already raised another issue regarding the use of backslash. The JDBC driver currently allows this but that is a different issue to this one - https://github.com/apache/iotdb/issues/2722

**Comment by Alima777** [comment]
Hey, I checked the issue#2722 and this problem again.

Actually, in 0.12 we don't support this type of path and it should not be created successfully from the beginning. 

In the 0.11 version that you use, this problem is caused by the mlog. When you delete the metadata and restart the server, the metadata will have to be created and deleted again by reading the mlog, when the exception will be thrown.

So if you want to clear the message, maybe you have to clean the mlog file manually.

**Comment by ope-nz** [comment]
@Alima777 thank you, that is good news about v12.

I see this in the mlog.txt file - this is from my testing. Do I remove these entires or delete the entire file?

_0,root.Test.C:/.status,0,2,1,,,
0,root.Test."C:\\".status,0,2,1,,,
0,root.Test."C:\".status,0,2,1,,,
1,root.Test."C:\".status
1,root.Test.C.status
1,root.Test.C:.status
1,root.Test.C:/.status
1,root.Test."C:\\".status
1,root.Test./test.status
1,root.Test./.status_

**Comment by jixuan1989** [comment]
Hi, yes, 
just remove all these lines.
