### ISSUE TITLE
Question; Listing Unique Sensor Values (not numeric)

### ISSUE THREAD

**Issue by ope-nz** [apache/iotdb#2769]
Scenario; I have a sensor that returns a string value for example red, blue, green - lets call the sensor "color"

If I dont know all the possible values but want to retrieve them from the database via query is there any query I can run?

In a normal RDBMS I could run either of these queries;

"select distinct color from table" and I would get the unique values.
Or 
"select color,count(color) from table group by color" and I would get the unique values and their count.

In iotDB "group by" only works for time so its not possible to run a query using group by.

Question; Is there any query that would achieve this?

**Comment by jixuan1989** [comment]
Hi ope-nz, 
At least, IoTDB does not support that currently...

"Group by" in IoTDB:
1. Group by time interval.
2. Group by partial path of series, e.g., group by level=1,
e.g., you have two prefix path: `root.china.a`, `root.china.b`, `root.newzealand.a`,
 `select count(*) from root group by level=1` will returns the the total count of data points that belongs to China, and the total counts of data points taht belongs to New Zealand.

3. Group by data value is not supported now..
Quickly thinking, I have no a very efficient algorithm to implement it...

How do you think?

BYW, send mails to  dev@iotdb.apache.org (subscribe dev-subscribe@iotdb.apache.org before your first sending email) if you can not get responses from github issues (Some guys in the community like Github issue, but for me, I rarely read these issues... and mainly focus the mailing list..)

**Comment by ope-nz** [comment]
Thanks @jixuan1989 I will join the mailing list.

I couldnt see a way to achive this either. I have resorted to storing the list in a RDBMS with a unique key and am storing the key in iotDB. It cuts down on iotDB storage too.
