### ISSUE TITLE
Alter timestamp_precision if IoTDB has ever been started before / 在之前启动过IoTDB的情况下修改时间精度

### ISSUE THREAD

**Issue by yinlenc** [apache/iotdb#2793]
#timestamp_precision
目前在0.11.2版本的配置文件中，timestamp_precision仍然只能设置成ms，设置成us就无法启动。 我目前在做技术调研，参数的采样周期是1KHz以上，请问，如何解决？

**Comment by HTHou** [comment]
您好，如果之前没有改 timestamp_precision就启动过，需要手动删除 data/system/schema/system.properties 文件。
如果已经写入过数据，最好将整个data目录删掉。否则已写入的数据查询会存在问题。。。

**Comment by yinlenc** [comment]
> 您好，如果之前没有改 timestamp_precision就启动过，需要手动删除 data/system/schema/system.properties 文件。
> 如果已经写入过数据，最好将整个data目录删掉。否则已写入的数据查询会存在问题。。。

OK，完美解决。
