### ISSUE TITLE
支持按非时间列聚合数据吗？

### ISSUE THREAD

**Issue by biuboombiuboom** [apache/iotdb#2865]
root.a1.b1.s1 root.a2.b2.s1

**Comment by HTHou** [comment]
您好，0.12 版本还支持按层级聚合。
https://iotdb.apache.org/zh/UserGuide/Master/Operation%20Manual/DML%20Data%20Manipulation%20Language.html#%E5%88%86%E5%B1%82%E8%81%9A%E5%90%88%E6%9F%A5%E8%AF%A2
