### ISSUE TITLE
Grafana can't get the data of iotdb time series database, Why？ 

### ISSUE THREAD

**Issue by LeeZChuan** [apache/iotdb#2878]
**Describe the bug**
I recently encountered a problem. When I successfully used “iotdb-grafana” to establish a connection with the iotdb database.But I can’t get the image on the page where the chart is made. Although I have searched for my keywords in the database, the icon does not draw a time series line chart.

My guess is that the database time is a millisecond timestamp, while grafana uses yy:mm:dd:hh:ss.

But I find Grafana  support the  millisecond timestamp.?

Maybe there may be other reasons, ？？

**Expected behavior**
 Can not draw the time series line chart .

**Screenshots**
[pic](https://i.stack.imgur.com/8p0FI.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome,
 - Version iotdb-grafana-0.12.0-SNAPSHOT

**Additional context**
NO

**Comment by qiaojialin** [comment]
Hi, You could see the log of iotdb-grafana.war to see the sql that the grafana sends to IoTDB. The sql could be executed in the CLI. Then you can put the sql here.

**Comment by LeeZChuan** [comment]
ok，thanks

I find the databases of date is different from the local computer date. When I deal with it. It's working.
