### ISSUE TITLE
The write stream is not closed when executing the command 'tracing off'

### ISSUE THREAD

**Issue by liu-hai** [apache/iotdb#2911]
**Describe the bug**
The write stream is not closed when executing the command 'TRACING OFF'
` private void operateTracing(TracingPlan plan) {
    IoTDBDescriptor.getInstance().getConfig().setEnablePerformanceTracing(plan.isTracingOn());
  }`

**Comment by liu-hai** [comment]
I’ll fix it ASAP

**Comment by Alima777** [comment]
Fixed in PR #2961
