### ISSUE TITLE
Thrift throws a null exception 

### ISSUE THREAD

**Issue by HTHou** [apache/iotdb#2915]
After inserting data by IoTDB benchmark, the thrift throws an exception.
https://github.com/thulab/iotdb-benchmark
![image](https://user-images.githubusercontent.com/25913899/112564347-10f74f80-8e16-11eb-9ea4-d1eac03dd3dd.png)

**Comment by JackieTien97** [comment]
This is a thrift bug, it can be fixed by upgrading thrift. You can see the details in this [blog](https://www.jianshu.com/p/c3b01bb949fa)
