### ISSUE TITLE
Log cannot fit into buffe

### ISSUE THREAD

**Issue by xuanbo** [apache/iotdb#2932]
现象：2000个存储组，设备写入一段时间后数据无法写入
版本：0.10
错误：Log cannot fit into buffer,if you don't enable Dynamic Parameters Adapter,please increase wal_buffer_size:otherwise,please increase the JVM memory

**Comment by jixuan1989** [comment]
It is mainly because the Insert operation is too large (e.g., you insert 10000000 data points in one session.isnert*() call).

In 0.10, you have to  increase wal_buffer_size in iotdb-engine.properties
