### ISSUE TITLE
UDF API, get*OrDefault, throws Exception with incorrect input

### ISSUE THREAD

**Issue by SiasDoming** [apache/iotdb#2990]
**描述**
UDF API提供的get*OrDefault参数解析接口（包括getBooleanOrDefault, getIntOrDefault, getLongOrDefault, getFloatOrDefault, getDoubleOrDefault）在输入参数形式错误时报解析错误，而非返回默认值。
**样例**
UDF实现: udfParameter.getIntOrDefault("IntArgument", 10);
调用: SELECT ExampleUDF(s1, "IntArgument"="ThisIsNotAnInteger")
Msg: 411: Error occurred in query process: Error occurred during executing UDTF#beforeStart(UDFParameters, UDTFConfigurations): java.lang.NumberFormatException: For input string: "ThisIsNotAnInteger"
**解决方案**
在相关函数接口中加入异常处理，解析错误时返回预设的默认值

**Comment by SteveYurongSu** [comment]
Hi，谢谢你的反馈！
当初设计get*OrDefault接口的时候，考虑的语义是当UDF没有提供参数时返回默认值，并非提供了参数但是出错时返回默认值。
或许我们可以加一个接口；或许您可以在用户逻辑里面主动handle NumberFormatException。
欢迎讨论或提PR哈 :D
