### ISSUE TITLE
import csv encounter an error

### ISSUE THREAD

**Issue by kevin-xin** [apache/iotdb#3051]
import csv encounter an error, the message is "Index 704" out fo bounds for length 704"
使用的版本是0.12.0，我已经创建了storage group：
show storage group;
+---------------------+
|        storage group|
+---------------------+
|root.432824.432824001|
+---------------------+

没有指定值的类型
[timeseries.txt](https://github.com/apache/iotdb/files/6363405/timeseries.txt)

导入的文件有160M，文件大概有30万行,有704列
下面附件中是csv的表头和一条记录
[timeseries.txt](https://github.com/apache/iotdb/files/6363402/timeseries.txt)

**Comment by HTHou** [comment]
您好，上面的文件里只看到了表头，能否发一下第一条记录？
