### ISSUE TITLE
Deployment Guidelines（部署指南)

### ISSUE THREAD

**Issue by HTHou** [apache/iotdb#3078]
## 关于版本 (About Version)

请升级到 0.11.4 或 0.12.1 以上版本，之前的版本有内存问题。

Please upgrade to 0.11.4 or 0.12.1 or newer version, previous versions may have OOM problem.

### 中文
重要配置参数：
iotdb-env.sh/bat
* MAX_HEAP_SIZE

iotdb-engine.properties
* primitive_array_size=32
* wal_buffer_size=16777216
* write_read_schema_free_memory_proportion=4:3:1:2 
* flush_proportion=0.4

在启动之前，需要根据写入内存和序列条数，调整以下参数：

如果参数全部默认：primitive_array_size=MAX_HEAP_SIZE / 200 / 总时间序列个数

或者详细计算：primitive_array_size=MAX_HEAP_SIZE(iotdb-env.sh/bat，换成字节) * write in write_read_schema_free_memory_proportion(写入内存占比，默认0.4) * flush_proportion / 总时间序列个数 / 2(有乱序数据) / 16（8字节时间戳 + 8字节数据）

### In English

Important parameter:

iotdb-env.sh/bat
* MAX_HEAP_SIZE

iotdb-engine.properties
* primitive_array_size=32
* wal_buffer_size=16777216
* write_read_schema_free_memory_proportion=4:3:1:2 
* flush_proportion=0.4

Before startup, you need to adjust the following parameters based on the number of written memory and sequence lines:

If using default config：primitive_array_size=MAX_HEAP_SIZE / 200 / 总时间序列个数

Or Detailed computing：primitive_array_size=MAX_HEAP_SIZE * write in write_read_schema_free_memory_proportion(default is 0.4) * flush_proportion / total time series(count timeseries) / 2(has out-of-order data) / 16（8bytes time + 8bytes value）

### 中文
重要配置参数：
iotdb-env.sh/bat
* MAX_HEAP_SIZE

iotdb-engine.properties
* primitive_array_size=128
* wal_buffer_size=16777216
* write_read_schema_free_memory_proportion=4:3:1:2 
* flush_proportion=0.4

在启动之前，需要根据写入内存和序列条数，调整以下参数：

如果参数全部默认：primitive_array_size=（MAX_HEAP_SIZE(换成字节) * 0.16 - wal_buffer_size * total storage group）/ total time series(count timeseries) / 32

或者详细计算：primitive_array_size=（MAX_HEAP_SIZE(换成字节) * write in write_read_schema_free_memory_proportion(写入内存占比，默认0.4) * flush_proportion - wal_buffer_size * 总存储组个数） / 总时间序列个数(count timeseries) / 2(有乱序数据) / 16（8字节时间戳 + 8字节数据）

当总存储组个数较多、建议减小 `wal_buffer_size`。
当总时间序列个数较多、建议减小 `primitive_array_size`。

### In English
Important parameter:

iotdb-env.sh/bat
* MAX_HEAP_SIZE

iotdb-engine.properties
* primitive_array_size=128
* wal_buffer_size=16777216
* write_read_schema_free_memory_proportion=4:3:1:2 
* flush_proportion=0.4

If using default config：primitive_array_size=（MAX_HEAP_SIZE(in byte) * 0.16 - wal_buffer_size * total storage group）/ total time series(count timeseries) / 32

Or Detailed computing：primitive_array_size=（MAX_HEAP_SIZE(in byte) * write in write_read_schema_free_memory_proportion(default is 0.4) * flush_proportion - wal_buffer_size * total storage group） / total time series(count timeseries) / 2(has out-of-order data) / 16（8byte time + 8byte value）

If the total storage group number is quite large, we suggest decreasing the value of `wal_buffer_size`.

If the total time series number is quite large, we suggest decreasing the value of `primitive_array_size`.

**Comment by neuyilan** [comment]
可以写到官网上吗，有一章节专门讲一些参数调优等注意事项。方便人直接参考。

**Comment by HTHou** [comment]
> 可以写到官网上吗，有一章节专门讲一些参数调优等注意事项。方便人直接参考。

No problem!
