### ISSUE TITLE
[iotdb-client-go] Compile error

### ISSUE THREAD

**Issue by Guoyuechuan** [apache/iotdb#3098]
Can not build the file `session_example.go`. The error info is

`go build session_exmaple.go`
 `github.com/apache/iotdb-client-go/rpc`
`/root/go/src/github.com/apache/iotdb-client-go/rpc/rpc.go:106:36: not enough arguments in call to iprot.ReadStructBegin`
        `have ()`
        `want (context.Context)`
`/root/go/src/github.com/apache/iotdb-client-go/rpc/rpc.go:114:55: not enough arguments in call to iprot.ReadFieldBegin`
        `have ()`
        `want (context.Context)`
`/root/go/src/github.com/apache/iotdb-client-go/rpc/rpc.go:198:32: too many errors`

The functions of interface TProtocol of thrift does not match. There may be other errors which may not be printed.

**Comment by manlge** [comment]
thrift must be 0.13.0

**Comment by manlge** [comment]
$ thrift --version
Thrift version 0.13.0

**Comment by manlge** [comment]
Without go mod

**# get thrift 0.13.0
go get github.com/apache/thrift
cd $GOPATH/src/github.com/apache/thrift
git checkout 0.13.0**

mkdir -p $GOPATH/src/iotdb-client-go-example/session_example
cd $GOPATH/src/iotdb-client-go-example/session_example

curl -o session_example.go -L https://github.com/apache/iotdb-client-go/raw/main/example/session_example.go
go run session_example.go

**Comment by Guoyuechuan** [comment]
Problem solved. Thanks a lot. But leaving a comment in the example will be helpful.
