### ISSUE TITLE
使用0.12.0版本session客户端，插入数据报类找不到错误，jar包里确实没这个类

### ISSUE THREAD

**Issue by zhouzhiy** [apache/iotdb#3119]
Caused by: java.lang.ClassNotFoundException: org.apache.iotdb.rpc.RedirectException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by jixuan1989** [comment]
normally it is caused that you do not import all dependencies..

We suggest you use maven to manage the dependencies:

```
        <dependency>
            <groupId>org.apache.iotdb</groupId>
            <artifactId>iotdb-session</artifactId>
            <version>0.12.0</version>
        </dependency>

```  

这一般都是没有使用maven或者其他依赖管理工具，而是自己手动仅导入了session一个jar包导致的。 建议使用maven管理依赖，如上所示。

否则，可以通过编译源码生成 with-dependencies的依赖包，这样的话导入一个jar包即可。
由于with-dependencies 的依赖包无法从网上的maven仓库下载， 目前只能手动编译：

`mvn package -pl session -am -P get-jar-with-dependencies`，

之后在session的target目录下就有以`with-dependencies.jar`结尾的jar包了。


另，如果手动逐一导入jar包，则列表为：

```
[INFO] --- maven-dependency-plugin:3.1.1:list (default-cli) @ iotdb-session ---
[INFO]
[INFO] The following files have been resolved:
[INFO]    org.apache.iotdb:service-rpc:jar:<YOUR VERSION>:compile
[INFO]    org.apache.iotdb:tsfile:jar:<YOUR VERSION>:compile
[INFO]    org.apache.iotdb:iotdb-thrift:jar:<YOUR VERSION>:compile
[INFO]    org.apache.thrift:libthrift:jar:0.13.0:compile
[INFO]    javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO]    org.xerial.snappy:snappy-java:jar:1.1.8.4:compile
```

**Comment by zhouzhiy** [comment]
> normally it is caused that you do not import all dependencies..
> 
> We suggest you use maven to manage the dependencies:
> 
> ```
>         <dependency>
>             <groupId>org.apache.iotdb</groupId>
>             <artifactId>iotdb-session</artifactId>
>             <version>0.12.0</version>
>         </dependency>
> ```
> 
> 这一般都是没有使用maven或者其他依赖管理工具，而是自己手动仅导入了session一个jar包导致的。 建议使用maven管理依赖，如上所示。
> 
> 否则，可以通过编译源码生成 with-dependencies的依赖包，这样的话导入一个jar包即可。
> 由于with-dependencies 的依赖包无法从网上的maven仓库下载， 目前只能手动编译：
> 
> `mvn package -pl session -am -P get-jar-with-dependencies`，
> 
> 之后在session的target目录下就有以`with-dependencies.jar`结尾的jar包了。
> 
> 另，如果手动逐一导入jar包，则列表为：
> 
> ```
> [INFO] --- maven-dependency-plugin:3.1.1:list (default-cli) @ iotdb-session ---
> [INFO]
> [INFO] The following files have been resolved:
> [INFO]    org.apache.iotdb:service-rpc:jar:<YOUR VERSION>:compile
> [INFO]    org.apache.iotdb:tsfile:jar:<YOUR VERSION>:compile
> [INFO]    org.apache.iotdb:iotdb-thrift:jar:<YOUR VERSION>:compile
> [INFO]    org.apache.thrift:libthrift:jar:0.13.0:compile
> [INFO]    javax.annotation:javax.annotation-api:jar:1.3.2:compile
> [INFO]    org.xerial.snappy:snappy-java:jar:1.1.8.4:compile
> ```

谢谢，我是用maven管理依赖的，问题解决了，原因是之前我用的0.11.2的版本，后来改成了0.12.0版本，没有update,依赖中的service-rpc版本还是0.11.2版本的，导致没找到org.apache.iotdb.rpc.RedirectException这个类。
