### ISSUE TITLE
Replace the dependence repository Bintray with JFrog

### ISSUE THREAD

**Issue by HTHou** [apache/iotdb#3132]
Since the Bintray repository is no long available, see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter, we need to update the related dependence download urls.

**Comment by jixuan1989** [comment]
change moqutte to :
        <dependency>
            <groupId>de.fraunhofer.iosb.io.moquette</groupId>
            <artifactId>moquette-broker</artifactId>
            <version>0.14.3</version>
        </dependency>

it is the same with the moqutte on Bintray.

**Comment by HTHou** [comment]
Fixed
