### ISSUE TITLE
UDTF not work in cluster mode.

### ISSUE THREAD

**Issue by irvine0109** [apache/iotdb#3147]
**Describe the bug**

UDTF not work in cluster mode.  

MUST set `default_replica_num=1` to reproduce this bug.  

**To Reproduce**

1. Set `default_replica_num=1` in file `iotdb-cluster.properties`.
2. Start 3 nodes.
3. Start cli and generate random data.
3. On one node, UDTF work.
4. On other two nodes, UDTF don't work.  

**Screenshots**

Node with port 6668, `sin(s1)` can work.
![work](https://user-images.githubusercontent.com/67060864/117532200-fde0bd80-b018-11eb-94b0-826fd4f6cba4.png)

Node with port 6669, `sin(s1)` not work. BTW, `select s1` and `sum(s1)` are working well.
![not work](https://user-images.githubusercontent.com/67060864/117532203-02a57180-b019-11eb-9095-7645d149a275.png)

**Desktop (please complete the following information):**

 - Version 0.12.1

**Comment by SteveYurongSu** [comment]
Hi, UDF now works in cluster mode (master & rel/0.12). 

You can pull the latest code, build and try!

For more detail, see PR #3503 and PR #3565 😊
