### ISSUE TITLE
权限异常

### ISSUE THREAD

**Issue by juice411** [apache/iotdb#3166]
使用的版本是0.11.4，前天更新的
1.root 用户创建了root.sg1存储组
2.root 用户创建了test用户
3.赋予test用户SET_STORAGE_GROUP INSERT_TIMESERIES READ_TIMESERIES 共3个权限 在root.sg1.dtxy路径
4.用test用户调checkTimeseriesExists，createMultiTimeseries等操作，报没有权限

**Comment by SteveYurongSu** [comment]
抱歉，文档存在描述缺失。
createMultiTimeseries还需要`CREATE_TIMESERIES`权限。
checkTimeseriesExists的执行应该没有问题。

**Comment by SteveYurongSu** [comment]
文档已经在0.11，0.12和master上修复，如果还有进一步问题，可以提新issue :D @juice411
