### ISSUE TITLE
Cannot get the jar-with-dependencies as the Zepplin-IoTDB UserGuide says

### ISSUE THREAD

**Issue by LeiRui** [apache/iotdb#3212]
**Describe the bug**
[The Zepplin-IoTDB UserGuide](https://iotdb.apache.org/UserGuide/Master/Ecosystem%20Integration/Zeppelin-IoTDB.html) says that after running `mvn clean package -pl zeppelin-interpreter -am -DskipTests`, the jar-with-dependencies will appear. But I cannot get the jar-with-dependencies.

**Screenshots**

- The Zepplin-IoTDB UserGuide:

![image](https://user-images.githubusercontent.com/33376433/118519693-ed90b700-b76b-11eb-911d-7f58975fc586.png)

- What I got:

![image](https://user-images.githubusercontent.com/33376433/118519862-144eed80-b76c-11eb-8e29-d458aa63ee22.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: Master

**Comment by HTHou** [comment]
Try to add `-P get-jar-with-dependencies`?

**Comment by LeiRui** [comment]
> Try to add `-P get-jar-with-dependencies`?

Wow it works. Thanks.
