### ISSUE TITLE
Can the query support fuzzy matching?

### ISSUE THREAD

**Issue by DongJigong** [apache/iotdb#3248]
**Is your feature request related to a problem? Please describe.**
`select * from root.log where time > 2021-05-10 12:00:00 and data contains 'abc'`
**Describe the solution you'd like**

  I want query sql can support fuzzy matching like mysql like '%abc%'

**Describe alternatives you've considered**

**Additional context**

**Comment by HTHou** [comment]
Hi, this issue is already fixed by the following PR.
- https://github.com/apache/iotdb/pull/3649
https://github.com/apache/iotdb/pull/3738
