### ISSUE TITLE
将大的用户文档（比如DDL，DML）拆分成若干个小的文档

### ISSUE THREAD

**Issue by SteveYurongSu** [apache/iotdb#3285]
我们官网的某些用户文档十分地长，而且没有二级标题索引，这直接导致很多文档没办法方便地找到。
![image](https://user-images.githubusercontent.com/30497621/119942880-e74cd700-bfc4-11eb-82de-9f83e19dc120.png)

比如，对于DML文档，我们可以将它拆分成：
1. 数据写入
2. 原始查询
3. 聚合查询
4. Group By 查询
5. 最新点查询
……

这样在搜索中也可以更方便地查找。

**Comment by liujiajun** [comment]
I can take this if no ones taking

**Comment by SteveYurongSu** [comment]
> I can take this if no ones taking

Great! Welcome!

**Comment by HTHou** [comment]
Seems the same issue like #2490

**Comment by liujiajun** [comment]
One alternative is a one-line config change to VuePress to achieve the result below:

![tmp](https://user-images.githubusercontent.com/2803108/120336733-38422f80-c325-11eb-86c1-6df8fcf0ae5e.gif)

If this is ok, we can further change the sub headers to make them more descriptive. Why do you guys think?

**Comment by SteveYurongSu** [comment]
> One alternative is a one-line config change to VuePress to achieve the result below:
> 
> ![tmp](https://user-images.githubusercontent.com/2803108/120336733-38422f80-c325-11eb-86c1-6df8fcf0ae5e.gif)
> 
> If this is ok, we can further change the sub headers to make them more descriptive. Why do you guys think?

WOW! I think that's the best way! We've always wanted to display multiple subtitles on our web pages, but we couldn't find a way to do that!
