### ISSUE TITLE
Compile c++ client on "Tools: Thrift" FAILE

### ISSUE THREAD

**Issue by haozewu** [apache/iotdb#3315]
**Describe the bug**
Use VS2013 Ultimate to compile client-cpp and cpp example, but failed.

![image](https://user-images.githubusercontent.com/20966439/120467578-e5bf4c80-c3d2-11eb-9762-27a7bdbe6a1f.png)

**To Reproduce**
1. Install VS2013 with C++ packages.
2. Download the latest release version iotDB source file.
3. Install flex, bison and compile boost.
4. cd compile-tools then run
```
mvn package -D"boost.include.dir"=" C:\x\boost_1_76_0" -D"boost.library.dir"="C:\x\boost_1_76_0\stage\lib" -D"cmake.generator"="Visual Studio 12 2013 Win64" -DskipTests
```
5. cd thrift, and other thrift* folder to compile with command above.
6. Compile client-cpp with command
```
mvn package -P compile-cpp -pl example/client-cpp-example -am -D"boost.include.dir"=" C:\x\boost_1_76_0" -D"boost.library.dir"="C:\x\boost_1_76_0\stage\lib" -D"cmake.generator"="Visual Studio 12 2013 Win64" -DskipTest
```
```
[ERROR] Failed to execute goal com.googlecode.cmake-maven-project:cmake-maven-plugin:3.7.2-b1:generate (cmake-generate) on project client-cpp-tools-thrift: Return code: 1 -> [Help 1]
```

**Expected behavior**
Compile SUCCEED

**Screenshots**
Above.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser no relation
 - Version 0.12.0

**Additional context**

**Comment by haozewu** [comment]
Now I change msvc to vs2019, but still have error.
Error log looks like this:
```
[INFO] Using local binaries
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- Configuring thrift 0.13.0
-- Setting C++11 as the default language level.
-- To specify a different C++ language level, set CMAKE_CXX_STANDARD
-- libevent NOT found.
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
```
**Now I think the default thrift compile process make this error because of lacking in libevent and don't find libevent\*.lib in iotdb0.12.0 folder.**
I find the config in `C:\x\iotdb-0.12.0\compile-tools\thrift\target\thrift-0.13.0\lib\cpp\3rdparty.props`
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <BOOST_ROOT>$(THIRD_PARTY)\boost\boost_1_47_0</BOOST_ROOT>
    <OPENSSL_ROOT_DIR>$(THIRD_PARTY)\openssl\OpenSSL-Win32</OPENSSL_ROOT_DIR>
    <LIBEVENT_ROOT>$(THIRD_PARTY)\libevent-2.0.21-stable</LIBEVENT_ROOT>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup>
    <BuildMacro Include="BOOST_ROOT">
      <Value>$(BOOST_ROOT)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="OPENSSL_ROOT_DIR">
      <Value>$(OPENSSL_ROOT_DIR)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="LIBEVENT_ROOT">
      <Value>$(LIBEVENT_ROOT)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
  </ItemGroup>
</Project>
```
**This $(LIBEVENT_ROOT) seems defined in thrift compile process, now I don't know how to change it to the folder which I compiled libevent because it's a temp value.**
There's also a bat file related to libevent in `C:\x\iotdb-0.12.0\compile-tools\thrift\target\thrift-0.13.0\build\appveyor\build-libevent.bat`. The content is
```
SETLOCAL EnableDelayedExpansion

SET URLFILE=libevent-%LIBEVENT_VERSION%-stable.tar.gz
SET URL=https://github.com/libevent/libevent/releases/download/release-%LIBEVENT_VERSION%-stable/%URLFILE%

:: Download - support running a local build or a build in appveyor
CD "%WIN3P%"                                     || EXIT /B
IF "%APPVEYOR_BUILD_ID%" == "" (
    curl -L -f -o "%URLFILE%" "%URL%"
) ELSE (
    appveyor DownloadFile "%URL%"
)
7z x "%URLFILE%" -so | 7z x -si -ttar > nul      || EXIT /B
CD "libevent-%LIBEVENT_VERSION%-stable"          || EXIT /B
nmake -f Makefile.nmake static_libs              || EXIT /B

:: in libevent 2.0 there is no nmake subdirectory in WIN32-Code, but in 2.1 there is
mkdir lib                                        || EXIT /B
move *.lib lib\                                  || EXIT /B
move WIN32-Code\event2\* include\event2\         || move WIN32-Code\nmake\event2\* include\event2\ || EXIT /B
move *.h include\                                || EXIT /B

ENDLOCAL
```
This content exec failed or don't exec at all. **So do anyone know how to exec this batch file or how to use libevent\*.lib and \*.h file to skip this error?**

**Comment by haozewu** [comment]
I skip the default compile process with maven, succeed to compile thrift with all dependencies.

But I also find some config not set correctly in thrift 0.13.0 by default.

**So, it might be not a good idea to take the thrift compile process in this project. So why not just presume developer already compile thrift successfully?**

Just let developer move the thrift include & lib path to a certain place.

**Comment by haozewu** [comment]
![image](https://user-images.githubusercontent.com/20966439/126598234-0f1fc5f6-1c17-4f99-be91-0aea6b3ed130.png)

windows编译thrift时提示 “echo，系统找不到此程序”

**Comment by haozewu** [comment]
> ![image](https://user-images.githubusercontent.com/20966439/126598234-0f1fc5f6-1c17-4f99-be91-0aea6b3ed130.png)
> 
> windows编译thrift时提示 “echo，系统找不到此程序”

我注释了这个echo，提示了新错误：

apache-iotdb-0.12.1\compile-tools\thrift\target\thrift-0.14.1\lib\cpp\src\thrift\transport\TWebSocketServer.cpp(24,10): fatal error C1083: 无法打开包括文件: “openssl/bio.h”: No such file or directory [C:\Users\xxx\Downloads\apache-iotdb-0.12.1\compile-tools\thrift\target\build\lib\cpp\thrift.vcxproj]

**Comment by jixuan1989** [comment]
Hi,

we may need to add parameters to allow users skip compiling Thrift and
Boostrap.

haoze ***@***.***> 于2021年7月22日周四 下午3:10写道：

**Comment by HTHou** [comment]
Hi, 问题看起来跟这个是类似的，可以试试里面说的方法？
https://github.com/apache/iotdb/discussions/4652

**Comment by HTHou** [comment]
fixed

**Comment by krishnpriya** [comment]
How this issue has been fixed? The above language I am not able to understand. I am also facing the same issue.
