### ISSUE TITLE
Implement regex matching operator

### ISSUE THREAD

**Issue by liujiajun** [apache/iotdb#3362]
As requested in https://issues.apache.org/jira/browse/IOTDB-1175

I propose a new grammar `select ... from ... where A matches REGEX_EXPERSSION`, where `A` must be a `TEXT` measurement and `REGEX_EXPERSSION` a string literal.

The grammar is in line with that of the `IN` operator.

I will work on this feature and appreciate any feedback on the proposed grammar

**Comment by SteveYurongSu** [comment]
@liujiajun Nice to see you here again! ❤️

Several points need to be considered:
1. What are the grammers in other db systems? Which grammer is better? Why?
2. We have already implemented a user-defined function called `STRING_CONTAINS` (see https://iotdb.apache.org/UserGuide/Master/IoTDB-SQL-Language/DML-Data-Manipulation-Language.html#string-processing-functions). Can those udf operators be reused in `where` clauses?

**Comment by SteveYurongSu** [comment]
#3248 is similar. You can take a look. :D

**Comment by liujiajun** [comment]
@SteveYurongSu Thanks and it's been great to be able contribute to IoTDB!
I will take note of the issues you mentioned and revise the design accordingly

**Comment by liujiajun** [comment]
I am putting design docs here temporarily: https://www.notion.so/IoTDB-Regex-a14cf476cde14c4c82a62f8c822bca98 

Feel free to make any suggestions! I can move this to confluence once we have a more mature proposal.

**Comment by HTHou** [comment]
Hi, I think this issue already fixed by the following PR. :>
- https://github.com/apache/iotdb/pull/3649
https://github.com/apache/iotdb/pull/3738
