### ISSUE TITLE
接入skywalking【Access skywalking】

### ISSUE THREAD

**Issue by hermeshephaestus** [apache/iotdb#3414]
现在的生态还是基于java为主,建议接入skywalking这种链路追踪，可以用于性能诊断以及问题排查 

The current ecology is still based on java. It is recommended to connect to skywalking link tracking, which can be used for performance diagnosis and troubleshooting.

**Comment by caszhou** [comment]
same need for me

**Comment by HTHou** [comment]
Hi, the latest version of skywalking has supported. 
https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-storage/#iotdb
