### ISSUE TITLE
Disable align in the query not work, when use session pool in java

### ISSUE THREAD

**Issue by caszhou** [apache/iotdb#3449]
**Describe the bug**
Disable algin in the query not work, when use session pool in java.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

MacOS 11.4
IoTDB 0.12.1

**Additional context**

<img width="1539" alt="2" src="https://user-images.githubusercontent.com/16935178/123254571-67615080-d521-11eb-80a9-81338a3b505d.png">
<img width="1881" alt="1" src="https://user-images.githubusercontent.com/16935178/123254581-69c3aa80-d521-11eb-8ace-08e16711f7b0.png">

**Comment by HTHou** [comment]
Hi, this feature is under developing. See https://github.com/apache/iotdb/issues/2770 .

**Comment by caszhou** [comment]
ok, waiting for release.
