### ISSUE TITLE
Bug: Load configuration command with null error message

### ISSUE THREAD

**Issue by Alima777** [apache/iotdb#3458]
Version: 0.12.1

Client log:
![image](https://user-images.githubusercontent.com/34242296/123568335-aaa81180-d7f6-11eb-91d3-6a485da18e7f.png)

Server log:

![image](https://user-images.githubusercontent.com/34242296/123568284-9532e780-d7f6-11eb-8080-fbc06118bf93.png)

**Comment by Alima777** [comment]
Command: Load configuration

It may be caused by the configurations in iotdb-engine.properties are annotated now.

**Comment by ijihang** [comment]
The cause may be ：org.apache.iotdb.db.conf.IoTDBDescriptor
![image](https://user-images.githubusercontent.com/55303647/124213527-5026f200-db23-11eb-921e-0240e83f01f3.png)
