### ISSUE TITLE
One NPE in UDTFDataSet.java

### ISSUE THREAD

**Issue by containerAnalyzer** [apache/iotdb#3482]
Hello,
Our static analyzer found a following potential NPE. We have checked the feasibility of this execution trace. It is necessary to defend this vulnerability to improve the code quality.

1. Select the true branch at this point (instanceof<org.apache.iotdb.db.query.expression.unary.TimeSeriesOperand>(expression)==0 is true). Function add executes and paths constains null
https://github.com/apache/iotdb/blob/8b1ee93c51932d72cb7fd7c5268f40f7b3a74f25/server/src/main/java/org/apache/iotdb/db/query/expression/unary/FunctionExpression.java#L170-L173

2. Program reaches the return point, and returns paths, which contains null
https://github.com/apache/iotdb/blob/8b1ee93c51932d72cb7fd7c5268f40f7b3a74f25/server/src/main/java/org/apache/iotdb/db/query/expression/unary/FunctionExpression.java#L176

3. Function getPaths executes and stores the return value to paths (paths can be null)
https://github.com/apache/iotdb/blob/8b1ee93c51932d72cb7fd7c5268f40f7b3a74f25/server/src/main/java/org/apache/iotdb/db/query/dataset/UDTFDataSet.java#L166

4. Function get executes and returns
https://github.com/apache/iotdb/blob/8b1ee93c51932d72cb7fd7c5268f40f7b3a74f25/server/src/main/java/org/apache/iotdb/db/query/dataset/UDTFDataSet.java#L169

5. The return value of function get is passed as the this pointer to function getFullPath (the return value of function get can be null), which will leak to null pointer dereference
https://github.com/apache/iotdb/blob/8b1ee93c51932d72cb7fd7c5268f40f7b3a74f25/server/src/main/java/org/apache/iotdb/db/query/dataset/UDTFDataSet.java#L169

Commit: 8b1ee93c51932d72cb7fd7c5268f40f7b3a74f25

ContainerAnalyzer

**Comment by SteveYurongSu** [comment]
This is a correct discovery. An NPE can be triggered by executing a nested query in the CLI that is syntactically supported (but not supported on the user's documentation, the nested query is WIP). 

example:
select sin(sin(s1)) from root.sg1.d1

Currently, we use `paths.get(i).getFullPath()` to get a reader index of a udtf plan, which may cause a NPE. After introducing nested query, we will use the column name to get the reader index, and all `paths` will be replaced by `columns` (we are doing the cleaning), at that time, there will be no NPEs.

Thanks for the discovery!

**Comment by containerAnalyzer** [comment]
Thank you for your confirmation.
