### ISSUE TITLE
schemaless 

### ISSUE THREAD

**Issue by siaron** [apache/iotdb#3506]
现在iotdb写入的需要提前定义schema. 之前听说有支持写入时不需要提前定义schema这个功能. 目前有什么资料或例子吗?

**Comment by HTHou** [comment]
> 现在iotdb写入的需要提前定义schema. 之前听说有支持写入时不需要提前定义schema这个功能. 目前有什么资料或例子吗?

官网文档有一些关于自动推断类型的配置参数说明
https://iotdb.apache.org/zh/UserGuide/Master/Appendix/Config-Manual.html#数据类型自动推断

具体使用方法就是直接插入数据即可，不需要提前create timeseries。
