### ISSUE TITLE
The problem when using spotless under windows

### ISSUE THREAD

**Issue by THUMarkLau** [apache/iotdb#3739]
The current IoTDB code style specification uses the spotless plug-in for management, but under Unix-like systems (MacOS, Linux), the line break for text files is \n (which is named LF), while under Dos-style systems (Windows), the line break is \r\n(which is named CRLF). More detail information of the difference between LF and CRLF is [here](https://blog.csdn.net/lishuoboy/article/details/84768748). Therefore, after using spotless formatting code under Windows, the line breaks of all code files will be replaced. This causes all code files in git to be modified, and each commit will commit all files. This will not only increase the size of the .git directory, but also make commands such as git diff unusable (because every line of all files has been modified), and it is impossible to see which files a PR has modified when viewing the modified content of the PR. 

当前的 IoTDB 代码风格规范使用 spotless 插件进行管理，但是在类 Unix 系统（MacOS、Linux）下，文本文件的换行符是 \n（被称为 LF），而 Dos 风格的系统（Windows）下换行符是 \r\n （被称为 CRLF）。更多关于 LF 和 CRLF 的信息可以查看[这篇文章](https://blog.csdn.net/lishuoboy/article/details/84768748)。因此，在 Windows 下使用 spotless 格式化代码后，会将所有代码文件的换行符进行替换。这就导致在 git 中所有的代码文件都被修改，每次提交都会提交所有文件（因为所有文件的每一行的结尾都被修改了）。这不仅会增加 .git 文件的大小，还会使得 git diff 等命令无法使用，在查看 PR 的修改内容是也无法看出一个 PR 到底修改了哪些文件。

![微信截图_20210813204519](https://user-images.githubusercontent.com/37140360/129374303-94e51055-2d5e-4896-a16a-941423af78fc.png)

**Comment by HTHou** [comment]
See this PR https://github.com/apache/iotdb/pull/3585, there is a comment solved this problem.

**Comment by HTHou** [comment]
I found another article to solve this problem.
http://mail-archives.apache.org/mod_mbox/geode-dev/201611.mbox/%3C8a1282bb-a63a-6a06-9d1d-ddaf08e0cde7@pivotal.io%3E
