### ISSUE TITLE
How to insert " and ' in one sentence of sql at the same time?

### ISSUE THREAD

**Issue by limeng32** [apache/iotdb#3774]
We know that single quotation marks (') can be inserted in double quotation marks, and double quotation marks (") can be inserted in single quotation marks. However, if an indicator has both single quotation marks (') and double quotation marks (") in the same time, how to insert it?

**Comment by Alima777** [comment]
Can you give one example?

**Comment by limeng32** [comment]
I can Use:
insert into root.ln.wf01.wt01 (timestamp,asd) values(now()," ' ");
To add a single quote record, I can also use:
insert into root.ln.wf01.wt01 (timestamp,asd) values(now(),' " ');
To add a double quote record, but I can’t add a record with both single quotes and double quotes, because there is no escape mechanism;
