### ISSUE TITLE
Hope fuzzy query could support multi-device

### ISSUE THREAD

**Issue by LIU-WEI-git** [apache/iotdb#3945]
I find the fuzzy query of IoTDB doesn't support multi device.  Hope it can be supported in the future.

In my scenario, I store the value of the index as LayerName to index some fields. For example, there is a table called service_traffic. It has 4 fields: id, type, group, name. I make the value of id, type and name as part of the storage path to achieve the effect of index. Eventually the data from the same table is spread across multiple devices.

When I used `like` clause to fuzzy query, I got a Exception: `Msg: 500: [INTERNAL_SERVER_ERROR] Exception occurred while executing "select * from root.skywalking.service_traffic.*."0".* where name like '%1%'". class org.apache.iotdb.db.qp.logical.crud.LikeOperator cannot be cast to class org.apache.iotdb.db.qp.logical.crud.BasicFunctionOperator (org.apache.iotdb.db.qp.logical.crud.LikeOperator and org.apache.iotdb.db.qp.logical.crud.BasicFunctionOperator are in unnamed module of loader 'app')`

In debug mode, I found the Exception occurred on [ConcatPathOptimizer](https://github.com/apache/iotdb/blob/489a51c486c46d2d32bc2bc10dfc35f9394f8aae/server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java#L308). The LikeOperator cannot be cast to BasicFunctionOperator.

![image](https://user-images.githubusercontent.com/51618159/132941220-c77b1ac7-13df-42f5-b3e9-538369858dc8.png)

OS: Win10, Version: 0.12.2

**Comment by HTHou** [comment]
@ijihang Any idea about this issue?

**Comment by ijihang** [comment]
Ok,I'll implement this function right away

**Comment by HTHou** [comment]
@LIU-WEI-git The latest rel/0.12 fixed this issue. You can try it now.

**Comment by LIU-WEI-git** [comment]
wow~, thanks a lot. : )
