### ISSUE TITLE
order by time asc can't work, is that a bug?

### ISSUE THREAD

**Issue by ntcat** [apache/iotdb#4028]
select last(s9) from root.cj2.jr*.result order by time desc 

this can work right.

select last(s9) from root.cj2.jr*.result order by time asc

this can't work right.

**Comment by ntcat** [comment]
select last(s9) from root.cj2.jr*.result order by time

**Comment by ntcat** [comment]
select last(s9) from root.cj2.jr*.result order by time
also can't work right, it means, data is shown in a wrong order, but desc do well.

**Comment by qiaojialin** [comment]
please add my wechat: qiaojialin1993

**Comment by HTHou** [comment]
The bug should have be fixed by newer version. Please try it and I'll close this issue.
