### ISSUE TITLE
Url of 'Get started quickly' is incorrect

### ISSUE THREAD

**Issue by Plutooooooo** [apache/iotdb#4314]
**Describe the bug**
The url of "Get started quickly" in file ContributeGuide.md is incorrect.

**To Reproduce**
1. Go to iotdb/docs/Development/ContributeGuide.md
2. Click on 'Main link->Get started quickly'(http://iotdb.apache.org/UserGuide/master/Get%20Started/QuickStart.html)

**Expected behavior**
Got user guide page instead of 'Not Found'

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser: chrome(95.0.4638.69)
 - Version: latest

**Comment by HTHou** [comment]
Nice catch, would you like to submit a PR to fix it?

**Comment by jenna25** [comment]
I want to do this
