### ISSUE TITLE
12.3集群版数据插入报错

### ISSUE THREAD

**Issue by shiritoshiro** [apache/iotdb#4561]
开发语言是java，jdk版本1.8，连接方式是session，插入方式insertbyrecords，自动创建时间序列。
当session依赖版本为0.12.3时报错
![QQ图片20211213163538](https://user-images.githubusercontent.com/74188141/145778953-2f98b3fb-597d-4da0-be6d-d3887fac6c03.jpg)
但数据可以正常插入，session依赖改为0.12.2报错消失

**Comment by luanshidujun** [comment]
12.3删除集群分组也是报这个错，实际分组已经删除成功

**Comment by LebronAl** [comment]
目前需要设置每个节点配置中 iotdb-engine.properties 的 rpc_address 为 iotdb-cluster.properties 的 internal_ip。可以尝试一下~

**Comment by luanshidujun** [comment]
> 需要设置每个节点配置中 iotdb-engine.properties 的 rpc_address 为 iotdb-cluster.properties 的 internal_ip。可以试一下~

果然可以

**Comment by LebronAl** [comment]
最近的 0.12.4 版本即使忘记配置 rpc_address 也不会再报此错误了~

**Comment by shiritoshiro** [comment]
谢谢，因为在群里面找到了解决方法就没有关注git，谢谢回复
