### ISSUE TITLE
Grafana-IoTDB java.sql.SQLException if IOTDB version > 0.12.2

### ISSUE THREAD

**Issue by IOjeffrey** [apache/iotdb#4637]
Hello,

The Grafana-IoTDB worked in version 0.12.2. But for both **0.12.3** and **0.12.4** it isn't working anymore as Grafana gets no results and the Grafana-IoTDB java application reports errors.

I attached the output of the application log:
[debug_log.txt](https://github.com/apache/iotdb/files/7777312/debug_log.txt)

This situation is reproducible in at least the following conditions:
- Use of the official Docker images: apache/iotdb:0.12.4-grafana
- Use of the official installation procedure as stated on https://iotdb.apache.org/UserGuide/Master/Ecosystem%20Integration/Grafana.html#grafana-iotdb (Option two)

Manual querying iotdb with the cli shows the data without any problems. Please note for all tests; I used identical versions of IoTDB and the Grafana-IoTDB. When switching back to 0.12.2 everything starts working again in Grafana.

Please let me know if I can supply you with any more information. This is my first post, so please forgive me if this report isn't correctly formatted.

Cheers,

Jeffrey

**Comment by SteveYurongSu** [comment]
Hi Jeffrey, thanks for reporting this! 

I found this in the log:

```shell
Caused by: java.sql.SQLException: Does not support setReadOnly
        at org.apache.iotdb.jdbc.IoTDBConnection.setReadOnly(IoTDBConnection.java:319) ~[iotdb-jdbc-0.12.4.jar!/:0.12.4]
        at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:372) ~[HikariCP-2.5.1.jar!/:na]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:346) ~[HikariCP-2.5.1.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506) ~[HikariCP-2.5.1.jar!/:na]
        ... 74 common frames omitted
```

Has the method `setReadOnly` ever been called by your application? The method is not supported by the `IoTDBConnection`. 

The IoTDB will automatically set the status to ReadOnly only in the event of a system failure. In other cases, we should not set the system state to read-only.

**Comment by IOjeffrey** [comment]
Hello Steve,

"My" application is Grafana 8.3.3. My setup consists of three Docker containers:

1. apache/iotdb:0.12.4-node
2. apache/iotdb:0.12.4-grafana (or as stated before [my own Option 2 iotdb-grafana installation](https://github.com/promouseus/open-field_time-series/blob/main/iotdb-grafana/Dockerfile))
3. [grafana/grafana:latest based container](https://github.com/promouseus/open-field_time-series/blob/main/grafana/Dockerfile) with the [data source configured](https://github.com/promouseus/open-field_time-series/blob/main/grafana/iotdb.yaml)

For testing I add some time-series with a bash script like this:
```
iotdbCli='docker exec -it iotdb /iotdb/sbin/start-cli.sh -h 127.0.0.1 -p 6667 -u root -pw root'
${iotdbCli} -e "set storage group to root.sentico"
${iotdbCli} -e "CREATE TIMESERIES root.sentico.portal.ipv4.\"10.20.20.254\".rtt WITH DATATYPE=FLOAT, ENCODING=RLE"
${iotdbCli} -e "CREATE TIMESERIES root.sentico.portal.ipv4.\"1.1.1.1\".rtt WITH DATATYPE=FLOAT, ENCODING=RLE"
```

And I create some data by running the following bash script a couple of times:
```
timestamp=`date +%s%3N`
rtt1=`ping 8.8.8.8 -qc1|tail -n 1|awk -F' ' '{print $4}'|awk -F'/' '{print $1}'`
rtt2=`ping 1.1.1.1 -qc1|tail -n 1|awk -F' ' '{print $4}'|awk -F'/' '{print $1}'`

${iotdbCli} -e "INSERT INTO root.sentico.portal.ipv4.\"10.20.20.254\"(timestamp,rtt) values(${timestamp},${rtt1})"
${iotdbCli} -e "INSERT INTO root.sentico.portal.ipv4.\"1.1.1.1\"(timestamp,rtt) values(${timestamp},${rtt2})"
```

Doing above for 0.12.3 and 0.12.4 results in the log file as supplied. If I leave container 1 (iotdb-node) and 3 (grafana) in tact and only change container 2 (iotdb-grafana) back to 0.12.2 everything is working immediately. So the problem seems isolated to the iotdb-grafana 0.12.3 and 0.12.4 version. For now I use iotdb-node 0.12.4 combined with iotdb-grafana 0.12.2 and that seems to work (at least in my basic tests).

If you need any more information or I can assist you with something, please let me know.

Cheers,

Jeffrey

**Comment by SteveYurongSu** [comment]
Hi @IOjeffrey , thanks for your detailed report again :D

We have checked and reproduced the bug, it was caused by the upgrade of the SprintBoot. Simply downgrading the version of SpringBoot to 1.5.15 can fix the issue. We will submit a PR ASAP.

**Comment by SteveYurongSu** [comment]
Hi, we have fixed the issue. You may pull the latest rel/0.12 code and try again. Enjoy :D
