### ISSUE TITLE
[iotdb-0.13.0-SNAPSHOT,Grafana-v8.2.0]聚合查询异常

### ISSUE THREAD

**Issue by sureychen** [apache/iotdb#4651]
**Describe the bug**
聚合查询一个未创建的时间序列，查询失败，Grafana报错“the result is not object”

**To Reproduce**
1. 指定一个未创建的时间序列
2. 使用聚合函数对其进行查询
3. 数据库查询结果显示“无数据”，grafana拿不到数据报错“the result is not object”

**Expected behavior**
希望对这种情形的聚合查询有相应的处理，比如返回结果0，这样Grafana就可以正常显示查询结果

**Screenshots**
![1](https://user-images.githubusercontent.com/38009328/147635995-feaf4df1-8b47-47ac-83bf-5a512d8b84b2.png)
![2](https://user-images.githubusercontent.com/38009328/147636050-9f071da8-eb39-4504-9616-18f363fc57b4.png)

**Comment by SteveYurongSu** [comment]
Thanks for reporting this @sureychen.

Please take a look :D @CloudWise-Lukemiao
