### ISSUE TITLE
I pulled the project and use command "mvn clean install -am -DskipTests -Drat.skip=true". I met this problem. The command was ok several days ago.

### ISSUE THREAD

**Issue by ZhanGHanG9991** [apache/iotdb#4715]
![image](https://user-images.githubusercontent.com/34939716/148331362-3f0f8138-8c7f-4c4c-a3a7-593c3bdd0784.png)

**Comment by HTHou** [comment]
Hi, are you using M1 macbook with ARM jdk17?  This PR is trying to fix it.

- https://github.com/apache/iotdb/pull/4714

**Comment by ZhanGHanG9991** [comment]
Yes, I am using M1 but with jdk8
![image](https://user-images.githubusercontent.com/34939716/148336619-9065688d-f52f-47b9-9109-5176b72776e8.png)

**Comment by HTHou** [comment]
> Yes, I am using M1 but with jdk8 !

It's an ARM jdk8, I'm sure it is exactly the same issue.

**Comment by ZhanGHanG9991** [comment]
Thanks! I am waiting for PR. :)

**Comment by HTHou** [comment]
The PR is merged, you can update the code now.

**Comment by ZhanGHanG9991** [comment]
Thanks, it's ok now!
