### ISSUE TITLE
TSFileDescriptor overwrite the config may lead to unexpected state

### ISSUE THREAD

**Issue by ahuazhu** [apache/iotdb#5030]
**Describe the bug**

The method TSFileDescriptor.loadProps() try to load parameters to overwrite the default values.

```
try {
  ....
      conf.setMaxDegreeOfIndexNode(
          Integer.parseInt(
              properties.getProperty(
                  "max_degree_of_index_node", Integer.toString(conf.getMaxDegreeOfIndexNode()))));
      conf.setMaxStringLength(
          Integer.parseInt(
              properties.getProperty(
                  "max_string_length", Integer.toString(conf.getMaxStringLength()))));
      conf.setFloatPrecision(
          Integer.parseInt(
              properties.getProperty(
                  "float_precision", Integer.toString(conf.getFloatPrecision()))));
....
} catch (Exception e) {
      logger.error("Loading settings {} failed", url, e);
} finally {

}
```

1.  The way to fall back to the default value could be improved.
2. Considering if `Integer.parseInt(properties.getProperty("max_string_length", Integer.toString(conf.getMaxStringLength())))` throw `NumberFormatException` , these will lead to the situation: Parameters before  *max_degree_of_index_node* are set correctly, but the successor ones are ignored.  Ignoring and log the unexpected-parameters (fail over) or crash(fail fast) are common practices.

**Comment by qiaojialin** [comment]
Hi, thanks for reporting and fixing this problem! Please add my wechat: qiaojialin1993, I will invite you to our group.
