### ISSUE TITLE
Verify out-of-order bug with the exportCSV tool

### ISSUE THREAD

**Issue by LeiRui** [apache/iotdb#5059]
**Describe the bug**
Export a timeseries using the exportCSV tool and I find there are out-of-order points in the exported csv file.

**To Reproduce**
```
\export-csv.sh -h 127.0.0.1 -p 6667 -u root -pw root -td ./  -q "select RcvTime from root.kobelco.trans.06.1090000506.2400499"
```
And then use Python to find out-of-order points:
```
from matplotlib import pyplot as plt
import pandas as pd
from datetime import datetime

df=pd.read_csv("D:\\dump0.csv")

lastTime=0
for index, row in df.iterrows():
	date_obj = datetime.strptime(row[0],'%Y-%m-%dT%H:%M:%S.%f%z') #2021-03-20T06:54:54.000+08:00
	nowTime = date_obj.timestamp()
	if nowTime < lastTime:
		print("There is a disorder point: lastTime=",lastTime,'nowTime=',nowTime,"or ",date_obj)
	lastTime=nowTime
```
The result is:
> There is a disorder point: lastTime= 1630377791.0 nowTime= 1630376098.0 or  2021-08-31 10:14:58+08:00
There is a disorder point: lastTime= 1630390037.0 nowTime= 1630388697.0 or  2021-08-31 13:44:57+08:00
There is a disorder point: lastTime= 1635551246.0 nowTime= 1632960899.0 or  2021-09-30 08:14:59+08:00

For example (The first column is Time and the second column is Value of root.kobelco.trans.06.1090000506.2400499.RcvTime):
![image](https://user-images.githubusercontent.com/33376433/154063994-7868a1b4-6958-4bc9-9169-b4ac00798aef.png)

**Need verification**
Someone with access to the data refered above can further verfiy this problem. Is it a bug of the exportCSV tool or the query itself?

**Expected behavior**
The exported timeseries is a sequence of points sorted by timestamp in ascending order.

**Comment by HTHou** [comment]
There might be several possible reasons.

1. Bug of CSV Tool. Plz verify it by try to execute the query in CLI to see if the problem exists. 
2. Bug of compaction. You can verify the TsFile that contains the wrong data by `Tracing Tool` and verify the IoTDB version when the TsFile was created. v0.12.2 or v0.12.3 contains such bug...

**Comment by LeiRui** [comment]
> There might be several possible reasons.
> 
> 1. Bug of CSV Tool. Plz verify it by try to execute the query in CLI to see if the problem exists.
> 2. Bug of compaction. You can verify the TsFile that contains the wrong data by `Tracing Tool` and verify the IoTDB version when the TsFile was created. v0.12.2 or v0.12.3 contains such bug...

Good idea, but I don't have access to that data environment. I asked @xiaoyekanren to help me export that data. So someone with access can verify this problem.

**Comment by HTHou** [comment]
Already verified the problem from @xiaoyekanren. The error is caused by the incorrect TsFile, which means it's not related with CSV tool. 
> Good idea, but I don't have access to that data environment. I asked @xiaoyekanren to help me export that data. So someone with access can verify this problem.
