### ISSUE TITLE
Does  Privilege clause support using wildcard (用户权限配置是否支持通配符

### ISSUE THREAD

**Issue by huangdejie** [apache/iotdb#5121]
我创建了很多存储组。如：
```
`set storage group to root.js.nanjing.jiangning;
set storage group to root.js.nanjing.pukou;
set storage group to root.js.suzhou.zhangjiagang;
set storage group to root.js.yangzhou.gaoyou;`
```
现在我想赋予某个用户root.js路径下的存储组的权限该如何操作？
我在IoTDB上进行GRANT USER jsiot PRIVILEGES INSERT_TIMESERIES on root.js.*  操作，但是这样并没有生效

I create a lot of storage groups, e.g.:
```
`set storage group to root.js.nanjing.jiangning;
set storage group to root.js.nanjing.pukou;
set storage group to root.js.suzhou.zhangjiagang;
set storage group to root.js.yangzhou.gaoyou;`
```

Now I want to assgin the privilege of inserting data into timeseries which have prefix "root.js" to some user.
I tried  `GRANT USER jsiot PRIVILEGES INSERT_TIMESERIES on root.js.*` but failed.

**Comment by jixuan1989** [comment]
Currently, IoTDB does not support it.  But this is a very good feature. 
Does someone want to implement it?

**Comment by jixuan1989** [comment]
well, I checked v0.12.4, it works like this:
`GRANT USER jsiot PRIVILEGES 'INSERT_TIMESERIES' on root.js`

**Comment by huangdejie** [comment]
> 好吧，我检查了 v0.12.4，它的工作原理是这样的： `GRANT USER jsiot PRIVILEGES 'INSERT_TIMESERIES' on root.js`
