### ISSUE TITLE
IoTDB依赖包问题

### ISSUE THREAD

**Issue by TimXu0713** [apache/iotdb#5275]
**Describe the bug**
项目原来使用iotdb-session-0.12.4.jar来开发，只需要这一个jar包即可使用java原生session方式操作IoTDB数据库，了解到IoTDB-0.13支持对齐时间序列，而我这边的应用场景比较适合使用对齐时间序列，所以尝试修改项目代码。经测试，0.13使用java session时，需要使用iotdb-session-0.13.0-SNAPSHOT.jar、iotdb-thrift-0.13.0-SNAPSHOT.jar、service-rpc-0.13.0-SNAPSHOT.jar、tsfile-0.13.0-SNAPSHOT.jar、libthrift-0.14.1.jar这５个jar包，运行才不会报找不到类的错。现在的问题是当增加了libthrift-0.14.1.jar包后，springboot运行会卡住，不增加就会报错“Caused by: java.lang.ClassNotFoundException: org.apache.thrift.TEnum”，能帮忙看看是什么问题吗？

**Comment by TimXu0713** [comment]
springboot版本：2.5.6
止住的位置是console打印如下内容后：

> /usr/local/java/jdk1.8.0_321/bin/java -javaagent:/snap/intellij-idea-community/345/lib/idea_rt.jar=38955:/snap/intellij-idea-community/345/bin -Dfile.encoding=UTF-8 -classpath /usr/local/java/jdk1.8.0_321/jre/lib/charsets.jar:/usr/local/java/jdk1.8.0_321/jre/lib/deploy.jar:/usr/local/java/jdk1.8.0_321/jre/lib/ext/cldrdata.jar:/usr/local/java/jdk1.8.0_321/jre/lib/ext/dnsns.jar:/usr/local/java/jdk1.8.0_321/jre/lib/ext/jaccess.jar:/usr/local/java/jdk1.8.0_321/jre/lib/ext/jfxrt.jar:/usr/local/java/jdk1.8.0_321/jre/lib/ext/localedata.jar:/usr/local/java/jdk1.8.0_321/jre/lib/ext/nashorn.jar:/usr/local/java/jdk1.8.0_321/jre/lib/ext/sunec.jar:/usr/local/java/jdk1.8.0_321/jre/lib/ext/sunjce_provider.jar:/usr/local/java/jdk1.8.0_321/jre/lib/ext/sunpkcs11.jar:/usr/local/java/jdk1.8.0_321/jre/lib/ext/zipfs.jar:/usr/local/java/jdk1.8.0_321/jre/lib/javaws.jar:/usr/local/java/jdk1.8.0_321/jre/lib/jce.jar:/usr/local/java/jdk1.8.0_321/jre/lib/jfr.jar:/usr/local/java/jdk1.8.0_321/jre/lib/jfxswt.jar:/usr/local/java/jdk1.8.0_321/jre/lib/jsse.jar:/usr/local/java/jdk1.8.0_321/jre/lib/management-agent.jar:/usr/local/java/jdk1.8.0_321/jre/lib/plugin.jar:/usr/local/java/jdk1.8.0_321/jre/lib/resources.jar:/usr/local/java/jdk1.8.0_321/jre/lib/rt.jar:/workspace/idea/IoTDBService/target/classes:/home/sn0252/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.5.6/spring-boot-starter-web-2.5.6.jar:/home/sn0252/.m2/repository/org/springframework/boot/spring-boot-starter/2.5.6/spring-boot-starter-2.5.6.jar:/home/sn0252/.m2/repository/org/springframework/boot/spring-boot/2.5.6/spring-boot-2.5.6.jar:/home/sn0252/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.5.6/spring-boot-autoconfigure-2.5.6.jar:/home/sn0252/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/home/sn0252/.m2/repository/org/yaml/snakeyaml/1.28/snakeyaml-1.28.jar:/home/sn0252/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.5.6/spring-boot-starter-json-2.5.6.jar:/home/sn0252/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.5/jackson-databind-2.12.5.jar:/home/sn0252/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.5/jackson-annotations-2.12.5.jar:/home/sn0252/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.5/jackson-core-2.12.5.jar:/home/sn0252/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.12.5/jackson-datatype-jdk8-2.12.5.jar:/home/sn0252/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.5/jackson-datatype-jsr310-2.12.5.jar:/home/sn0252/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.12.5/jackson-module-parameter-names-2.12.5.jar:/home/sn0252/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.5.6/spring-boot-starter-tomcat-2.5.6.jar:/home/sn0252/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.54/tomcat-embed-core-9.0.54.jar:/home/sn0252/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.54/tomcat-embed-el-9.0.54.jar:/home/sn0252/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.54/tomcat-embed-websocket-9.0.54.jar:/home/sn0252/.m2/repository/org/springframework/spring-web/5.3.12/spring-web-5.3.12.jar:/home/sn0252/.m2/repository/org/springframework/spring-beans/5.3.12/spring-beans-5.3.12.jar:/home/sn0252/.m2/repository/org/springframework/spring-webmvc/5.3.12/spring-webmvc-5.3.12.jar:/home/sn0252/.m2/repository/org/springframework/spring-aop/5.3.12/spring-aop-5.3.12.jar:/home/sn0252/.m2/repository/org/springframework/spring-context/5.3.12/spring-context-5.3.12.jar:/home/sn0252/.m2/repository/org/springframework/spring-expression/5.3.12/spring-expression-5.3.12.jar:/workspace/idea/IoTDBService/src/main/resources/jar/iotdb-session-0.13.0-SNAPSHOT.jar:/workspace/idea/IoTDBService/src/main/resources/jar/tsfile-0.13.0-SNAPSHOT.jar:/workspace/idea/IoTDBService/src/main/resources/jar/service-rpc-0.13.0-SNAPSHOT.jar:/workspace/idea/IoTDBService/src/main/resources/jar/iotdb-thrift-0.13.0-SNAPSHOT.jar:/home/sn0252/.m2/repository/org/apache/thrift/libthrift/0.16.0/libthrift-0.16.0.jar:/home/sn0252/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/sn0252/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/home/sn0252/.m2/repository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:/home/sn0252/.m2/repository/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar:/home/sn0252/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar:/home/sn0252/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/home/sn0252/.m2/repository/org/springframework/boot/spring-boot-configuration-processor/2.5.6/spring-boot-configuration-processor-2.5.6.jar:/home/sn0252/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.5.6/spring-boot-starter-logging-2.5.6.jar:/home/sn0252/.m2/repository/com/alibaba/fastjson/1.2.79/fastjson-1.2.79.jar:/home/sn0252/.m2/repository/com/google/protobuf/protobuf-java/3.19.4/protobuf-java-3.19.4.jar:/home/sn0252/.m2/repository/org/projectlombok/lombok/1.18.22/lombok-1.18.22.jar:/home/sn0252/.m2/repository/io/springfox/springfox-boot-starter/3.0.0/springfox-boot-starter-3.0.0.jar:/home/sn0252/.m2/repository/io/springfox/springfox-oas/3.0.0/springfox-oas-3.0.0.jar:/home/sn0252/.m2/repository/io/swagger/core/v3/swagger-annotations/2.1.2/swagger-annotations-2.1.2.jar:/home/sn0252/.m2/repository/io/swagger/core/v3/swagger-models/2.1.2/swagger-models-2.1.2.jar:/home/sn0252/.m2/repository/io/springfox/springfox-spi/3.0.0/springfox-spi-3.0.0.jar:/home/sn0252/.m2/repository/io/springfox/springfox-schema/3.0.0/springfox-schema-3.0.0.jar:/home/sn0252/.m2/repository/io/springfox/springfox-core/3.0.0/springfox-core-3.0.0.jar:/home/sn0252/.m2/repository/io/springfox/springfox-spring-web/3.0.0/springfox-spring-web-3.0.0.jar:/home/sn0252/.m2/repository/io/github/classgraph/classgraph/4.8.83/classgraph-4.8.83.jar:/home/sn0252/.m2/repository/io/springfox/springfox-spring-webmvc/3.0.0/springfox-spring-webmvc-3.0.0.jar:/home/sn0252/.m2/repository/io/springfox/springfox-spring-webflux/3.0.0/springfox-spring-webflux-3.0.0.jar:/home/sn0252/.m2/repository/io/springfox/springfox-swagger-common/3.0.0/springfox-swagger-common-3.0.0.jar:/home/sn0252/.m2/repository/org/mapstruct/mapstruct/1.3.1.Final/mapstruct-1.3.1.Final.jar:/home/sn0252/.m2/repository/io/springfox/springfox-data-rest/3.0.0/springfox-data-rest-3.0.0.jar:/home/sn0252/.m2/repository/io/springfox/springfox-bean-validators/3.0.0/springfox-bean-validators-3.0.0.jar:/home/sn0252/.m2/repository/io/springfox/springfox-swagger2/3.0.0/springfox-swagger2-3.0.0.jar:/home/sn0252/.m2/repository/io/swagger/swagger-annotations/1.5.20/swagger-annotations-1.5.20.jar:/home/sn0252/.m2/repository/io/swagger/swagger-models/1.5.20/swagger-models-1.5.20.jar:/home/sn0252/.m2/repository/io/springfox/springfox-swagger-ui/3.0.0/springfox-swagger-ui-3.0.0.jar:/home/sn0252/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar:/home/sn0252/.m2/repository/org/springframework/plugin/spring-plugin-core/2.0.0.RELEASE/spring-plugin-core-2.0.0.RELEASE.jar:/home/sn0252/.m2/repository/org/springframework/plugin/spring-plugin-metadata/2.0.0.RELEASE/spring-plugin-metadata-2.0.0.RELEASE.jar:/home/sn0252/.m2/repository/net/bytebuddy/byte-buddy/1.10.22/byte-buddy-1.10.22.jar:/home/sn0252/.m2/repository/org/springframework/spring-core/5.3.12/spring-core-5.3.12.jar:/home/sn0252/.m2/repository/org/springframework/spring-jcl/5.3.12/spring-jcl-5.3.12.jar:/home/sn0252/.m2/repository/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar:/home/sn0252/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/home/sn0252/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/home/sn0252/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/sn0252/.m2/repository/org/checkerframework/checker-qual/3.12.0/checker-qual-3.12.0.jar:/home/sn0252/.m2/repository/com/google/errorprone/error_prone_annotations/2.11.0/error_prone_annotations-2.11.0.jar:/home/sn0252/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar cn.com.scc.IoTDBServiceApplication
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.6)

**Comment by HTHou** [comment]
可以试试在源码上执行 `mvn clean package -pl session -am -DskipTests -get-jar-with-dependencies`， 在 session/target下会生成session-jar-with-dependencies jar包。只引用这一个jar 包应该就可以。

另外，0.13.0 正式版正在发版投票。正式发布后，maven 里就可以直接引到正式版本的依赖了，到时候可以去掉这个临时的jar包。

**Comment by TimXu0713** [comment]
你好，运行命令，提示没有“-get-jar-with-dependencies”这个参数。

**Comment by HTHou** [comment]
> 你好，运行命令，提示没有“-get-jar-with-dependencies”这个参数。

-P get-jar-with-dependencies

**Comment by TimXu0713** [comment]
搞定了，谢谢！
