### ISSUE TITLE
Release zip files include incorrect version of Guava

### ISSUE THREAD

**Issue by mscottford** [apache/iotdb#5482]
**Describe the bug**
Since #2303, the `pom.xml` files that reference Guava have specified that any version greater than or equal to `24.1.1` should be used. However, all of the binary [releases in GitHub](https://github.com/apache/iotdb/releases) are shipping with Guava version `21.0`.

**To Reproduce**
1. Download "all-bin" release binary 0.13.0 from [GitHub releases](https://github.com/apache/iotdb/releases/tag/v0.13.0)
2. Extract the file
3. Locate the `guava-A.B.C.jar` file in the `/lib` folder

**Expected behavior**
The version number of the located file is greater than or equal to `24.1.1`.

**Additional context**
I've confirmed that this is also true for the binary releases that can be retrieved from https://iotdb.apache.org/Download/.

**Comment by jixuan1989** [comment]
this is quite strange.. I use `mvn compile dependency:tree -DskipTests` to check who depends on `guava:21.0`  but can not find anyone...

**Comment by HTHou** [comment]
Hi, I'm sure the `guava:21.0` comes from this step, after clear .m2 cache and execute `mvn clean package -pl distribution -am -DskipTests`...

<img width="898" alt="image" src="https://user-images.githubusercontent.com/25913899/162891954-9c5f2dac-3ea4-4e30-9687-4bee42452ca1.png">

**Comment by HTHou** [comment]
I think the issue has been fixed. You can check the nightly build version now.

https://github.com/SteveYurongSu/apache-iotdb-nightly-releases/releases/tag/2022-04-12-12-12-44-0.13-ca6337628-java-8

**Comment by jixuan1989** [comment]
Nice work!
