### ISSUE TITLE
UDF降采样函数Sample采用等间隔降采样时，一直报IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Jinm-zou** [apache/iotdb#5520]
iotdb服务版本为0.13，查询语句为  ```select sample((`"PI.u_s"`),'method'='isometric','k'='500') from root.zoujm.d30344 where Time >= 0 ```。

**Comment by SteveYurongSu** [comment]
Please ignore the PR (#5567), it does not fix the issue.

**Comment by SteveYurongSu** [comment]
Thanks @Jinm-zou for reporting this. I fixed the issue. You can download the latest nightly build version [here](https://github.com/SteveYurongSu/apache-iotdb-nightly-releases) to validate the bugfix :D
