### ISSUE TITLE
聚合查询丢失记录，版本13.0.

### ISSUE THREAD

**Issue by tn987** [apache/iotdb#5773]
IoTDB> select count(Ua)  from root.tjwy.A group by  ([2022-05-01T00:00:00, 2022-05-01T21:00:00),1h)
+-----------------------------+---------------------+
|                         Time|count(root.tjwy.A.Ua)|
+-----------------------------+---------------------+
|2022-05-01T00:00:00.000+08:00|                   60|
|2022-05-01T01:00:00.000+08:00|                   60|
|2022-05-01T02:00:00.000+08:00|                   60|
|2022-05-01T03:00:00.000+08:00|                   60|
|2022-05-01T04:00:00.000+08:00|                   60|
|2022-05-01T05:00:00.000+08:00|                   60|
|2022-05-01T06:00:00.000+08:00|                   60|
|2022-05-01T07:00:00.000+08:00|                   60|
|2022-05-01T08:00:00.000+08:00|                   60|
|2022-05-01T09:00:00.000+08:00|                   60|
|2022-05-01T10:00:00.000+08:00|                   60|
|2022-05-01T11:00:00.000+08:00|                   60|
|2022-05-01T12:00:00.000+08:00|                   60|
|2022-05-01T13:00:00.000+08:00|                   60|
|2022-05-01T14:00:00.000+08:00|                   60|
|2022-05-01T15:00:00.000+08:00|                   60|
|2022-05-01T16:00:00.000+08:00|                   60|
|2022-05-01T17:00:00.000+08:00|                   60|
|2022-05-01T18:00:00.000+08:00|                    0|
|2022-05-01T19:00:00.000+08:00|                    0|
|2022-05-01T20:00:00.000+08:00|                    0|
+-----------------------------+---------------------+
Total line number = 21
It costs 0.019s
IoTDB> select count(Ua)  from root.tjwy.A group by  ([2022-05-01T17:00:00, 2022-05-01T21:00:00),1h)
+-----------------------------+---------------------+
|                         Time|count(root.tjwy.A.Ua)|
+-----------------------------+---------------------+
|2022-05-01T17:00:00.000+08:00|                   60|
|2022-05-01T18:00:00.000+08:00|                   60|
|2022-05-01T19:00:00.000+08:00|                   60|
|2022-05-01T20:00:00.000+08:00|                   60|
+-----------------------------+---------------------+

Total line number = 4
It costs 0.007s
IoTDB>

样本数据：[data.zip](https://github.com/apache/iotdb/files/8606715/data.zip)

**Comment by tn987** [comment]
![QQ图片20220503083623](https://user-images.githubusercontent.com/30252478/166365264-a60b005f-ff83-44f1-a875-fcddf65f670b.png)

**Comment by SteveYurongSu** [comment]
Thanks for reporting this!!  @tn987 

@JackieTien97 @Alima777 PTAL
