### ISSUE TITLE
Push Dockerfiles for latest images (e.g. apache/iotdb:0.13.0-node)  into GitHub repository

### ISSUE THREAD

**Issue by janniswarnat** [apache/iotdb#5794]
**Is your feature request related to a problem? Please describe.**
I would like to create my own adapted Docker image (to enable mqtt) and cannot find the Dockerfile for image apache/iotdb:0.13.0-node that published on Docker Hub

**Describe the solution you'd like**
Push the latest Dockerfiles to GitHub

**Describe alternatives you've considered**
Allow enabling mqtt via environment variables in the standard Docker image

**Comment by HTHou** [comment]
Hi, you can find the v0.13 Dockerfile here.
https://github.com/apache/iotdb/tree/v0.13.0/docker/src/main

We'll update the master branch later.

**Comment by janniswarnat** [comment]
Thanks a lot, I should have found this myself. I was probably confused by the fact the master branch included a list of versioned Dockerfiles.
