### ISSUE TITLE
Either re-interrupt this method or rethrow the "InterruptedException" that can be caught here.

### ISSUE THREAD

**Issue by xingtanzjr** [apache/iotdb#5876]
Code Path: cluster/src/main/java/org/apache/iotdb/cluster/log/catchup/CatchUpTask.java

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/18027703/168047735-418d9905-d28f-4834-b348-0b20e4780b54.png">

InterruptedExceptions should never be ignored in the code, and simply logging the exception counts in this case as "ignoring". The throwing of the InterruptedException clears the interrupted state of the Thread, so if the exception is not handled properly the information that the thread was interrupted will be lost. Instead, InterruptedExceptions should either be rethrown - immediately or after cleaning up the method’s state - or the thread should be re-interrupted by calling Thread.interrupt() even if this is supposed to be a single-threaded application. Any other course of action risks delaying thread shutdown and loses the information that the thread was interrupted - probably without finishing its task.

**Comment by HTHou** [comment]
This issue is no longer valid since the old cluster module has been removed.
