### ISSUE TITLE
This class overrides "equals()" and should therefore also override "hashCode()".

### ISSUE THREAD

**Issue by MinaQin** [apache/iotdb#5879]
Code Path:confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/auth/AuthorReq.java
<img width="877" alt="image" src="https://user-images.githubusercontent.com/55030443/168055618-b1b033cf-5bcb-44b6-bbc6-352252a076c2.png">
According to the Java Language Specification, there is a contract between equals(Object) and hashCode():

If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result.

It is not required that if two objects are unequal according to the equals(java.lang.Object) method, then calling the hashCode method on each of the two objects must produce distinct integer results.

However, the programmer should be aware that producing distinct integer results for unequal objects may improve the performance of hashtables.

In order to comply with this contract, those methods should be either both inherited, or both overridden.

**Comment by chakkk309** [comment]
Hi, I want to try it.
