### ISSUE TITLE
The start.bat file in the sbin folder is automatically cleared to 0k

### ISSUE THREAD

**Issue by wanghui42** [apache/iotdb#5929]
场景：Windows系统下输入启动命令无法启动成功；
原因：sbin文件夹中的start.bat文件被自动清除为0k。
![20220517-145049](https://user-images.githubusercontent.com/105700158/168747355-41e8ff2d-69f4-47af-ab99-1f98538671b2.png)

**Additional context**

**Comment by HTHou** [comment]
Hi, which version are you using?

**Comment by hailiu12** [comment]
Jinrui，SunHao and I （HaiLiu）saw it on 0.10, while it's reported on 0.13 as well. I happens occasional but can't steadily reproduce. We'll work further to find a way to repro it.
