### ISSUE TITLE
Duplicate data point aggregation（重复数据点聚合查询）

### ISSUE THREAD

**Issue by a1135656335** [apache/iotdb#5964]
![image](https://user-images.githubusercontent.com/34510920/169432223-32ebc1da-2a23-4950-8d37-8453ed5e7925.png)

insert data：
insert into root.open.api.wf02.1123(timestamp,success,fail) aligned  values(1,10,10);
insert into root.open.api.wf02.1123(timestamp,success,fail) aligned  values(1,11,11);
insert into root.open.api.wf02.1123(timestamp,success,fail) aligned  values(2,11,11);
insert into root.open.api.wf02.1123(timestamp,success,fail) aligned  values(3,11,11);

select：
IoTDB> select SUM(success),SUM(fail) from root.open.api.** align by device;
+-----------------------+------------+---------+
|                 Device|SUM(success)|SUM(fail)      |
+-----------------------+------------+---------+
|root.open.api.wf02.1123|        43.0  |     43.0   |
+-----------------------+------------+---------+
Total line number = 2
It costs 0.005s

if duplicate data point is update,  result should be 33.0.

**Comment by HTHou** [comment]
Hi, the bug has been fixed now. You can download the latest snapshot version from https://github.com/SteveYurongSu/apache-iotdb-nightly-releases .

**Comment by a1135656335** [comment]
closed
