### ISSUE TITLE
AttributeError: 'TSDataType' object has no attribute 'np_dtype'

### ISSUE THREAD

**Issue by lizhenwei** [apache/iotdb#5999]
**Describe the bug**
python run SessionExample.py failed.throw error
``` 
Traceback (most recent call last):
  File "D:/lzwprogram/loadtest/iotdbtest/SessionExample.py", line 188, in <module>
    np.array([False, True, False, True], TSDataType.BOOLEAN.np_dtype()),
AttributeError: 'TSDataType' object has no attribute 'np_dtype'
```

**To Reproduce**
1. copy https://github.com/apache/iotdb/blob/master/client-py/SessionExample.py into local folder
2. pip install numpy==1.21.6 apache-iotdb==0.13.0.post1
3. python run SessionExample.py

**Comment by HTHou** [comment]
Hi, `np_dtype` in TSDataType is added in master branch, which should not be in 0.13.0 version. You can try the test 0.14.0 version of py-client from https://test.pypi.org/project/apache-iotdb-test/ . It is compatible with 0.13.0 IoTDB server.

**Comment by HTHou** [comment]
For the current 0.13.0 python client, you can refer the SessionExample below.
https://github.com/apache/iotdb/blob/v0.13.0/client-py/SessionExample.py
https://github.com/apache/iotdb/blob/4f985dd6dd7d1deb47359f27f10e84248490f837/client-py/SessionExample.py#L180-L187

**Comment by lizhenwei** [comment]
thank you,
I fix it by this command:
```
pip install -i https://test.pypi.org/simple/ apache-iotdb-test==0.14.0.1
```

> Hi, `np_dtype` in TSDataType is added in master branch and 0.13.1, which should not be in 0.13.0 version. You can try the 0.14.0 test version of py-client from https://test.pypi.org/project/apache-iotdb-test/ . It is compatible with 0.13.0 IoTDB server.
thank you 
I fix it by this command
