### ISSUE TITLE
grafana plugins  login   occur  "invalid username or password"

### ISSUE THREAD

**Issue by zhengshubin** [apache/iotdb#6195]
**Describe the bug**

iotdb:0.13  grafana:8.5.4

When I use grafana datasource to connect this  rest, it occur " 401 ,invalid username or password" ,but when I use  script to connect  /grafana/v1/login , it return 200

**Comment by HTHou** [comment]
@SteveYurongSu PTAL

**Comment by SteveYurongSu** [comment]
@zhengshubin 

The address in the login panel should be like `http://<ip>:<port>`. 

Please check if you are missing the `http://` or `<port>`.

If you still have problems, please contact me :D

**Comment by zhengshubin** [comment]
> 

Yes,  I missing "http:// ", and now it work. Thanks

**Comment by zhengshubin** [comment]
> @zhengshubin
> 
> The address in the login panel should be like `http://<ip>:<port>`.
> 
> Please check if you are missing the `http://` or `<port>`.
> 
> If you still have problems, please contact me :D

Yes, I missing "http:// ", and now it work. Thanks
