### ISSUE TITLE
节点是以中文命名的，查询语句在不同版本中，查询结果有差别。

### ISSUE THREAD

**Issue by xm19929** [apache/iotdb#6248]
0.13.0的版本里无法查出数据；
0.12.5的版本里可查出数据；
请教下问题的解决方法
![1655089221485](https://user-images.githubusercontent.com/30405857/173272387-acbe2847-3728-49a5-80f5-0635c8e46c31.jpg)
![16545912824547](https://user-images.githubusercontent.com/30405857/173272398-a13577f9-defa-4d9d-9c09-edfce98e9dbd.png)

**Comment by HTHou** [comment]
https://iotdb.apache.org/zh/UserGuide/Master/Reference/Syntax-Conventions.html#%E6%97%A7%E8%AF%AD%E6%B3%95%E7%BA%A6%E5%AE%9A%E4%B8%AD%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by xm19929** [comment]
> https://iotdb.apache.org/zh/UserGuide/Master/Reference/Syntax-Conventions.html#%E6%97%A7%E8%AF%AD%E6%B3%95%E7%BA%A6%E5%AE%9A%E4%B8%AD%E7%9A%84%E9%97%AE%E9%A2%98
谢谢~可解决
