### ISSUE TITLE
内存表刷新报数组下标越界错，iotdbserver进入只读模式

### ISSUE THREAD

**Issue by zhouzhiy** [apache/iotdb#6551]
报错日志截图如下
![1656642207424_1656641353522_CA91DBB2-D662-40c5-BCAA-55FBBE27FEE1](https://user-images.githubusercontent.com/52025735/176814065-98854be7-5db8-4737-8b1e-98f24d08052a.png)

**Comment by jixuan1989** [comment]
issue #6551

**Comment by jixuan1989** [comment]
@Cpaulyz  @qiaojialin , has is been fixed in both v0.13 and v0.14?

**Comment by Cpaulyz** [comment]
> [To rel/0.13][IOTDB-3730][ISSUE-6551] ArrayIndexOutOfBounds when flushing a memtable #6576

Yes. It has been fixed in 0.12 #6572, 0.13 #6576 and master #6577(0.14).
