### ISSUE TITLE
How to implement this query method

### ISSUE THREAD

**Issue by skyplume** [apache/iotdb#6751]
For the data of the same indicator over a period of time, I want to clean out the data with the same value as the previous one, and only keep the changed data. I want to achieve the same effect as “SELECT a.id ,a.value FROM test a left join test b on a.id+1=b.id where  a.value!=b.value” does, but the DML and UDF provided by querying the official website documents seem to have no way to achieve similar effects. 
How to achieve this effect? thank you

**Comment by qiaojialin** [comment]
Hi, this may be implemented by a UDF. You could buffer the current data, and output the current data once you meet a different value.

**Comment by Wei-hao-Li** [comment]
> For the data of the same indicator over a period of time, I want to clean out the data with the same value as the previous one, and only keep the changed data. I want to achieve the same effect as “SELECT a.id ,a.value FROM test a left join test b on a.id+1=b.id where a.value!=b.value” does, but the DML and UDF provided by querying the official website documents seem to have no way to achieve similar effects. How to achieve this effect? thank you

Hi, we have implement a UDF as Built-in Function to do this job, you can see [PR](https://github.com/apache/iotdb/pull/6874).

**Comment by skyplume** [comment]
Sorry, I just finished two weeks of sick leave. I will check the new UDF. Thank you for your help!
