### ISSUE TITLE
DataGrip  使用JDBC驱动连接异常 / connection error when using DataGrip with JDBC driver

### ISSUE THREAD

**Issue by sen9912** [apache/iotdb#6774]
DataGrip version 2019.3.5  
JDBC driver version iotdb-jdbc-0.13.0
iotdb version  0.13.0
error message
			Index 1 out of bounds for length 1.
![107791658819192_ pic](https://user-images.githubusercontent.com/25913899/181148966-698c8800-3959-43db-ba57-30d256252ccb.jpg)

**Comment by HTHou** [comment]
这个应该是DataGrip调用了某个0.13.0 版本 JDBC 没实现的方法导致的。目前的JDBC驱动只能保证 iotdb-sql 可以执行，有一些关于表操作的方法没有实现。欢迎提供一下具体是哪个没实现的方法导致这个问题，可以记录一下。

**Comment by HTHou** [comment]
This bug has been fixed by #6961, you can try to rebuild the JDBC driver from source code and try again.
