### ISSUE TITLE
0.13.1 docker run container error

### ISSUE THREAD

**Issue by szz-9503** [apache/iotdb#6958]
**Describe the bug**
0.13.1 docker run container error 

docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/iotdb/sbin/start-server.sh": stat /iotdb/sbin/start-server.sh: no such file or directory: unknown.

**Comment by HTHou** [comment]
Hi, could you please provide a screenshot of this error? Thanks.

**Comment by szz-9503** [comment]
![1660198517146](https://user-images.githubusercontent.com/66717160/184074466-37376f0b-c404-4640-8142-8afbeda8c8eb.png)

**Comment by HTHou** [comment]
@xiaoyekanren PTAL

**Comment by szz-9503** [comment]
thanks!
