### ISSUE TITLE
select error when selecting a single quotation mark 

### ISSUE THREAD

**Issue by nlosilva1** [apache/iotdb#6987]
**Describe the bug**
I try to insert a quotation mark into iotdb with iotdb-client using the following sql: 
`insert into root.sg0(timestamp, t0) values(1, '\"')` 
And it is successfully inserted, which can be queried by `select * from root.**`  
But when I try to query it with a select clause `select * from root.sg0 where t0 = '\"'` or `select * from root.sg0 where t0 = '"'`, I get a 500 ERROR in IoTDB, which is a `java.lang.StringIndexOutOfBoundsException`
If a select like this is invalid, I might get an error like 401 or so (like using single quotation mark without backslash) but not 500; and I can also run other queries validly like  
`select * from root.sg0 where t0 = '\\'` or 
`select * from root.sg0 where t0 = 'a\"'` or
 `select * from root.sg0 where t0 = 'a"'`. Will this be a bug to fix? Or is there something i misunderstood? 
(I also tried insert sql like `insert into root.sg0(timestamp, t0) values(1, '"')`  and it also successed)
Thanks.

**To Reproduce**
Execute the following statements in iotdb-client:
 `set storage group to root.sg0`
`create timeseries root.sg0.t0 with datatype=text, encoding=plain`
`insert into root.sg0(timestamp, t0) values(1, '\"')`
`select * from root.sg0 where t0='\"'`

**Expected behavior**
The system will return a query set(if the select is valid) or return a error 4xx (if the select is not valid)

**Screenshots**
The input and output in iotdb-client
![image](https://user-images.githubusercontent.com/25195216/184540838-2ae25ed5-6b81-4d36-a2b9-3bdc0a75bab5.png)

Error in iotdb
![image](https://user-images.githubusercontent.com/25195216/184540856-6aaf8cd2-3877-47e4-b3d4-f0e2cbb7f86e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
IoTDB 0.13.1

**Comment by HTHou** [comment]
Fixed in latest rel/0.13 branch
