### ISSUE TITLE
"String#replace" should be preferred to "String#replaceAll"

### ISSUE THREAD

**Issue by xingtanzjr** [apache/iotdb#7001]
Code Path:
jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java

The underlying implementation of String::replaceAll calls the java.util.regex.Pattern.compile() method each time it is called even if the first argument is not a regular expression. This has a significant performance cost and therefore should be used with care.

When String::replaceAll is used, the first argument should be a real regular expression. If it’s not the case, String::replace does exactly the same thing as String::replaceAll without the performance drawback of the regex.

This rule raises an issue for each String::replaceAll used with a String as first parameter which doesn’t contains special regex character or pattern.

**Comment by GuanchuShen** [comment]
[WeOpen Star]I would like to help

**Comment by wjr4hy** [comment]
[WeOpen Star]I would like to help
