### ISSUE TITLE
搭建伪分布式问题

### ISSUE THREAD

**Issue by honestpeople** [apache/iotdb#7258]
单机部署 3 节点 1 副本，为什么cluster rpc 监控的是127.0.0.1而不是0.0.0.0？
iotdb版本0.13.2
信息：2022-09-07 09:02:25,594 [main] INFO  o.a.i.d.s.t.ThriftService:135 - IoTDB: start Cluster RPC Service successfully, listening on ip 127.0.0.1 port 6667

**Comment by jixuan1989** [comment]
Hi, pls use v0.14 if you want to try the cluster.
