### ISSUE TITLE
System rejected over 10017ms

### ISSUE THREAD

**Issue by zhouzhiy** [apache/iotdb#7310]
运行一段时间后数据写入失败

日志如下

[log_all.zip](https://github.com/apache/iotdb/files/9564470/log_all.zip)

**Comment by jixuan1989** [comment]
@HTHou  can you  review this log? 
I think it will help us to improve the content.

**Comment by HTHou** [comment]
Hi @zhouzhiy, it seems that it caused by memtable is too small and flushed too much times. You can try changing `avg_series_point_number_threshold` from `10000` to `1000000` to improve it.
