### ISSUE TITLE
0.14Preview2分布式写入对齐时间序列数据失败

### ISSUE THREAD

**Issue by TheSaltedFish** [apache/iotdb#7327]
在3台设备上进行部署，每台设备各一个datanode，除开必要的节点地址和日志路径配置之外未改动任何配置。
创建元数据正常，但写入对齐时间序列的数据时失败，查看错误日志发现错误信息：connot dispatch FI for write operation

**Comment by HTHou** [comment]
可以看看datanode的error日志里有没有其他信息

**Comment by HTHou** [comment]
Fixed in latest version
