### ISSUE TITLE
使用maven编译v0.13.2分支，报错

### ISSUE THREAD

**Issue by snake-zhiqiang** [apache/iotdb#7385]
# mvn clean package -DskipTests -U
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.eclipse.jetty:jetty-server:jar -> version ${jetty.version} vs 11.0.6 @ org.apache.iotdb:iotdb-parent:0.13.2, /opt/module/IoTDB/iotdb/pom.xml, line 544, column 25
[FATAL] Non-resolvable parent POM for org.apache.iotdb:testcontainer:0.13.2-SNAPSHOT: Could not find artifact org.apache.iotdb:iotdb-parent:pom:0.13.2-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 23, column 13
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.eclipse.jetty:jetty-server:jar -> version ${jetty.version} vs 11.0.6 @ org.apache.iotdb:iotdb-parent:0.13.2, /opt/module/IoTDB/iotdb/pom.xml, line 544, column 25
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.eclipse.jetty:jetty-server:jar -> version ${jetty.version} vs 11.0.6 @ line 544, column 25
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.iotdb:testcontainer:0.13.2-SNAPSHOT (/opt/module/IoTDB/iotdb/testcontainer/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.apache.iotdb:testcontainer:0.13.2-SNAPSHOT: Could not find artifact org.apache.iotdb:iotdb-parent:pom:0.13.2-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 23, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by HTHou** [comment]
https://github.com/apache/iotdb/tree/rel/0.13 用最新 rel/0.13 分支编译吧
或者用一个不带docker的机器进行编译
这是由于打tag时候机器没有docker，testcontainer 的版本号没有自动修改引起的，小问题。

**Comment by HTHou** [comment]
也可以手动修改 testcontainer pom里的版本号

**Comment by snake-zhiqiang** [comment]
> 也可以手动修改 testcontainer pom里的版本号

我先换成二进制包安装了 下次试试

**Comment by snake-zhiqiang** [comment]
> https://github.com/apache/iotdb/tree/rel/0.13 用最新 rel/0.13 分支编译吧 或者用一个不带docker的机器进行编译 这是由于打tag时候机器没有docker，testcontainer 的版本号没有自动修改引起的，小问题。

[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.6.7:wget (get-thrift-executable) on project iotdb-thrift: IO Error: Could not get content -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :iotdb-thrift


我用你所说的分支编译 还是报错了

**Comment by HTHou** [comment]
这个看起来是有个依赖被墙导致的

**Comment by snake-zhiqiang** [comment]
> 这个看起来是有个依赖被墙导致的

我现在正尝试手动安装thrift

**Comment by KW213** [comment]
> 也可以手动修改 testcontainer pom里的版本号

请问把testcontainer pom里面的哪个版本号改成什么可以解决这个问题，我的机器里又docker而且不太方便更改

**Comment by snake-zhiqiang** [comment]
> > > 这个看起来是有个依赖被墙导致的
> > 
> > 
> > 我现在正尝试手动安装thrift
> 
> 请问您手动安装成功了么？是直接官网下载thrift然后编译吗

我换成14版本 就可以了。

**Comment by panqiang199** [comment]
@KW213 可以手动下载thrift。然后通过maven命令的参数指定thrift的地址mvn clean package -pl distribution -am -DskipTests -Dthrift.download-url=http://apache.org/licenses/LICENSE-2.0.txt -Dthrift.exec.absolute.path={这里就是thrift指定文件的地址}

**Comment by panqiang199** [comment]
@KW213 下载thrift可以用这个链接http://archive.apache.org/dist/thrift/0.14.1/thrift-0.14.1.exe
