### ISSUE TITLE
为什么在官方文档，看不到对TsFile的详细介绍呢？

### ISSUE THREAD

**Issue by chenjiehao** [apache/iotdb#7401]

**Comment by jixuan1989** [comment]
see https://cwiki.apache.org/confluence/display/IOTDB/TsFile+Format

**Comment by chenjiehao** [comment]
感谢~


在 2022年9月22日 16:39，Xiangdong ***@***.***> 写道：


see https://cwiki.apache.org/confluence/display/IOTDB/TsFile+Format
