### ISSUE TITLE
当时序不存在的时候能否直接返回空

### ISSUE THREAD

**Issue by Haze-Lan** [apache/iotdb#7434]
IoTDB> select variable,number,save,value from root.product.1_data.57 where   time >=1664146800000 and time <=1664153923031 and variable in  ( 'Location') order by time  asc
Msg: 411: Error occurred in query process: Unknown time series root.product.1_data.57.variable in `where clause`

因为设备未报数据过来所以 表内是没有数据的，如果要过滤某个值就会报错，这里能不能处理成跟time一样 没有值就返回为空

**Comment by HTHou** [comment]
@JackieTien97

**Comment by jixuan1989** [comment]
IMO, it is different between "no data" and "no schema".. Users may need to do some other action when they meet  the latter case.

**Comment by qiaojialin** [comment]
Thanks for reporting, we will optimize this 
https://issues.apache.org/jira/browse/IOTDB-4576

**Comment by Wei-hao-Li** [comment]
Has implemented in this [PR](https://github.com/apache/iotdb/pull/7924).
