### ISSUE TITLE
聚合查询函数会支持方差吗

### ISSUE THREAD

**Issue by yiwojiu** [apache/iotdb#7473]
聚合查询函数有支持方差的计划吗？opentsdb、questdb都是有dev函数的

**Comment by HTHou** [comment]
@trin1t PTAL

**Comment by trin1t** [comment]
目前有stddev函数，下次更新库的时候可以顺带加上去

**Comment by yiwojiu** [comment]
> 目前有stddev函数，下次更新库的时候可以顺带加上去
多谢！！
