### ISSUE TITLE
(欢迎使用/测试IoTDB的公司在此登记) Welcome to leave your company's info if your company are using/testing IoTDB

### ISSUE THREAD

**Issue by jixuan1989** [apache/iotdb#748]
Welcome to register by company + homepage (optional) + use case(optional), 
your support is important to us.
We will sync to official website periodically (TBD).

欢迎采用/正在测试IoTDB的公司在此登记，您的支持是我们最大的动力。
请按公司名 + 首页（可选） + 应用案例（可选）的格式登记。
后期我们会定期同步至使用公司列表页面。

**Comment by juice411** [comment]
大唐先一科技，目前正在做Iotdb的性能和稳定性测试，因为集群版没有出来，公司暂时停留在测试观察阶段。

**Comment by kevin-xin** [comment]
金风科技在重点研发项目中使用了iotdb，实时消费kafka中的风机SCADA数据，使用方便接口方便,极值查询，函数计算基本上都是毫秒级返回。

**Comment by zhangweide666** [comment]
北京创智信科，使用IoTDB存储中国铁塔设备监控数据，在试用阶段，IoTDB数据库的插入、存储、查询性能优越，目前正在进行压力和稳定性测试

**Comment by xiamingwu365** [comment]
北京清智物联在分析调相机(发电机)的在线监测数据，测试使用IoTDB，目前在等待分布式版本，用于诊断中心。

**Comment by vesense** [comment]
@jixuan1989 We'd better add these companies to the powered page. This is very convincing for users.
http://iotdb.apache.org/Community/Community-Powered%20By.html#companies-and-organizations

**Comment by lxn1992** [comment]
建龙钢铁，对iotdb进行测试，祝愿乔博等创作者引领世界

**Comment by shareli** [comment]
中泰科技  主要使用iotdb在物联网，智能家居行业。目前在做性能和压力测试。由于没有集群版本，所以还在观望

**Comment by jixuan1989** [comment]
> 中泰科技 主要使用iotdb在物联网，智能家居行业。目前在做性能和压力测试。由于没有集群版本，所以还在观望

可以测试下cluster_new 分支，并非常欢迎对这个分支提issue~

**Comment by wc188996** [comment]
太极计算机股份有限公司 企业BG 基础能源SBU 准备 测试性能

**Comment by yuerj** [comment]
用友-云平台-微服务团队，在开发测试环境使用了iotdb，祝愿乔博等创作者引领世界，社区越来越强大

**Comment by changyonggang** [comment]
> 大唐先一科技，目前正在做Iotdb的性能和稳定性测试，因为集群版没有出来，公司暂时停留在测试观察阶段。

现在有分布式的版本吗？

**Comment by qiaojialin** [comment]
> > 大唐先一科技，目前正在做Iotdb的性能和稳定性测试，因为集群版没有出来，公司暂时停留在测试观察阶段。
> 
> 现在有分布式的版本吗？

@changyonggang master 分支的 0.12.0-SNAPSHOT 有分布式的代码，可以测试了。这个问题可以单独提 issue，不在这讨论啦~

http://iotdb.apache.org/zh/UserGuide/Master/Server/Cluster%20Setup.html

**Comment by wc188996** [comment]
太极计算机股份有限公司，目前在做IOTDB的测试和应用中，在一个项目中用来记录人员追踪器的GPS定位信息。祝IOTDB社区越做越强！👍👍

**Comment by fly-chosen** [comment]
开始加入社区，研究

**Comment by xlgo** [comment]
车星际网络科技有限公司      汽车odb盒子，行车记录仪。记录GPS轨迹信息，实现手机查看轨迹，实时位置 等。

**Comment by 7bao** [comment]
大唐先一 某项目在用 但是使用rpc c++代码 和你们的sessionExcample.cpp 文件查出的结果有问题。 timestamp   value；value一直是同一个值，用你们最新的代码编译，找不到一个叫 catch.h的头文件，盼解决

**Comment by L00161910** [comment]
Testing - MS Win 10.0.19041 / 64 /  Java 1.8.0_271 - Stable - No Load

**Comment by lizhizhou** [comment]
震坤行 www.zkh360.com 行家设备云 https://iservice.zkh360.com/

**Comment by LeiRui** [comment]
> @jixuan1989 We'd better add these companies to the powered page. This is very convincing for users.
> http://iotdb.apache.org/Community/Community-Powered%20By.html#companies-and-organizations

Agree. If possible I would suggest listing the cooperating companies on the IoTDB home page. Take [shimo document](https://shimo.im/) as an example:
![image](https://user-images.githubusercontent.com/33376433/119633457-5818b580-be44-11eb-943b-ab4ebda30419.png)

**Comment by Eights-Li** [comment]
长安汽车 IOTDB用于车况信号的存储和查询

**Comment by it-boy-like-girl** [comment]
绍兴安瑞思网络科技，工业互联网项目，对于目前需求，单机完全够用，只希望稳定，查询很高效。nice

**Comment by e1o** [comment]
深圳嘉信公司，使用IoTDB存储武汉桥梁健康监控数据，在试用阶段，IoTDB数据库的插入、存储、查询性能优越，目前在等待Grafana插件，祝愿IotDB越来越来

**Comment by yanghe25413** [comment]
拓维信息系统股份有限公司，使用iotdb为某大型国企采集设备数据，搭建物联网，智能制造相关平台，目前已步入生产环节

**Comment by CloudsYy** [comment]
广东瑞恩科技有限公司，使用iotdb的cnc工厂设备数据采集存储并应用，查询性能各方面还不错，希望后面功能越来越完善！

**Comment by limeng32** [comment]
用友网络科技，多维数据库团队，打算深入研究IoTDB。
