### ISSUE TITLE
数据存活时间（TTL） 没有起作用 ？

### ISSUE THREAD

**Issue by SunnySaman** [apache/iotdb#7572]
**Describe the bug**
配置如下：
```
timestamp_precision=ns
default_ttl=600000
```
1. 我不确定我设置的这个 600000 是ns 还是 ms级别的。
2. 所有我插入了5条数据（如下）
![image](https://user-images.githubusercontent.com/108415530/195234108-d03b7f20-1f87-49d9-8073-f83bcaf9ac27.png)
3. 如果 600000 是ms级别，则过了10分钟后，数据依然存在
![image](https://user-images.githubusercontent.com/108415530/195234253-112cc532-1fbb-402b-aeea-6333fcf484b1.png)

-- 版本：

![image](https://user-images.githubusercontent.com/108415530/195234340-45c44190-3c5e-4e3d-8e60-488b5eecac5f.png)

**Comment by HeimingZ** [comment]
We will fix this issue in the new version.

**Comment by HTHou** [comment]
https://github.com/apache/iotdb/pull/7580 
Fixed
