### ISSUE TITLE
Is it possible to provide an API for setting the TTL?

### ISSUE THREAD

**Issue by xianzheTM** [apache/iotdb#7702]
The way to set the TTL now is via the CLI.[https://iotdb.apache.org/UserGuide/Master/Delete-Data/TTL.html](https://iotdb.apache.org/UserGuide/Master/Delete-Data/TTL.html#unset-ttl)#unset-ttl .this increases the initialisation cost of the device.
So can IoTDB provide a way to set the TTL using the API? After all there is too much duplication of work going through the CLI settings on each device.

**Comment by HTHou** [comment]
Hi, you can use the API `session.executeNonQueryStatement("set ttl to xxx") `.

**Comment by xianzheTM** [comment]
> Hi, you can use the API `session.executeNonQueryStatement("set ttl to xxx") `.

Thank you for your answer.
