### ISSUE TITLE
0.14 Preview2升级到Preview3出错

### ISSUE THREAD

**Issue by TheSaltedFish** [apache/iotdb#7773]
按文档停止原版本的datanode和confignode，然后修改新版本的配置文件，各个设置一致，然后运行confignode：
提示“The parameter config_node_id doesn't exist in confignode-system.properties”；
找到这个文件后在文件里添加“config_node_id”配置之后(值在原版本里查询得到)，报错“For input string:[serverIP]_22278”，能成功运行，但运行datenode的时候提示无法加入集群，因为运行的confignode不是leader；
使用“[serverIP]_22278”作为confignode-system.properties里“config_node_id”配置的值后继续报错“The parameter config_node_id doesn't exist in confignode-system.properties”，可能是无法识别；

问一下是不是前后版本不兼容，有没有办法解决这个问题？如果无法升级的话有没有进行数据迁移的办法？

**Comment by HTHou** [comment]
1.0正式版本已经发布了，可以通过load-tsfile工具将preview版本的数据升级到正式版里。
