### ISSUE TITLE
`SHOW LATEST TIMESERIES`的关键字`LATEST`似乎无效

### ISSUE THREAD

**Issue by panlw** [apache/iotdb#7931]
**Describe the bug**

`SHOW LATEST TIMESERIES`的关键字`LATEST`似乎无效，出来的结果并不是按照 timeseries 的创建顺序排列

**Desktop (please complete the following information):**

 - OS: macOS 12.6 (Apple M1 Pro)
 - Version: IotDB v0.13.1

**Comment by HTHou** [comment]
SHOW LATEST TIMESERIES

表示查询出的时间序列需要按照最近插入数据的时间戳降序排列，不是按照timeseries 的创建顺序排列的

**Comment by panlw** [comment]
哦，LATEST 是这个意思啊，明白了，谢谢！
