### ISSUE TITLE
使用maven编译rel-0.13版本时报错

### ISSUE THREAD

**Issue by KW213** [apache/iotdb#7950]
**Describe the bug**
使用maven编译rel-0.13版本时报错

[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.6.7:wget (get-thrift-executable) on project iotdb-thrift: IO Error: Could not get content -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :iotdb-thrift

**Comment by jixuan1989** [comment]
this is due to the network problem (can not download a resource from github).
pls retry.
