### ISSUE TITLE
[Bug] Can't create database

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/iotdb#8192]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

loTDB:0.13.3
Mac OS:12.6

### Describe the bug and provide the minimal reproduce step

I was unable to create a database after connecting to loTDB with the client
`CREATE DATABASE root.ln`

>  
    Msg: 401: Error occurred while parsing SQL to physical plan: line 1:7 no viable alternative at input 'CREATE DATABASE'

### What did you expect to see?

I can create database

### What did you see instead?

Msg: 401: Error occurred while parsing SQL to physical plan: line 1:7 no viable alternative at input 'CREATE DATABASE'

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by HTHou** [comment]
Database is introduced from v1.0. For v0.x, you should use storage group.

**Comment by Oliverwqcwrw** [comment]
Thanks for your reply @HTHou ,
I also notice the document is modified  to storage group,so fast 👍
