### ISSUE TITLE
Msg: 906: There are no available SchemaRegionGroup RegionGroups currently

### ISSUE THREAD

**Issue by simpledong81** [apache/iotdb#8329]
I upgrade to v1.0 and step by "Quick Start"
When I run "CREATE TIMESERIES root.ln.wf01.wt01.status WITH DATATYPE=BOOLEAN, ENCODING=PLAIN" in CLI, 
I always got "Msg: 906: There are no available SchemaRegionGroup RegionGroups currently, please use "show cluster" or "show regions" to check the cluster status".
What should I do?

**Comment by MarcosZyk** [comment]
Please describe your upgrading process. It seems the upgrade operation may fail, which need to be confirmed by checking the log generated during upgrading.

**Comment by MarcosZyk** [comment]
For better convenience, you can contact me via VX, named MarcosZyk.

**Comment by simpledong81** [comment]
SchemaConsensusPort:50010 was under used by another process.
Kill pid & restart resolved the problem.
Thanks.
