### ISSUE TITLE
In the docs  folder the README.md file is empty. It's not needed.

### ISSUE THREAD

**Issue by sumanpaikdev** [apache/iotdb#8373]
Empty Readme.md file can be removed.

**Comment by HTHou** [comment]
Yes, it's useless. Would you like to submit a PR to remove it?

**Comment by sumanpaikdev** [comment]
sure

**Comment by HTHou** [comment]
Hi, it seemed that the file is useful. After I merged your PR, the homepage looked like this.
 
![36491670581834_ pic](https://user-images.githubusercontent.com/25913899/206849589-8d50df86-7450-4e94-be34-33394c1c7641.jpg)

Therefore I reverted your PR. Anyway, thanks for you contribution!

**Comment by sumanpaikdev** [comment]
Ok, delete my pr. thanks for your feedback.
