### ISSUE TITLE
元数据模版目前支持修改吗？

### ISSUE THREAD

**Issue by whsqjss** [apache/iotdb#8394]
iotdb版本:v1.0.0

当前元数据模版好像只支持激活，卸载。但是卸载模版后，path已有的数据点会被清除。
有什么方法能在不清除数据的情况下，修改path的元数据模版吗？

**Comment by HTHou** [comment]
@MarcosZyk PTAL

**Comment by zhangyf001** [comment]
fsdafsdsdafsda

**Comment by MarcosZyk** [comment]
In IoTDB v1.0.0, template update operation has not been supported yet. Here are some suggestions:
1. If you want to add some extra timeseries to specific devices activating template, you can directly create a normal timeseries to this device via CreateTimeSeries
2. Divide your physical device into several logical devices, and each of them can use an individual template
3. Before deactivating and unsetting template, export the data first via export tools or ```select into```
