### ISSUE TITLE
[Bug] v1.0.0 采用java原生接口insertAlignRecords批量插入时，regions可能为空List

### ISSUE THREAD

**Issue by whsqjss** [apache/iotdb#8550]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

OS: Centos 7.6
IoTDB: v1.0.0

### Describe the bug and provide the minimal reproduce step

采用java原生接口insertAlignRecords批量插入时（每次写入5000个数据点），regions可能为空List。

datanode日志内容如下：
![iotdb_error](https://user-images.githubusercontent.com/35548533/208689992-14b580f5-d0d2-4a8c-90dc-8664a21777c9.png)

抛出异常的代码
![iot-db1](https://user-images.githubusercontent.com/35548533/208690649-f109655f-b227-4e8e-8919-1311028417d5.png)

应用程序控制台报错：
![iot-db2](https://user-images.githubusercontent.com/35548533/208690547-5ef475f7-454c-4a6f-b13a-ec1548ec895e.png)

### What did you expect to see?

异常出现的原因？

### What did you see instead?

异常出现的原因？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xingtanzjr** [comment]
Hi @whsqjss, thanks for your reporting.

Could you please supply more details regarding your tests ?
1. how many confignodes/datanodes did you deployed in your tests.
2. Before writing data using insertAlignedRecords, did you create the schema manually ?
3. can you execute the cmd `show regions` by sql client ?

Thanks,
Jerry

**Comment by whsqjss** [comment]
1. I deployed 1 confignode and 3 datanodes
![iotdb-1](https://user-images.githubusercontent.com/35548533/209901601-aa0e0320-3b3e-4e9f-82d8-3f3c9d076576.png)
2. I created 1 schema for writing data
![iotdb-2](https://user-images.githubusercontent.com/35548533/209901754-bbbb5208-555a-492f-a94b-fa3e7eb46617.png)

3.  `show regions`
![iotdb-3](https://user-images.githubusercontent.com/35548533/209901931-4cf3982d-0f3c-47d6-9a2e-df0bc21c6fae.png)
