### ISSUE TITLE
python client error when disable wal(禁用wal之后，python客户端连接错误)

### ISSUE THREAD

**Issue by 0x55aa** [apache/iotdb#8801]
### Discussed in https://github.com/apache/iotdb/discussions/8794

<div type='discussions-op-text'>

<sup>Originally posted by **0x55aa** January  9, 2023</sup>
version: 1.0.0
版本：1.0.0

in conf file  iotdb-common.properties, set
`wal_mode=DISABLE`
,then get error:

```

  File "/home/work/x/IoTDB/__init__.py", line 153, in connection_init
    self.session.open(False)
  File "/home/.virtualenvs/lib/python3.9/site-packages/iotdb/Session.py", line 149, in open
    self.set_time_zone(self.__zone_id)
  File "/home/.virtualenvs/python3.9/site-packages/iotdb/Session.py", line 1017, in set_time_zone
    raise RuntimeError("Could not set time zone because: ", e)
RuntimeError: ('Could not set time zone because: ', TTransportException('Transport not open'))
```
delete wal_mode configuretion, then running program is ok.</div>

**Comment by HTHou** [comment]
IoTConsensus is using wal. If using IoTConsensus (default for DataRegion), wal can not be disabled.

**Comment by 0x55aa** [comment]
i change to `data_region_consensus_protocol_class=org.apache.iotdb.consensus.simple.SimpleConsensus`, it works.thanks a lot
