### ISSUE TITLE
当前版本暂不支持删除某一闭时间区间范围内的数据 （do not support time range deletion now）

### ISSUE THREAD

**Issue by juice411** [apache/iotdb#897]
其实这个功能有时候也是需要的，因为写数据过程中由于第三方系统的异常，导致写入了时间异常的数据，比如写入了未来时间的数据或者写入了过期时间的数据，后来被业务人员发现后需要删除异常数据，这样就需要根据某一闭时间区间范围删除数据。可是目前不支持啊。

**Comment by qiaojialin** [comment]
感谢反馈，我们之后考虑扩充一下delete的功能

**Comment by qiaojialin** [comment]
在0.11版本已经支持啦
