### ISSUE TITLE
[Bug] grafana plugin 对于多个非对齐序列同时展示时把null处理为0的问题

### ISSUE THREAD

**Issue by wang3076** [apache/iotdb#9061]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

iotdb 1.0.0 fbbca3f-dev
grafana 9.3.6 社区版

### Describe the bug and provide the minimal reproduce step

1. 进入grafana，新建一个panel，选择Timeseries类型
2. 数据源选择ApacheIotDB， 查询语句输入一个 select * from root.dev.dev1 ，注意dev1下的多个序列是非对其的

### What did you expect to see?

每个序列正常展示，对于null点不展示

### What did you see instead?

![image](https://user-images.githubusercontent.com/118646023/218909247-e5372931-c0ed-4dc2-a2a3-de26926652b2.png)
对于null的点变成了0，使得序列展示的时候连接了很多0点

### Anything else?

IotDB直接查询是正常的，排除IotDB本身问题，应该是grafana plugin问题
IotDB数据查询结果：
![image](https://user-images.githubusercontent.com/118646023/218909491-0e72c44b-e45a-49bf-8ef8-faccb0590975.png)
grafana中折线数据表格化展示结果：
![image](https://user-images.githubusercontent.com/118646023/218909589-a918941b-4bb1-46ab-b16c-a8a4265ada10.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by wang3076** [comment]
已解决，两种方法
方法1、对于同时查多个非对齐序列，补空值，参考
https://iotdb.apache.org/zh/UserGuide/V1.0.x/Query-Data/Fill.html#%E5%A1%AB%E5%85%85%E6%96%B9%E5%BC%8F
效果如图：
![251677058649_ pic](https://user-images.githubusercontent.com/118646023/220581517-22834f83-c501-4953-a484-e28148efb5f1.jpg)

方法2、逐一对每个序列进行查询
效果如图：
![271677058941_ pic](https://user-images.githubusercontent.com/118646023/220582237-d4cc4a1b-890a-4332-9e10-50a45044f8f4.jpg)

**Comment by SteveYurongSu** [comment]
> 已解决，两种方法 方法1、对于同时查多个非对齐序列，补空值，参考 https://iotdb.apache.org/zh/UserGuide/V1.0.x/Query-Data/Fill.html#%E5%A1%AB%E5%85%85%E6%96%B9%E5%BC%8F 效果如图： ![251677058649_ pic](https://user-images.githubusercontent.com/118646023/220581517-22834f83-c501-4953-a484-e28148efb5f1.jpg)
> 
> 方法2、逐一对每个序列进行查询 效果如图： ![271677058941_ pic](https://user-images.githubusercontent.com/118646023/220582237-d4cc4a1b-890a-4332-9e10-50a45044f8f4.jpg)

Ah GREAT!
