### ISSUE TITLE
TSStatus(code=400, message='', subStatus=None, redirectNode=TEndPoint(ip='xxxxx', port=xx))

### ISSUE THREAD

**Issue by wc188996** [apache/iotdb#9201]
iotdb version 1.0.0
client python
使用的是standalone 形式
频次 每秒插入大概40000+
使用的是 tablets一秒进行一次插入。
每次插入都看到报出错误
error status is TSStatus(code=400, message='no detailed failure reason in QueryStateMachine', subStatus=[TSStatus(code=400, message='', subStatus=None, redirectNode=TEndPoint(ip='xxxxx', port=xxxx)),

但是在数据库里看数据是插入进去的

每次都输出这种报错，请问一下 如何解决。

**Comment by HTHou** [comment]
可以试试更新 iotdb python client 1.0.1，bug 已经修复了

**Comment by wc188996** [comment]
> 可以试试更新 iotdb python client 1.0.1，bug 已经修复了

谢谢  我试试！
