### ISSUE TITLE
[Bug]  Java Python Api   SELECT LAST 语句 结果 字段类型均为 TEXT

### ISSUE THREAD

**Issue by zhengshubin** [apache/iotdb#9229]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

IOTDB 1.0.1
JAVA API   1.0.1
python api  1.0.1

### Describe the bug and provide the minimal reproduce step

JAVA API:
 SessionDataSet sessionDataSet = session.executeLastDataQuery(Arrays.asList("a.str", "a.int"));
        RowRecord rowRecord=null;
        while (sessionDataSet.hasNext()) {
            rowRecord=sessionDataSet.next();
            List<Field> fields = rowRecord.getFields();
            for (Field field : fields) {
                TSDataType dataType = field.getDataType();
                Object objectValue = field.getObjectValue(dataType);
                System.out.println(objectValue);
                System.out.println(dataType);  //always TEXT
PYTHON API:
sql = """
    
    SELECT   LAST
        str_value,    
       int_value
    FROM a
"""
result = session.execute_statement(sql)
while result.has_next():
    row_record = result.next()
    fields = row_record.get_fields()
    output=[  field.get_data_type() for field in fields]
    print(output)  //always TEXT

如果用 SELECT last_value(xx) 语句 结果 能正确输出对应DataType

### What did you expect to see?

使用 SELECT LAST 语句  结果能正确获取对应的数据类型，而不是全都为TEXT.

### What did you see instead?

全都为TEXT

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by SteveYurongSu** [comment]
@zhengshubin 是的，目前 LAST 结果集都是以 TEXT 形式返回的。这样做的原因是，目前定义的结果集的每一列必须是相同的类型（实现上的限制），而最新点可能是不同数据类型的。

如果你想获取原始类型的数据，就需要手工转型了：我们最后一列提供了每一个最新点的数据类型，可以根据最后一列进行转型，恢复到原始的数据类型。

当然，你也可以为我们包装一个自带转型功能的 LAST 专用结果集，哈哈 :)

**Comment by SteveYurongSu** [comment]
> @zhengshubin 是的，目前 LAST 结果集都是以 TEXT 形式返回的。这样做的原因是，目前定义的结果集的每一列必须是相同的类型（实现上的限制），而最新点可能是不同数据类型的。

我能够理解你的疑问，结果集这样表现其实对 Python 是奇怪的，但是对 Java 这种强类型的语言却是合理的。但是事实是，目前 Python 客户端简单地保持了 Java 客户端相同的语义，同时也引入了相同的麻烦。可以考虑加入一些语言层面的『糖』，让客户端更好用。
