### ISSUE TITLE
[Bug] Unable to build from source

### ISSUE THREAD

**Issue by lichadehehehe** [apache/iotdb#9326]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

OS: MacOS 13.0.1 on Apple Silicon
IoTDB version: 1.01 (latest)

### Describe the bug and provide the minimal reproduce step

Unable to build iotdb from source

Steps for reproducing the error:

1 execute `git clone https://github.com/apache/iotdb.git`
2 go to the root directory of iotdb by executing `cd iotdb`
3 execute `mvn clean package -pl distribution -am -DskipTest`
4 error reproduced as follows:

`[FATAL] Non-resolvable parent POM for org.apache.iotdb:iotdb-parent:1.2.0-SNAPSHOT: Could not transfer artifact org.apache:apache:pom:23 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/apache/apache/23/apache-23.pom and 'parent.relativePath' points at wrong local POM @ line 24, column 13`

### What did you expect to see?

iotdb built successfully from source

### What did you see instead?

iotdb failed to be built from source

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by HTHou** [comment]
Hi, what is your maven version?

**Comment by lichadehehehe** [comment]
> Hi, what is your maven version?

Hi HTHou, my environment info is as follows:

```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/homebrew/Cellar/maven/3.8.6/libexec
Java version: 18.0.2.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/18.0.2.1/libexec/openjdk.jdk/Contents/Home
Default locale: zh_CN_#Hans, platform encoding: UTF-8
OS name: "mac os x", version: "13.0.1", arch: "aarch64", family: "mac"
```

**Comment by lichadehehehe** [comment]
And I also manage to reproduce the bug with another environment as follows:
`Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.18, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-143-generic", arch: "amd64", family: "unix"`

**Comment by HTHou** [comment]
Hi, can you ping this URL on your environment?

```
ping repo.maven.apache.org
```

**Comment by lichadehehehe** [comment]
Upon diving deeper into the installation documentation I've realized I've missed the thrift compiler option. The correct installation command for macOS and Linux environments should be `mvn clean package -pl distribution -am -DskipTest -Dthrift.download-url=http://apache.org/licenses/LICENSE-2.0.txt -Dthrift.exec.absolute.path=/opt/homebrew/Cellar/thrift/0.16.0/bin/thrift` 
Please be advised to replace `/opt/homebrew/Cellar/thrift/0.16.0/bin/thrift` with your local absolute path of thrift.

**Comment by lichadehehehe** [comment]
> Hi, can you ping this URL on your environment?
> 
> ```
> ping repo.maven.apache.org
> ```

Kudos to HTHou. It turns out this issue is caused by the DNS server of my local network. Pinging `repo.maven.apache.org ` would be prompted `unknown host `. Switching the network environment or switching the DNS server is the correct way of doing it.
