### ISSUE TITLE
Grafana-plugin 问题

### ISSUE THREAD

**Issue by Archerll** [apache/iotdb#9442]
最新的Grafana-plugin安装后，无法在Grafana上进行查询

**Comment by Archerll** [comment]
grafana的日志是这样显示的
`INFO [03-22|21:16:40] QueryData called                         logger=plugin.apache-iotdb-datasource request="map[Headers:map[http_X-Datasource-Uid:KSab4GfVk http_X-Grafana-Org-Id:1 http_X-Panel-Id:123125] PluginContext:map[AppInstanceSettings:<nil> DataSourceInstanceSettings:map[BasicAuthEnabled:false BasicAuthUser: Database: DecryptedSecureJSONData:map[password:root] ID:2 JSONData:map[url:http://127.0.0.1:18080 username:root] Name:Apache IoTDB Type:apache-iotdb-datasource UID:KSab4GfVk URL: Updated:2023-03-22T11:14:29+08:00 User:] OrgID:1 PluginID:apache-iotdb-datasource User:map[Email:admin@localhost Login:admin Name: Role:Admin]] Queries:[map[Interval:2e+10 JSON:map[datasource:map[type:apache-iotdb-datasource uid:KSab4GfVk] datasourceId:2 expression:[RPN518KM] intervalMs:20000 maxDataPoints:1080 prefixPath:[root.dc1.m1] refId:A sqlType:SQL: Full Customized] MaxDataPoints:1080 QueryType: RefID:A TimeRange:map[From:2023-03-22T15:16:40.802+08:00 To:2023-03-22T21:16:40.803+08:00]]]]"
ERROR[03-22|21:16:40] prefixPath should not be null            logger=plugin.apache-iotdb-datasource`

**Comment by SteveYurongSu** [comment]
这是一个常见问题。请确保 grafana plugin 的版本号跟 IoTDB 的版本号一一对应，至少大版本号需要对应。

例如:
* grafana plugin 版本号 1.0.1 - IoTDB 1.1.0  ->  不兼容
* grafana plugin 版本号 1.1.0 - IoTDB 1.1.0  ->  兼容
* * grafana plugin 版本号 1.0.0 - IoTDB 1.0.1  ->  兼容
