### ISSUE TITLE
路径包含汉字[Bug] 

### ISSUE THREAD

**Issue by cqconelin** [apache/iotdb#9486]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

windows11  
iotdb 1.0.1

### Describe the bug and provide the minimal reproduce step

insert into root.ln.汉字(timestamp,status) values(1,true)

Msg: 305: org.apache.iotdb.commons.exception.IoTDBException: Unexpected errors: null

### What did you expect to see?

Msg: The statement is executed successfully.

### What did you see instead?

Msg: 305: org.apache.iotdb.commons.exception.IoTDBException: Unexpected errors: null

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by HTHou** [comment]
https://github.com/apache/iotdb/pull/10051 fixed this bug.
