### ISSUE TITLE
java 使用iotdb-session的问题

### ISSUE THREAD

**Issue by TheDawnXu** [apache/iotdb#9490]
java.lang.ClassNotFoundException: org.apache.iotdb.service.rpc.thrift.TSProtocolVersion
jar包版本是不是改更新了

**Comment by jixuan1989** [comment]
该类一直存在。是thrift生成的。
后续有问题请附上版本号，环境、复现场景等（这是自行编译源码？刚下载源码后没编译就导入IDE？还是客户端使用依赖？）
